services:
  window-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: window-container
    ports:
      - "6080:6080" # noVNC (open in browser)
      - "5900:5900" # raw VNC
    volumes:
      - ./recordings:/recordings
      - ./recordings/vlc/example.mp4:/home/vlcuser/example.mp4:ro
    environment:
      DISPLAY: ":99"
      SCREEN_SIZE: "1440x900x24"
      APP_STARTCOMMAND: "su -m vlcuser -c 'XDG_RUNTIME_DIR=/tmp/runtime-vlcuser vlc --no-audio --play-and-exit --vout xcb_x11 /home/vlcuser/example.mp4'"
      APP_LOG_FILE: "/tmp/vlc.log"
      APP_WINDOW_CLASS: "vlc"
      APP_WINDOW_TITLE: "VLC media player"
      AUTO_POSITION: "1"
      WINDOW_X: "20"
      WINDOW_Y: "20"
      WINDOW_WIDTH: "1400"
      WINDOW_HEIGHT: "860"
    restart: "no"
