#!/usr/bin/env bash
# Create a ready-to-use Thunderbird (or Betterbird) profile from scratch.
#
#   seed-mozilla-profile.sh <profile-root> [profile-name]
#
# e.g. seed-mozilla-profile.sh /root/.thunderbird parrot
#
# Writes profiles.ini and a prefs.js that already contains the IMAP account,
# the identity and the SMTP server, so the recorded macro starts at a synced
# mailbox instead of a six-page account wizard.  Also switches off first-run
# dialogs, update checks and telemetry, all of which would otherwise show up as
# windows and network traffic in the middle of a measurement.
#
# One thing this cannot do: store the password.  Thunderbird keeps it in an
# NSS key4.db that no shell script can author.  Two ways around it:
#   * let the macro type the password once at the first sync (it is prompted at
#     the same point on every run, because the profile is rebuilt each time), or
#   * capture a profile that already has it and commit it as profile.tar.zst -
#     see the README.  seed-profile.sh then wins over this script.
set -euo pipefail

PROFILE_ROOT="${1:?usage: seed-mozilla-profile.sh <profile-root> [profile-name]}"
PROFILE_NAME="${2:-parrot}"

# readlink -f, so this still resolves when the script is reached through a
# symlink: BASH_SOURCE is then the link's path and ../account.env would not
# exist next to it.  The prebuilt image relies on this - it puts start.sh on
# PATH as /usr/local/bin/parrot-mailserver-start.
HERE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
# shellcheck source=../account.env
source "${HERE}/../account.env"

log() { printf '[seed-mozilla] %s\n' "$*"; }

PROFILE_DIR="${PROFILE_ROOT}/${PROFILE_NAME}"
mkdir -p "$PROFILE_DIR"

# socketType / try_ssl: 0 = none, 2 = STARTTLS, 3 = SSL/TLS
case "${PARROT_MAIL_SECURITY:-none}" in
    none)
        IMAP_PORT="$PARROT_IMAP_PORT";  IMAP_SOCKET=0
        SMTP_PORT="$PARROT_SUBMISSION_PORT"; SMTP_SOCKET=0
        ;;
    starttls)
        IMAP_PORT="$PARROT_IMAP_PORT";  IMAP_SOCKET=2
        SMTP_PORT="$PARROT_SUBMISSION_PORT"; SMTP_SOCKET=2
        ;;
    tls)
        IMAP_PORT="$PARROT_IMAPS_PORT"; IMAP_SOCKET=3
        SMTP_PORT="$PARROT_SMTPS_PORT"; SMTP_SOCKET=3
        ;;
    *)
        log "ERROR: PARROT_MAIL_SECURITY must be none, starttls or tls"
        exit 1
        ;;
esac

cat > "${PROFILE_ROOT}/profiles.ini" <<INI
[Profile0]
Name=${PROFILE_NAME}
IsRelative=1
Path=${PROFILE_NAME}
Default=1

[General]
StartWithLastProfile=1
Version=2
INI

# authMethod 3 = "password, transmitted insecurely".  Correct for every value of
# PARROT_MAIL_SECURITY: the password is sent as an IMAP LOGIN either in the
# clear (none) or inside the TLS session (starttls/tls).  Dovecot offers only
# PLAIN and LOGIN, so asking Thunderbird for an encrypted password (4) would
# fail to negotiate.
cat > "${PROFILE_DIR}/prefs.js" <<PREFS
// Generated by seed-mozilla-profile.sh - do not edit by hand.

// ---- the benchmark account -------------------------------------------------
// account2 is Local Folders and must be listed here too - Thunderbird treats an
// unlisted account as nonexistent and falls back to the setup wizard.
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account2.server", "server2");

user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.hostname", "${PARROT_MAIL_HOST}");
user_pref("mail.server.server1.name", "${PARROT_MAIL_ADDRESS}");
user_pref("mail.server.server1.userName", "${PARROT_MAIL_USER}");
user_pref("mail.server.server1.port", ${IMAP_PORT});
user_pref("mail.server.server1.socketType", ${IMAP_SOCKET});
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.check_time", 10);
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/${PARROT_MAIL_HOST}");
user_pref("mail.server.server1.max_cached_connections", 5);

// Local Folders, which Thunderbird insists on having for Trash and Outbox.
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");

user_pref("mail.identity.id1.useremail", "${PARROT_MAIL_ADDRESS}");
user_pref("mail.identity.id1.fullName", "${PARROT_MAIL_REALNAME}");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.compose_html", true);
user_pref("mail.identity.id1.fcc", true);
user_pref("mail.identity.id1.draft_folder", "imap://${PARROT_MAIL_USER}@${PARROT_MAIL_HOST}/Drafts");
user_pref("mail.identity.id1.fcc_folder", "imap://${PARROT_MAIL_USER}@${PARROT_MAIL_HOST}/Sent");

user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "${PARROT_MAIL_HOST}");
user_pref("mail.smtpserver.smtp1.port", ${SMTP_PORT});
user_pref("mail.smtpserver.smtp1.try_ssl", ${SMTP_SOCKET});
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "${PARROT_MAIL_USER}");
user_pref("mail.smtpserver.smtp1.description", "Parrot benchmark submission");

// ---- keep the first run quiet ----------------------------------------------
// Every dialog suppressed here would otherwise appear mid-measurement, and
// every check disabled here would otherwise generate network traffic.
// Ctrl+Enter otherwise raises "Are you sure you are ready to send this
// message?", which would put a modal in the middle of the send step and force
// the macro to click a button at coordinates instead of using a keystroke.
user_pref("mail.warn_on_send_accel_key", false);

user_pref("mail.provider.suppress_dialog_on_startup", true);
user_pref("mail.rights.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mail.shell.checkDefaultMail", false);
user_pref("mail.spotlight.firstRunDone", true);
user_pref("mail.winsearch.firstRunDone", true);
user_pref("mail.biff.show_alert", false);
user_pref("mail.biff.play_sound", false);
user_pref("mail.tabs.drawInTitlebar", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.service.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.crashreporter.enabled", false);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("browser.region.network.url", "");
user_pref("mail.chat.enabled", false);
user_pref("calendar.itip.showImipBar", false);
user_pref("mail.cloud_files.enabled", false);
user_pref("gfx.webrender.all", false);

// Deterministic layout: same pane sizes and sort order in every client run.
user_pref("mailnews.default_sort_type", 18);   // 18 = by date
user_pref("mailnews.default_sort_order", 2);   // 2 = descending (newest first)
user_pref("mailnews.default_view_flags", 0);   // no threading, flat list
PREFS

log "wrote ${PROFILE_ROOT}/profiles.ini and ${PROFILE_DIR}/prefs.js"
log "account ${PARROT_MAIL_ADDRESS} via ${PARROT_MAIL_HOST}:${IMAP_PORT} (security=${PARROT_MAIL_SECURITY:-none})"

# Thunderbird ships its own NSS trust store and ignores the system one on
# Linux, so the CA the client container installed system-wide is invisible to
# it.  With PARROT_MAIL_SECURITY=none this does not matter; with TLS it is the
# difference between a silent sync and a modal "Add Security Exception" dialog.
if [[ "${PARROT_MAIL_SECURITY:-none}" != "none" ]]; then
    ca_file="$(find /usr/local/share/ca-certificates -name 'parrot-mail-*.crt' 2>/dev/null | head -1)"
    if [[ -n "$ca_file" ]] && command -v certutil >/dev/null 2>&1; then
        certutil -N -d "sql:${PROFILE_DIR}" --empty-password 2>/dev/null || true
        n=0
        for f in /usr/local/share/ca-certificates/parrot-mail-*.crt; do
            n=$((n + 1))
            certutil -A -n "Parrot benchmark ${n}" -t 'C,C,C' -d "sql:${PROFILE_DIR}" -i "$f" \
                2>/dev/null || log "WARNING: certutil could not import ${f}"
        done
        log "imported ${n} certificate(s) into the profile's NSS store"
    else
        log "WARNING: PARROT_MAIL_SECURITY=${PARROT_MAIL_SECURITY} but no CA file or no certutil"
        log "install libnss3-tools, or expect a certificate dialog on first sync"
    fi
fi

log "the password (${PARROT_MAIL_PASS}) still has to be entered once, at the first sync"
