#!/usr/bin/env bash
# Drive AbiWord through applications/wordprocessors/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# AbiWord is driven through DIALOGS wherever a toolbar combo would do, because
# every combo in this application is either inert or self-positioning:
#   * the font size box accepts typing and never applies it;
#   * the style box and the zoom box place the SELECTED entry under the pointer,
#     so a fixed coordinate hits a different item once the selection changes;
#   * the export file-type box does not open under a synthetic click at all.
set -euo pipefail

# Matched on TITLE, not class. AbiWord never destroys its Find, Replace and
# message-box windows - they stay IsViewable at 0,0 after being closed and sort
# AHEAD of the document - so a class match would photograph a dead 478x254
# dialog from block 8 onwards. See MEASUREMENTS.md.
TITLE_RE='^(Untitled1|[*]?Parrot Field Report)$'

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
CLICK3() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 3 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - which would be baked into the reference screenshot and then fail to
# reappear on replay.
#
# 700,450 is the middle of the text area. It is inside the page at both zoom
# levels the run uses (Page Width for blocks 1-5, 100% from block 6 on), and
# body text raises no tooltip.
park() { X mousemove 700 450; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion is on the TITLE match, because that is what the capture uses for
# this app. It checks both that exactly one window matched and that it is the
# 1440x900 document - the second half matters because the Font dialog is itself
# resized to 1440x900 by the pin rule, so size alone proves nothing here.
CP() {
    sleep "${2:-3}"
    park
    n="$(Q "xdotool search --onlyvisible --name '${TITLE_RE}' | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --name '${TITLE_RE}' | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving AbiWord ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `abiword` through the startcommand and
# waited for the window. Nothing has to be dismissed - AbiWord is the only app
# in this group that needs no profile seeding at all.
sleep 30
CP "Load app" 5

# --- 2. Open document --------------------------------------------------------
# A GTK file chooser: typing a path beginning with `/` opens GTK's location
# entry, so nothing is clicked. The empty Untitled1 window is REUSED.
#
# AbiWord paginates this document to 97 pages where LibreOffice and OpenOffice
# both give 98 - which is why script.md counts keystrokes and never names a page.
K ctrl+o; sleep 5
T '/tmp/parrot-report.odt'; sleep 2
K Return
CP "Open document" 50

# --- 3. Page through ---------------------------------------------------------
# Ends on "Page: 5/97", at the default Page Width zoom.
for _ in $(seq 1 10); do K Next; sleep 0.8; done
CP "Page through" 6

# --- 4. Jump to end ----------------------------------------------------------
# Needs up to 25 s to settle. Measured at 8 s and again at 20 s still reading
# "Page: 5/97", which looks exactly like a keystroke that did nothing.
K ctrl+End
CP "Jump to end" 30

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 30

# --- 6. Zoom -----------------------------------------------------------------
# View > Zoom, never the toolbar combo - the combo puts the SELECTED entry under
# the pointer, so the same click lands on a different item once the selection
# changes. The [Zoom] dialog has no OK: the value applies as it is set and Close
# only dismisses.
CLICK 103 12;  sleep 3           # View menu
CLICK 127 315; sleep 3           # Zoom submenu
CLICK 400 314; sleep 4           # Zoom...
CLICK 27 196;  sleep 2           # Percent radio
CLICK3 58 229; sleep 1           # its field
T '150'; sleep 1
K Tab; sleep 3                   # commit the spin value
CLICK 130 261; sleep 6           # Close
CLICK 103 12;  sleep 3
CLICK 127 315; sleep 3
CLICK 400 417; sleep 6           # Zoom to 100%
CP "Zoom" 6

# --- 7. Find word ------------------------------------------------------------
# After the third Find: "Page: 3/97" with Cormorant selected in the same
# sentence LibreOffice and OpenOffice both land on from their page 3.
K ctrl+f; sleep 4
T 'Cormorant'; sleep 2
CLICK 413 30; sleep 4            # Find
CLICK 413 30; sleep 4
CLICK 413 30; sleep 4
CLICK 432 234; sleep 3           # Close
CP "Find word" 5

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+Home FIRST. AbiWord's Replace All runs from the cursor to the end of the
# document and does not wrap: started from block 7's match on page 3 it replaces
# 118 of 120 and reports "has made 118 replacements" as though that were the
# answer. From the top it reports 120, which is what the document contains.
#
# Ctrl+H, not Ctrl+R. Ctrl+R is Align Right in AbiWord and silently reformats
# the paragraph the cursor is in.
#
# The Find field does NOT carry `Cormorant` over from block 7 - it opens empty.
K ctrl+Home; sleep 25
K ctrl+h; sleep 4
T 'Cormorant'; sleep 1
CLICK 199 76; sleep 1            # Replace with field
T 'Shearwater'; sleep 1
CLICK 398 122; sleep 25          # Replace All -> "has made 120 replacements."
CLICK 719 504; sleep 3           # OK on the count box
CLICK 432 234; sleep 3           # Close
CP "Replace all" 5

# --- 9. Type paragraph -------------------------------------------------------
# Return first, so the block is its own paragraph rather than being glued to the
# end of the last one. One keystroke at a time rather than a paste.
K ctrl+End; sleep 30
K Return; sleep 2
T 'The kestrel circled above the reservoir before dawn.'; sleep 2; K Return; sleep 2
T 'Three technicians logged the reading and filed the sheet.'; sleep 2; K Return; sleep 2
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 5

# --- 10. Bold a line ---------------------------------------------------------
# Confirmed in block 11: the Font dialog opens with Bold selected in its Style
# list, which is the only confirmation AbiWord offers - its status bar has no
# selection word count.
K shift+Home; sleep 2
K ctrl+b
CP "Bold a line" 4

# --- 11. Resize the text -----------------------------------------------------
# Format > Font (Ctrl+D), NOT the toolbar size box. Typing 18 into that box and
# pressing Return leaves the box reading 18 and the text at 12 pt - no error, no
# change. Neither a second Return nor KP_Enter commits it.
K ctrl+d; sleep 6
CLICK 1290 213; sleep 2          # size 18 in the list
CLICK 1389 875; sleep 5          # OK
CP "Resize the text" 5

# --- 12. Apply heading -------------------------------------------------------
# Format > Create and Modify Styles, NOT the style box - a triple-click on that
# opens a 178x733 popup positioned so the CURRENT style sits under the pointer,
# with Heading 1 scrolled out of view.
#
# The list is filtered to styles in use, and Heading 1 is in use because the
# document ships twelve chapter headings, so its row is a property of the
# document rather than of the run.
CLICK 211 12;  sleep 3           # Format menu
CLICK 300 466; sleep 5           # Create and Modify Styles...
CLICK 565 433; sleep 2           # Heading 1
CLICK 916 662; sleep 4           # Apply
CLICK 827 662; sleep 4           # Close
CP "Apply heading" 5

# --- 13. Insert image --------------------------------------------------------
# Insert > Picture... - a GTK file chooser again, so the path is typed.
# AbiWord raises no context toolbar for a selected image and lays it out inline,
# so unlike OpenOffice there is nothing to dismiss afterwards.
K ctrl+End; sleep 15
K Return; sleep 3
CLICK 154 12;  sleep 3           # Insert menu
CLICK 188 490; sleep 5           # Picture...
T '/tmp/parrot.png'; sleep 2
K Return
CP "Insert image" 15

# --- 14. Insert table --------------------------------------------------------
# AbiWord defaults the dialog to 5 columns by 2 rows, so both spin fields have
# to be set.
K ctrl+End; sleep 15
K Return; sleep 3
CLICK 154 12;  sleep 3           # Insert menu
CLICK 182 113; sleep 5           # Table...
CLICK3 250 50; sleep 1; T '3'; sleep 1     # Number of columns
CLICK3 250 93; sleep 1; T '4'; sleep 1     # Number of rows
CLICK 317 235; sleep 6                     # Insert
T 'Alpha'; sleep 1; K Tab; sleep 1
T 'Beta';  sleep 1; K Tab; sleep 1
T 'Gamma'
CP "Insert table" 5

# --- 15. Insert page break ---------------------------------------------------
# ONE Ctrl+End, unlike LibreOffice and OpenOffice. In both of those the first
# one only reaches the end of the table and Ctrl+Return there is a silent no-op;
# in AbiWord one press leaves the table and reaches the end of the document.
# Measured: the cursor lands below the table's last row and the style box reads
# Text body. "Page: 98/98" -> "Page: 99/99".
K ctrl+End; sleep 15
K ctrl+Return
CP "Insert page break" 15

# --- 16. Undo and redo -------------------------------------------------------
# 99/99 -> 98/98 -> 99/99.
K ctrl+z; sleep 15
K ctrl+y
CP "Undo and redo" 15

# --- 17. Save ----------------------------------------------------------------
# No dialog: AbiWord writes ODT natively and does not ask about keeping it.
K ctrl+s
CP "Save" 25

# --- 18. Export PDF ----------------------------------------------------------
# File > Print > Print to File. There is no "Export as PDF" in AbiWord's File
# menu, and `Save Copy...` is a trap: its file-type box stays on AbiWord format,
# a .pdf name raises "The given file extension does not match the chosen file
# type!", and answering Yes writes an AbiWord document called parrot-report.pdf.
# The type combo does not open under a synthetic click at all.
#
# script.md allows print-to-file for exactly this case. PDF is already the
# default output format and All Pages is already the default range, so only the
# filename has to be set.
#
# Selecting the printer WIDENS the dialog from 601 to 635 px, which moves every
# button below it - these coordinates are the post-selection ones.
CLICK 19 12;   sleep 3           # File menu
CLICK 52 289;  sleep 8           # Print...
CLICK 503 301; sleep 4           # the "Print to File" row
CLICK 523 512; sleep 5           # the File button -> [Select a filename]
K ctrl+a; sleep 1
T '/tmp/parrot-report.pdf'; sleep 2
CLICK 1237 883; sleep 4          # Select
CLICK 995 701                    # Print
CP "Export PDF" 60

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
