#!/usr/bin/env bash
# Drive LibreOffice Writer through applications/wordprocessors/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
set -euo pipefail

CLASS=libreoffice
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
CLICK3() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 3 1; }
CLICK2() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 2 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - which would be baked into the reference screenshot and then fail to
# reappear on replay.
#
# 140,450 is the grey workspace to the left of the page: not the toolbar, not
# the page, not the sidebar, and nothing hovers there.
park() { X mousemove 140 450; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion matters. record-macro.py captures
# `xdotool search --onlyvisible --class <class> | head -n1` - the FIRST match,
# not the largest - and every Writer dialog shares the document's WM_CLASS. A
# checkpoint taken with one still on screen becomes a photograph of a modal, and
# that image is what every future replay is measured against.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving LibreOffice Writer ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `soffice --writer` through the
# startcommand and waited for the window. What it cannot wait for is Writer
# finishing its first paint, which is around 25 s cold in this container.
#
# Nothing has to be dismissed: the seeded profile turns off the Tip of the Day
# modal, the "first time you have run 24.2" infobar and document recovery. See
# install.sh for why each one is there.
sleep 45
CP "Load app" 5

# --- 2. Open document --------------------------------------------------------
# The Open dialog's filename field has focus when it appears, so nothing is
# clicked. The empty `Untitled 1` window is REPLACED rather than added to -
# Writer reuses an unmodified blank document - so there is still exactly one
# window afterwards.
K ctrl+o; sleep 4
T '/tmp/parrot-report.odt'; sleep 2
K Return
CP "Open document" 40

# --- 3. Page through ---------------------------------------------------------
# Ends on "Pages 6 and 7 of 98": ten presses move six pages, because the view
# spans two pages at 100%.
for _ in $(seq 1 10); do K Next; sleep 0.5; done
CP "Page through" 4

# --- 4. Jump to end ----------------------------------------------------------
K ctrl+End
CP "Jump to end" 8

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 6

# --- 6. Zoom -----------------------------------------------------------------
# Double-clicking the zoom percentage in the status bar opens `Zoom & View
# Layout` directly. Two routes that do NOT work and were tried first: hovering
# View > Zoom (the menu ignores a warped pointer) and Alt+V, Up, Return.
CLICK2 1418 889; sleep 4
CLICK  568 472; sleep 1          # Custom radio
CLICK3 679 472; sleep 1          # its field, contents selected
T '150%'; sleep 1
CLICK  841 512; sleep 5          # OK
CLICK2 1418 889; sleep 4
CLICK  568 449; sleep 1          # 100% radio
CLICK  841 512
CP "Zoom" 5

# --- 7. Find word ------------------------------------------------------------
# The find toolbar opens at the foot of the document area; it is not a separate
# X window. After the third Return the status bar reads "Selected: 1 word, 9
# characters" - nine characters is `Cormorant`, so the match landed on the
# anchor rather than somewhere merely plausible.
K ctrl+f; sleep 3
T 'Cormorant'; sleep 2
K Return; sleep 2
K Return; sleep 2
K Return; sleep 2
K Escape
CP "Find word" 4

# --- 8. Replace all ----------------------------------------------------------
# Replace All is the CLICK at 938,414. Alt+A is Find All, and it fails in the
# worst way available: it reports "Search key found 120 times", selects 120
# words, and replaces nothing. See MEASUREMENTS.md.
#
# The Replace field does not follow Find in the tab order - Match case and Whole
# words come first - so it is clicked.
K ctrl+h; sleep 4
T 'Cormorant'; sleep 1
CLICK 754 368; sleep 1
T 'Shearwater'; sleep 1
CLICK 938 414; sleep 10          # -> "Search key replaced 120 times."
CLICK 949 623                    # Close
CP "Replace all" 4

# --- 9. Type paragraph -------------------------------------------------------
# Return first, so the block is its own paragraph rather than being glued to the
# end of the last one. One keystroke at a time rather than a paste: the point of
# the block is what typing into a 98-page document costs.
K ctrl+End; sleep 6
K Return; sleep 1
T 'The kestrel circled above the reservoir before dawn.'; sleep 1; K Return; sleep 1
T 'Three technicians logged the reading and filed the sheet.'; sleep 1; K Return; sleep 1
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 4

# --- 10. Bold a line ---------------------------------------------------------
# Ends on "Selected: 9 words, 53 characters", which is exactly the line above.
K shift+Home; sleep 1
K ctrl+b
CP "Bold a line" 3

# --- 11. Resize the text -----------------------------------------------------
# Enter in the size box returns focus to the document, but the selection is
# STILL LIVE afterwards - a printable character sent next would replace the
# whole line. The next block only uses the style box, so that is safe here.
CLICK3 430 60; sleep 2
T '18'; sleep 1
K Return
CP "Resize the text" 4

# --- 12. Apply heading -------------------------------------------------------
# The style box, same behaviour. Ends with "Heading Numbering : Level 1" in the
# status bar. This overrides the 18 pt from block 11, which is what the script
# asks for and is identical in every application.
CLICK3 80 60; sleep 2
T 'Heading 1'; sleep 1
K Return
CP "Apply heading" 5

# --- 13. Insert image --------------------------------------------------------
# Insert > Image. The menu is drawn inside the main window rather than as its own
# X window, so it never appears in a window list. Clicking the entries works;
# hovering them does not.
K ctrl+End; sleep 3
K Return; sleep 2
CLICK 123 9;  sleep 3            # Insert menu
CLICK 155 71; sleep 4            # Image...
T '/tmp/parrot.png'; sleep 2
K Return
CP "Insert image" 10

# --- 14. Insert table --------------------------------------------------------
# Escape FIRST. The image is still selected after block 13, and while a drawing
# object is selected every text-insertion command is greyed out - Ctrl+F12 then
# does nothing at all, silently.
#
# Ctrl+F12 only works because pin-windows.sh writes a fluxbox keys file with no
# keyboard bindings. The default one binds Control+F1..F12 to workspace
# switching and grabs them at the X server, so Writer never sees the keystroke
# and the display jumps to an empty workspace instead.
K Escape; sleep 2
K ctrl+End; sleep 3
K Return; sleep 2
K ctrl+F12; sleep 5
CLICK3 624 312; sleep 1; T '3'; sleep 1     # Columns
CLICK3 879 312; sleep 1; T '4'; sleep 1     # Rows
CLICK  906 624; sleep 5                     # Insert
T 'Alpha'; sleep 1; K Tab; sleep 1
T 'Beta';  sleep 1; K Tab; sleep 1
T 'Gamma'
CP "Insert table" 4

# --- 15. Insert page break ---------------------------------------------------
# Ctrl+End TWICE. The cursor is in the last table cell after block 14, and in
# Writer the first Ctrl+End only goes to the end of the TABLE - the status bar
# still reads Table4:C4. Ctrl+Return there is a no-op, and the page count does
# not move: 99 of 99 before and after. The second one reaches the end of the
# document, and then the break takes: "Page 100 of 100".
K ctrl+End; sleep 3
K ctrl+End; sleep 3
K ctrl+Return
CP "Insert page break" 5

# --- 16. Undo and redo -------------------------------------------------------
# A page break is a single undo unit in every application in this group, which
# is why the script exercises undo on this and not on the typed paragraph.
# 100 of 100 -> 99 of 99 -> 100 of 100.
K ctrl+z; sleep 5
K ctrl+y
CP "Undo and redo" 5

# --- 17. Save ----------------------------------------------------------------
# No dialog: ODT is Writer's native format, so nothing asks about keeping it.
K ctrl+s
CP "Save" 14

# --- 18. Export PDF ----------------------------------------------------------
# File > Export As > Export as PDF..., which opens PDF Options and then a file
# dialog. Range defaults to All, so the whole document goes.
CLICK 15 9;    sleep 3           # File menu
CLICK 60 324;  sleep 3           # Export As submenu
CLICK 285 318; sleep 6           # Export as PDF...
CLICK 1004 619; sleep 5          # PDF Options -> Export
K ctrl+a; sleep 1
T '/tmp/parrot-report.pdf'; sleep 2
K Return
CP "Export PDF" 35

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
