#!/usr/bin/env bash
# Drive SchildiChat Desktop through applications/chatclients/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowraise`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THE RULES THIS FILE IS BUILT AROUND, all measured - three inherited from
# Element, one that is SchildiChat's own:
#
#   1. Never click a room in the room list. The list sorts by recent activity,
#      so it moves as the scenario touches rooms. Ctrl+K takes a name. Here the
#      rows also carry a message preview and are taller than Element's, so a
#      position copied across from Element would be wrong even on run one.
#
#   2. A dialog closing means NOTHING. The upload has a second confirmation
#      step, and skipping it leaves the server with no event while the UI looks
#      like it worked. Every mutating block here was verified with
#      matrix-truth.py, not by eye.
#
#   3. A mapped window is not a painted window - see wait_paint() below and the
#      Element write-up that cost a recording to produce.
#
#   4. Unlike Element, the message context menu is CLICKED rather than driven
#      with Down/Return. Element's menu opens with React focused so counting
#      matters; SchildiChat's is positioned against the message, and both the
#      message and the menu are at fixed positions in a recording.
set -euo pipefail

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
RCLICK() { X mousemove "$1" "$2"; sleep 0.4; X click 3; }

# Open a room by name through the spotlight. Immune to the room list reordering,
# and the only sane way to reach Parrot Echo and Parrot Firehose, which sit far
# down a 66-room list.
ROOM() { K ctrl+k; sleep 2; T "$1"; sleep 4; K Return; sleep "${2:-14}"; }

# Park the pointer somewhere inert before every capture. SchildiChat shows a
# hover action bar on whichever message is under the pointer, which is baked
# into the reference image - so the parked position must be identical at record
# and replay time, which it is, because this function is the only thing that
# moves the pointer before a capture.
park() { X mousemove 900 300; sleep 1; }

# The size of a full-screen PNG, in bytes. `import` is a passive X client - it
# reads the root window and sends no input event - so calling it mid-recording
# does not put anything into the macro.
SHOT() { Q 'export DISPLAY=:99; import -window root /tmp/parrot-probe.png 2>/dev/null; stat -c %s /tmp/parrot-probe.png'; }

# Just above a blank or spinner screen, and well below any real one. Measured on
# Element: the loading spinner is ~2.4 kB, real screens are 99 kB and up. The
# threshold must sit near the spinner, not in the middle - a value picked off
# the photographic welcome screen condemns every real screen after it.
PAINTED=30000

# Block until the display actually has the client on it, rather than guessing
# with a sleep. Aborts the run instead of driving a screen that is not there: a
# recording made against a loading screen looks successful in every log line and
# is worthless.
wait_paint() {
    local limit="${1:-420}" waited=0 sz
    while (( waited < limit )); do
        sz="$(SHOT)"
        if [[ "${sz:-0}" -gt "$PAINTED" ]]; then
            echo "  [paint] first painted frame after ${waited}s"
            return 0
        fi
        sleep 5; waited=$(( waited + 5 ))
    done
    echo "  FATAL: nothing painted after ${limit}s - the app never came up" >&2
    exit 1
}

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# `--class schildichat` also matches the GTK file chooser, whose WM_CLASS is
# schildichat-desktop - the count check catches that, and the geometry check
# catches it too because the chooser is 1124x822 rather than 1440x900.
#
# The member list and the image lightbox are in-window panels, not separate
# windows, so they never trip this - which is exactly why blocks 7 and 9 close
# them explicitly rather than trusting the guard.
CP() {
    sleep "${2:-4}"
    park
    n="$(Q "xdotool search --onlyvisible --class schildichat | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class schildichat | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1 - the file chooser is probably still open"
    sz="$(SHOT)"
    [[ "${sz:-0}" -gt "$PAINTED" ]] || echo "  WARNING: '$1' would capture a blank or loading screen (${sz}B)"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving SchildiChat Desktop ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `schildichat-desktop` - the wrapper from
# install.sh, which drops to uid 1001, starts a session bus and unlocks a secret
# service. Without all three it either crash-loops with no window or stops on an
# "unsupported keyring" modal; see MEASUREMENTS.md.
#
# The head time is deliberately the SAME as nheko's and Element's - 20 s in
# record-session.sh, 25 s here, 5 s in CP - because it is measured time, and a
# client given a longer head burns more energy for no reason of its own.
wait_paint
sleep 25
CP "Load app" 5

# --- 2. Sign in --------------------------------------------------------------
# Homeserver FIRST, defaulting to matrix.org, so the server has to be changed
# before any credential is typed.
CLICK 614 329; sleep 5                       # Sign In
CLICK 999 241; sleep 5                       # Edit, next to matrix.org
# The dialog opens with "Other homeserver" selected AND its field focused.
T 'http://matrix.parrot.test:8008'; sleep 3
CLICK 714 578; sleep 10                      # Continue
T 'parrot'; sleep 1                          # Username is already focused
CLICK 822 410; sleep 1                       # Password
T 'parrot'; sleep 1
CLICK 822 504
CP "Sign in" 15

# --- 3. Initial sync ---------------------------------------------------------
# The measurement this block exists for: 8000 messages, 66 rooms and a
# 509-member room arriving at once.
#
# ONE prompt here, not Element's chain of three - and it arrives immediately
# rather than several seconds after the room list settles. "Show preview" would
# join a SchildiChat release-announcement room, which would add a room to the
# list and network traffic of the client's choosing to a measured run.
sleep 40
CLICK 175 170; sleep 10                      # Update notifications -> No
CP "Initial sync" 12

# --- 4. Open busy room -------------------------------------------------------
ROOM 'Aurora Release' 22
CP "Open busy room" 8

# --- 5. Scroll back ----------------------------------------------------------
X mousemove 900 400; sleep 1
for _ in $(seq 1 10); do K Prior; sleep 2; done
CP "Scroll back" 8

# --- 6. Jump to live ---------------------------------------------------------
# Not `End`: the composer holds focus, so End is a text-cursor key and never
# reaches the timeline. Measured in all three clients so far.
CLICK 1392 800
CP "Jump to live" 10

# --- 7. Open member list -----------------------------------------------------
# TWO steps, unlike Element's one-click facepile: room info, then People. Both
# panels are in-window, so the checkpoint guard cannot see them - hence the
# explicit close before the capture, which also makes the block boundary mean
# the same thing as it does in the other clients.
CLICK 1403 27; sleep 6                       # Room info
CLICK 1263 295; sleep 14                     # People 509
CLICK 1411 86                                # close
CP "Open member list" 5

# --- 8. Open photo room ------------------------------------------------------
# 400 images. They render only because the homeserver sets
# enable_authenticated_media false; see ../nheko/MEASUREMENTS.md.
ROOM 'Field Photos' 20
CP "Open photo room" 8

# --- 9. View image full size -------------------------------------------------
# An in-window lightbox, closed before the checkpoint for the same
# block-boundary reason as block 7.
CLICK 653 690; sleep 12
CLICK 1408 31                                # close the lightbox
CP "View image full size" 5

# --- 10. Scroll thumbnails ---------------------------------------------------
X mousemove 900 400; sleep 1
for _ in $(seq 1 5); do K Prior; sleep 3; done
CP "Scroll thumbnails" 8

# --- 11. Filter room list ----------------------------------------------------
K ctrl+k; sleep 2
T 'windvane'
CP "Filter room list" 5

# --- 12. Open filtered room --------------------------------------------------
K Return; sleep 18
CP "Open filtered room" 6

# --- 13. Send message --------------------------------------------------------
CLICK 900 872; sleep 2
T 'Thank you so much'; sleep 1
K Return
CP "Send message" 8

# --- 14. Reply to message ----------------------------------------------------
# The menu is clicked, not counted - see rule 4 at the top. Reply is the second
# item; "Reply in thread" is the third and would open a side panel that changes
# the timeline width for every coordinate after it.
RCLICK 657 687; sleep 3
CLICK 717 436; sleep 4                       # Reply
T 'Agreed, going out today'; sleep 1
K Return
CP "Reply to message" 8

# --- 15. React to message ----------------------------------------------------
# TARGET THE ORIGINAL, NOT THE QUOTE. The reply just sent renders a quoted copy
# of the same text; reacting to that attaches the reaction to the reply event
# instead, and only ground truth can tell the difference.
RCLICK 657 581; sleep 3
CLICK 717 291; sleep 4                       # React -> emoji picker
CLICK 866 693                                # 👍 in Quick Reactions
CP "React to message" 8

# --- 16. Edit message --------------------------------------------------------
# Own messages are RIGHT-ALIGNED bubbles here, so this aims at the right-hand
# side of the timeline rather than Element's left. The own-message menu inserts
# Edit as the fourth item.
RCLICK 1281 683; sleep 3
CLICK 1322 470; sleep 4                      # Edit
K ctrl+a; sleep 1
T 'Thank you so much indeed'; sleep 1
K Return
CP "Edit message" 8

# --- 17. Upload image --------------------------------------------------------
# THE CHOOSER OPENS ON "Recent", WHICH IS EMPTY ON A FRESH PROFILE, so clicking
# a row selects nothing and the whole block silently sends nothing. The path is
# typed instead - the same action nheko's block 17 uses.
#
# RETURN DOES NOT ACCEPT THE LOCATION ENTRY; the Open button does. Measured on
# Element, and the chooser here is the same GTK dialog at the same geometry.
#
# The Upload click is the step that actually sends.
CLICK 1277 872; sleep 8                      # paperclip
K ctrl+l; sleep 2                            # location bar
T '/tmp/parrot.png'; sleep 2
CLICK 1075 821; sleep 6                      # Open - NOT Return
CLICK 876 648                                # Upload - the step that matters
CP "Upload image" 14

# --- 18. Echo round trip -----------------------------------------------------
ROOM 'Parrot Echo' 14
CLICK 900 872; sleep 2
T 'ping'; sleep 1
K Return
CP "Echo round trip" 12

# --- 19. Join room -----------------------------------------------------------
# The spotlight offers "Join #parrot-lobby:parrot.test" as the preselected first
# result, so Return joins. No dialog.
K ctrl+k; sleep 2
T '#parrot-lobby:parrot.test'; sleep 5
K Return
CP "Join room" 18

# --- 20. Create room ---------------------------------------------------------
# DEFAULTS TO PRIVATE AND ENCRYPTED, exactly as Element does. Left alone this
# produces an invite-only E2EE room - not what script.md asks for, and not what
# the other clients produce, which would make every later block a comparison of
# different work.
#
# Switching to Public removes the encryption toggle entirely and makes a Room
# address mandatory.
CLICK 390 131; sleep 3                       # + next to All rooms
CLICK 450 216; sleep 6                       # New room
T 'Parrot benchmark'; sleep 2
CLICK 719 419; sleep 4                       # visibility dropdown
CLICK 574 487; sleep 5                       # Public room
CLICK 595 528; sleep 2                       # Room address
T 'parrot-benchmark'; sleep 2
CLICK 866 646; sleep 16                      # Create room

# The invite, in TWO steps - Element needs three because its second Invite is a
# confirmation. Verified with matrix-truth rather than by the dialog closing.
CLICK 929 720; sleep 6                       # Invite to this room
T '@alice:parrot.test'; sleep 6
CLICK 471 400; sleep 3                       # the suggestion row
CLICK 1028 269                               # Invite
CP "Create room" 12

# --- 21. Leave room ----------------------------------------------------------
# One click in the room-name menu, unlike Element's below-the-fold panel.
ROOM 'Parrot Lobby' 14
CLICK 605 28; sleep 5                        # room-name chevron
CLICK 649 458; sleep 5                       # Leave
CLICK 993 525                                # confirm Leave
CP "Leave room" 12

# --- 22. Idle quiet ----------------------------------------------------------
ROOM 'Parrot Firehose' 20
sleep 60
CP "Idle quiet" 4

# --- 23. Idle receiving ------------------------------------------------------
# `drip` is the trigger: the bot posts drip 01..24, one every 5 s, scheduled
# against a fixed start so the burst does not drift.
CLICK 900 872; sleep 2
T 'drip'; sleep 1
K Return
sleep 130
CP "Idle receiving" 6

echo "=== driven ==="
