#!/usr/bin/env bash
# Drive nheko through applications/chatclients/script.md while record-macro.py
# records the input. One block per script line, each ending in a checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowraise`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THREE RULES THIS FILE IS BUILT AROUND, all measured:
#
#   1. Never click a room in the room list. nheko sorts by unread state, so
#      reading a room reorders the list underneath you and the same coordinate
#      opens a different room the second time. Ctrl+K instead - it takes a name.
#
#   2. Never use the hover action bar. Its reply icon is at (1401,810), the
#      SAME point as the jump-to-live button, so one coordinate does two
#      different things depending on scroll state. Right-click gives a labelled
#      menu whose items have keyboard mnemonics, which need no coordinate.
#
#   3. Never checkpoint with a second window mapped. See CP() below.
set -euo pipefail

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
RCLICK() { X mousemove "$1" "$2"; sleep 0.4; X click 3; }

# Open a room by name. Immune to the room list reordering as rooms are read,
# and it is the only way to reach Parrot Echo and Parrot Firehose at all: they
# hold nothing unread, so they sort below all sixty filler rooms.
ROOM() { K ctrl+k; sleep 2; T "$1"; sleep 2; K Return; sleep "${2:-12}"; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - measured on the member-list button, which shows "Show room
# members." - that would be baked into the reference screenshot.
#
# 800,300 is upper timeline: it is over message text in every room the run
# visits, and raises no tooltip and no hover action bar at that height.
park() { X mousemove 800 300; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# THE ASSERTION IS `exactly one window`, AND IT IS THE LOAD-BEARING ONE.
#
# The recorder captures `xdotool search --onlyvisible --class nheko | head -n1`
# and then RAISES and FOCUSES that window before importing it. Every one of
# nheko's extra windows - the image viewer, the file dialog, the member list,
# the context menus - shares WM_CLASS "nheko","nheko", and the image viewer and
# the file dialog are ALSO 1440x900 with the title "nheko", so neither geometry
# nor name separates them from the main window. Measured: which one `head -n1`
# returns is not even stable, it flips with stacking order.
#
# Worse than photographing the wrong window: the raise puts the main window on
# top of the viewer, and the Escape meant to close the viewer then goes to the
# main window instead - so the viewer stays mapped, invisible, for the rest of
# the run. Measured, and it is unrecoverable without a non-input event.
#
# So the rule is simply that no checkpoint is taken while a second window
# exists. script.md already ends both such blocks by closing the thing they
# opened, so this costs nothing.
CP() {
    sleep "${2:-4}"
    park
    n="$(Q "xdotool search --onlyvisible --class nheko | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class nheko | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1 - a dialog or the image viewer is still open"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving nheko ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `nheko` through the startcommand - the
# wrapper from install.sh, which supplies a session bus and an unlocked keyring
# - and waited for the window. nheko settles on its welcome screen: logo,
# REGISTER, LOGIN. No first-run modal, nothing to dismiss.
sleep 25
CP "Load app" 5

# --- 2. Sign in --------------------------------------------------------------
# There is no seeded session; an access token is server state and GMT rebuilds
# the homeserver for every run. See usage_scenario.yml.
#
# THE FORM RE-LAYOUTS WHILE YOU FILL IT. Entering the Matrix ID makes nheko try
# .well-known autodiscovery on parrot.test; it fails, prints a two-line error
# and INSERTS a Homeserver field. Everything below the Matrix ID moves, so
# typing the password straight after the id puts it in Device name instead -
# measured, by doing it.
#
# Filling the homeserver clears the error, which springs the form back up:
# LOGIN is at y=676 while the error shows and y=656 once it is gone. So the
# order below is id, homeserver, password - not the order the fields appear in.
CLICK 801 582; sleep 3                       # welcome LOGIN
CLICK 720 424; sleep 1                       # Matrix ID
T '@parrot:parrot.test'
sleep 6                                      # let autodiscovery fail and re-lay out
CLICK 720 546; sleep 1                       # Homeserver address
K ctrl+a; T 'http://matrix.parrot.test:8008'; sleep 2
CLICK 720 445; sleep 1                       # Password
T 'parrot'; sleep 1
CLICK 720 656                                # LOGIN
CP "Sign in" 12

# --- 3. Initial sync ---------------------------------------------------------
# The measurement this block exists for. 8000 messages, 60-odd rooms and a
# 509-member room arriving at once; the room list is populated well within 20 s
# but the block is timed, not paced, so it gets room to finish.
#
# Two prompts, both refused. The Setup Encryption wizard would start real
# cross-signing key generation that belongs in no block, and the corpus is
# unencrypted anyway. The yellow "Encryption not set up" banner is dismissed
# because otherwise it is baked into all 21 remaining reference images.
sleep 30
CLICK 1373 861; sleep 3                      # Setup Encryption -> Cancel
CLICK 208 65                                 # dismiss the banner
CP "Initial sync" 20

# --- 4. Open busy room -------------------------------------------------------
# Aurora Release: 8000 messages, unread badge 7999.
ROOM 'Aurora Release' 18
CP "Open busy room" 8

# --- 5. Scroll back ----------------------------------------------------------
# PageUp with the pointer over the timeline. Confirmed to move - each press
# produced a different capture - and older batches load as it goes.
X mousemove 800 450; sleep 1
for _ in $(seq 1 10); do K Prior; sleep 2; done
CP "Scroll back" 8

# --- 6. Jump to live ---------------------------------------------------------
# The circular down-arrow. `End` does NOT do this - tried, the timeline stayed
# where it was. The button only exists while scrolled back, which is why this
# coordinate must never be used for anything else.
CLICK 1401 810
CP "Jump to live" 10

# --- 7. Open member list -----------------------------------------------------
# Opens a SEPARATE window, "Members of Aurora Release", reporting 509 people.
# It is closed again before the checkpoint - see CP().
CLICK 1343 28; sleep 10
K Escape
CP "Open member list" 5

# --- 8. Open photo room ------------------------------------------------------
# 400 images. They render only because the homeserver has
# enable_authenticated_media false; with Synapse's default this room is a grid
# of broken-image icons and this block plus the next two measure nothing. See
# MEASUREMENTS.md.
ROOM 'Field Photos' 15
CP "Open photo room" 8

# --- 9. View image full size -------------------------------------------------
# The newest image, reservoir-at-first-light.jpg. Its viewer is a second
# 1440x900 window also titled "nheko", so it is closed with Escape - while it
# still has focus - before the checkpoint. script.md ends this block by closing
# the viewer anyway.
CLICK 523 685; sleep 8
K Escape
CP "View image full size" 5

# --- 10. Scroll thumbnails ---------------------------------------------------
X mousemove 800 450; sleep 1
for _ in $(seq 1 5); do K Prior; sleep 3; done
CP "Scroll thumbnails" 8

# --- 11. Filter room list ----------------------------------------------------
# Ctrl+K is nheko's room filter. Exactly one joined room matches `windvane`,
# which smoke_test.py asserts.
K ctrl+k; sleep 2
T 'windvane'
CP "Filter room list" 5

# --- 12. Open filtered room --------------------------------------------------
# Return opens the preselected exact match, and closing the switcher is what
# clears the filter.
K Return; sleep 12
CP "Open filtered room" 6

# --- 13. Send message --------------------------------------------------------
# From here on every reference image contains the wall-clock date - nheko
# inserts a "Saturday, 8 August" day separator and a live timestamp for
# anything the scenario sends. The seeded corpus is frozen in the past to avoid
# exactly this; messages the run sends itself cannot be. Expect a small
# permanent RMSE floor on the rest of the checkpoints.
CLICK 700 880; sleep 1
T 'Thank you so much'; sleep 1
K Return
CP "Send message" 6

# --- 14. Reply to message ----------------------------------------------------
# The anchor is Nadia Oyelaran's "Ship it when the smoke tests are green.",
# which the send above pushed up to y=747.
#
# Right-click, then the menu's MNEMONIC - `y` for Reply. The mnemonic needs no
# coordinate at all, which matters because the menu is anchored to the click
# (its bottom edge lands on it) so every item's position moves with the
# message. Verified: the reply composer quotes the right message.
RCLICK 410 747; sleep 3
K y; sleep 3
T 'Agreed, going out today'; sleep 1
K Return
CP "Reply to message" 6

# --- 15. React to message ----------------------------------------------------
# The same anchor, now at y=689 - the reply pushed it up again.
#
# TARGET THE ORIGINAL, NOT THE QUOTE. The reply just sent contains a quoted
# copy of the identical text at y=807. Reacting to that would attach the
# reaction to the reply event, and ground truth cannot tell the difference
# without reading the target event id - which is why matrix-truth.py prints it.
#
# `a` is React. The emoji picker opens anchored to the message with its search
# field already focused; Return does NOT pick the first hit - measured, it
# produced no reaction at all - so the plain yellow thumbs-up is clicked.
RCLICK 410 689; sleep 3
K a; sleep 4
T 'thumbs up'; sleep 3
CLICK 440 664
CP "React to message" 6

# --- 16. Edit message --------------------------------------------------------
# Own messages get an 11-item menu - it inserts Edit and Remove message - so the
# offsets from the 9-item menu above do not apply. `e` is Edit; the mnemonic
# sidesteps the difference entirely.
RCLICK 345 767; sleep 3
K e; sleep 3
K ctrl+a; sleep 1
T 'Thank you so much indeed'; sleep 1
K Return
CP "Edit message" 6

# --- 17. Upload image --------------------------------------------------------
# NHEKO DOES NOT SEND ON FILE SELECTION. It shows an inline preview with
# "Upload file" / "Cancel", and without that second click the dialog closes,
# the timeline looks busy and the server receives nothing. Invisible on screen;
# caught only by ground truth.
#
# The file dialog is 1440x900 at 0,0 - the same geometry as the main window -
# so it is closed before the checkpoint like every other extra window.
CLICK 279 880; sleep 5                       # paperclip
T '/tmp/parrot.png'; sleep 2                 # File name is already focused
K Return; sleep 5
CLICK 1307 841                               # Upload file
CP "Upload image" 12

# --- 18. Echo round trip -----------------------------------------------------
# The bot answers `ping` with `pong`, measured inside 6 s. It only answers
# messages that arrive after it started, so nothing in the seeded history can
# trigger it.
ROOM 'Parrot Echo' 12
CLICK 700 880; sleep 1
T 'ping'; sleep 1
K Return
CP "Echo round trip" 10

# --- 19. Join room -----------------------------------------------------------
# THE JOIN DIALOG DOES NOT FOCUS ITS OWN FIELD. The window has keyboard focus
# but no widget does, and typing is silently discarded - six seconds of waiting
# does not help. Tab lands on Cancel; shift+Tab from there lands in the field.
CLICK 66 880; sleep 1                        # + menu
CLICK 110 815; sleep 4                       # Join a room
K Tab; sleep 1
K shift+Tab; sleep 1
T '#parrot-lobby:parrot.test'; sleep 1
K Return
CP "Join room" 12

# --- 20. Create room ---------------------------------------------------------
# Driven entirely by keyboard, because nheko's dialogs are placed by fluxbox's
# CascadePlacement: each one opens 23 px down and right of the last and the
# counter never resets, so a coordinate measured in one session is wrong in the
# next. Keystrokes are input events, so xmacrorec2 records them.
#
# New Room: the name field HAS focus on open. Tab x3 reaches Public, Tab x3
# more reaches Create Room.
CLICK 66 880; sleep 1
CLICK 110 839; sleep 4                       # Create a new room
T 'Parrot benchmark'; sleep 1
K Tab; sleep 1; K Tab; sleep 1; K Tab; sleep 1
K space; sleep 2                             # Public
K Tab; sleep 1; K Tab; sleep 1; K Tab; sleep 1
K space; sleep 8                             # Create Room

# The invite. Typing the mxid and pressing Invite sends NOTHING - the dialog
# closes and looks successful and the room's member events show only @parrot.
# The result row has to be moved into the selected pane first, and Return does
# it. A second Return does not press Invite; only Tab Tab space does.
CLICK 1415 28; sleep 2                       # room ⋮
CLICK 1367 55; sleep 4                       # Invite users (4-item menu here)
T '@alice:parrot.test'; sleep 4
K Return; sleep 2                            # move the hit into the selected pane
K Tab; sleep 1; K Tab; sleep 1
K space
CP "Create room" 10

# --- 21. Leave room ----------------------------------------------------------
# THE ⋮ MENU CHANGES SHAPE PER ROOM. parrot created Parrot benchmark, so there
# it has four items with Invite users first. In Parrot Lobby it is an ordinary
# member, Invite users is absent, and everything moves up 25 px - so Leave room
# is at y=80 here and y=105 there. Clicking 105 in the lobby opens Settings,
# with no error anywhere.
ROOM 'Parrot Lobby' 12
CLICK 1415 28; sleep 2
CLICK 1367 80; sleep 3                       # Leave room (3-item menu)
K Return                                     # confirm "Are you sure you want to leave?"
CP "Leave room" 10

# --- 22. Idle quiet ----------------------------------------------------------
# Nothing arrives and nothing is touched. The baseline the next block is read
# against.
ROOM 'Parrot Firehose' 15
sleep 60
CP "Idle quiet" 4

# --- 23. Idle receiving ------------------------------------------------------
# `drip` is the trigger: the bot posts drip 01..24, one every 5 s, scheduled
# against a fixed start so the burst does not drift. 24 x 5 s = 120 s, plus
# room for the last one to render.
CLICK 700 880; sleep 1
T 'drip'; sleep 1
K Return
sleep 130
CP "Idle receiving" 6

echo "=== driven ==="
