#!/usr/bin/env bash
# Drive GNU nano through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# nano lives in a terminal, so "the application" is a full-screen xterm with a
# bash prompt in /root/project, and block 1 is typing `nano` at that prompt.
#
# This is the most different driver in the group.  nano has no project-wide
# replace, no modal command line and no linewise registers, so several steps
# that are one keystroke elsewhere are three or four here - which is the point
# of having it in the comparison.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=xterm
WIN_W=1440
WIN_H=900
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 40 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# nano's Meta shortcuts, sent as an ESC prefix rather than as Alt+key.
#
# This is not a stylistic choice.  xterm's metaSendsEscape is off by default, so
# `xdotool key alt+f` does NOT reach nano as M-F - it arrives as a bare `f` with
# a stray space, and the first attempt at opening a file failed with
#   [ File " src/price_calculator.py" not found ]
# because the toggle never fired and the space landed in the filename.  ESC then
# the key is what a terminal actually carries.
M() { K Escape; sleep 0.2; K "$1"; }

park() { X mousemove 1200 850; sleep 1; }

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=${WIN_W}"*"HEIGHT=${WIN_H}"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

# Open a file into a buffer of its own: ^R, then M-F to switch the prompt from
# "File to insert" to "File to read into new buffer", then the path.  Without
# the toggle nano would splice the file into the current buffer, which would
# leave it unnamed and make ^O prompt for a filename later.
open_file() {
    K ctrl+r; sleep 1
    M f; sleep 1
    T "$1"; K Return
}

echo "=== driving GNU nano ==="

# --- 1. Load app -------------------------------------------------------------
sleep 8
X mousemove 700 400 click 1
sleep 2
T 'nano'
K Return
CP "Load app" 6

# --- 2. Open file ------------------------------------------------------------
open_file 'src/price_calculator.py'
CP "Open file" 4

# --- 3. Scroll to function ---------------------------------------------------
# ^V is a screen forward.  Two of them put the top of the window at ~line 83;
# nano shows 43 text lines between the title bar and the two-line help bar, so
# `def calculate_total` at 110 is on screen.
K ctrl+v; sleep 1
K ctrl+v
CP "Scroll to function" 3

# --- 4. Find identifier ------------------------------------------------------
K ctrl+w; sleep 1
T 'tax_rate'; K Return
CP "Find identifier" 3

# --- 5. Select line ----------------------------------------------------------
# M-W repeats the search, landing on the `tax_rate` in `tax = subtotal *
# tax_rate`.  nano has no linewise selection, so the line is selected by hand:
# Home, set the mark with ^6, then End.  Home goes to column 0 rather than to
# the first non-blank, so the selection includes the four spaces of indent -
# which is what makes the paste in the next block land correctly indented in an
# editor with no autoindent.
M w; sleep 1
K Home; sleep 1
K ctrl+6; sleep 1
K End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
# M-6 copies the marked region and drops the mark.  nano has no autoindent, so
# the new line starts at column 0 and the pasted text supplies its own indent.
M 6; sleep 1
K End; sleep 1
K Return; sleep 1
K ctrl+u
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice: the Return and the paste are separate undo steps, as in VS Code.
M u; sleep 1
M u
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# ^\ asks for the search text, then the replacement, then per occurrence - and
# `a` answers "All" to the first prompt.  It reports "Replaced 4 occurrences".
K ctrl+Home; sleep 1
K ctrl+backslash; sleep 1
T 'tax_rate'; K Return; sleep 1
T 'vat_rate'; K Return; sleep 2
K a
CP "Replace all" 4

# --- 9. Undo replace ---------------------------------------------------------
# FOUR undos, one per occurrence.  This is the sharpest difference in the whole
# comparison: every other editor here treats a replace-all as a single undoable
# operation, and nano treats it as four.  Measured, not guessed - after one M-U
# the status line says "Undid replacement" and a search still finds `vat_rate`;
# only after the fourth does it report "not found".
M u; sleep 1
M u; sleep 1
M u; sleep 1
M u
CP "Undo replace" 4

# --- 10. Insert comment ------------------------------------------------------
# Typing at column 0 of the return line pushes it right, and the Return then
# splits the two apart - so the comment ends up on its own line above, at four
# columns because the four spaces were typed explicitly.  nano has no
# "open line above" command and no autoindent to inherit.
K ctrl+w; sleep 1
T 'return subtotal + tax'; K Return; sleep 2
K Home; sleep 1
T '    # benchmark complete'; sleep 1
K Return
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
# ^O prompts with the current filename; Return accepts it.
K ctrl+o; sleep 2
K Return
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
# ^X closes the buffer.  There are two open by now - the empty one nano started
# with and this file - so it closes this one and falls back to the empty one
# rather than exiting.  The buffer was just written, so there is no
# "Save modified buffer?" prompt to answer.
K ctrl+x; sleep 2
open_file 'src/price_calculator.py'
CP "Reopen file" 4

# --- 13. Open large file -----------------------------------------------------
open_file 'src/component_library.py'
CP "Open large file" 22

# --- 14. Go to line ----------------------------------------------------------
# ^/ is Go To Line; the prompt asks for "line number, column number".
K ctrl+slash; sleep 2
T '120000'; K Return
CP "Go to line" 10

# --- 15. Page down -----------------------------------------------------------
for _ in $(seq 1 10); do K ctrl+v; sleep 0.4; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
K ctrl+Home
CP "Go to start" 8

# --- 17. Type block ----------------------------------------------------------
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.25
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# nano has no project-wide replace at all, so this is the file-by-file path the
# script allows for: open, replace within, save, three times over.  Twenty-one
# keystrokes and three prompts where Vim spends one :argdo and VS Code spends a
# dialog - which is exactly the sort of difference this benchmark exists to put
# a number on.
for f in orders pricing shipping; do
    open_file "src/legacy/${f}.py"; sleep 3
    K ctrl+backslash; sleep 1
    T 'LEGACY_SKU'; K Return; sleep 1
    T 'ARCHIVE_SKU'; K Return; sleep 2
    K a; sleep 2
    K ctrl+o; sleep 2
    K Return; sleep 2
done
CP "Global replace" 6

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
