#!/usr/bin/env bash
# Drive VS Code through applications/codeeditors/script.md while record-macro.py
# records the input.  One block per script line, each ending in a checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - which is watching the same X display from inside - records real
# input events.  Anything done with `xdotool windowactivate`, `windowfocus` or
# `windowsize` would NOT be recorded and would silently not happen on replay;
# there is none of that here, and the window is pinned by the window manager
# instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md.  Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=code
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

# Type a literal string.  --delay 45 is not decoration: at the default 12 ms VS
# Code's renderer drops characters out of the quick-open box often enough to
# make the file it opens a lottery.
T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Park the pointer somewhere inert before every capture.  xdotool leaves it
# wherever it last clicked, and a pointer resting on a tab, a tree row or the
# minimap changes what is drawn there.
#
# 200,600 is blank space in the explorer, below the last entry.  Not the editor
# text area, which was the obvious choice and the wrong one: VS Code runs on its
# defaults here, so `editor.hover` is on, and a pointer left over code for a few
# hundred milliseconds raises a hover card - which is exactly the kind of thing
# that ends up baked into a reference screenshot and then fails to reappear on
# replay.
park() { X mousemove 200 600; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion is the point.  record-macro.py captures
# `xdotool search --onlyvisible --class <class> | head -n1` - the FIRST match,
# not the largest - and VS Code's dialogs share the editor's WM_CLASS.  A
# checkpoint taken with one on screen is a 525x81 photograph of a modal, and it
# becomes the reference image that every future replay is measured against.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving VS Code ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `vscode /root/project` via the
# startcommand and waited for the window.  What it cannot wait for is the
# workbench finishing its first paint - or the three-page onboarding VS Code
# puts in front of it on a fresh profile, which is what these clicks are.
#
# VS Code is not configured here at all: it runs on its own defaults, so the
# sign-in modal, the theme picker and the agents page all appear, and getting
# past them is part of what loading this editor costs.  All three are drawn
# INSIDE the editor window rather than as X windows, so their coordinates
# follow the pinned 1440x900 geometry and are stable.
sleep 22
X mousemove 1064 700 click 1   # "Continue without Signing In"
sleep 4
X mousemove 1125 700 click 1   # theme picker -> "Continue" (Dark 2026 preselected)
sleep 4
X mousemove 1117 700 click 1   # "Build with AI Agents" -> "Get Started"
CP "Load app" 8

# --- 2. Open file ------------------------------------------------------------
# The click is the only one whose purpose is focus: fluxbox focuses the window
# but the workbench does not always have keyboard focus inside it until
# something in the editor area is clicked.  `xdotool windowfocus` would not be
# recorded, so this has to be a real click.
X mousemove 740 450 click 1
sleep 1
K ctrl+p; sleep 1
# The full relative path, not just the file name: `price_calculator.py` also
# fuzzy-matches tests/test_price_calculator.py, and which of the two ranks first
# is not something to bet a recording on.
T 'src/price_calculator.py'; sleep 2
K Return
CP "Open file" 4

# --- 3. Scroll to function ---------------------------------------------------
# Wheel, not PageDown, and deliberately: the wheel moves the viewport without
# moving the cursor, which leaves the cursor at line 1 so that the find in the
# next block lands on the first `tax_rate` in the file rather than on one below
# wherever paging happened to stop.  35 clicks at ~2.7 lines each.
X mousemove 740 450
for _ in $(seq 1 35); do X click 5; done
CP "Scroll to function" 3

# --- 4. Find identifier ------------------------------------------------------
K ctrl+f; sleep 1
T 'tax_rate'
CP "Find identifier" 3

# --- 5. Select line ----------------------------------------------------------
# Return advances to match 2 of 4, which is the `tax_rate` in
# `tax = subtotal * tax_rate`.  Escape closes the find widget and hands focus
# back to the editor with the match still selected; Home goes to the first
# non-whitespace character, so Shift+End selects the statement without its
# indent - which is what "select the line" looks like on screen.
K Return; sleep 1
K Escape; sleep 1
K Home; sleep 1
K shift+End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
# End collapses the selection to the end of the line, Return opens a new one
# below - auto-indented to the same four spaces - and the paste fills it.
K ctrl+c; sleep 1
K End; sleep 1
K Return; sleep 1
K ctrl+v
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice.  The Return and the paste are separate undo stops, so one Ctrl+Z leaves
# an empty, indented line 118 behind - which looks close enough to correct in a
# screenshot to pass, and is caught only by the ground-truth line count.
K ctrl+z; sleep 1
K ctrl+z
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+H opens the widget with the previous term pre-filled AND selected, so
# typing overwrites it.  The term is typed in full anyway rather than relying on
# that.
K ctrl+h; sleep 2
T 'tax_rate'; sleep 1
K Tab; sleep 1
T 'vat_rate'; sleep 1
K ctrl+alt+Return; sleep 2
K Escape
CP "Replace all" 3

# --- 9. Undo replace ---------------------------------------------------------
# Once - replace-all is a single undo stop, unlike block 6.
K ctrl+z
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# `return subtotal + tax` is unique in the file, so this lands on line 118 from
# wherever the cursor happens to be after the undo.  Ctrl+Shift+Return opens a
# line ABOVE the current one and indents it to match.
K ctrl+f; sleep 1
T 'return subtotal + tax'; sleep 2
K Escape; sleep 1
K ctrl+shift+Return; sleep 1
T '# benchmark complete'
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
K ctrl+s
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
K ctrl+w; sleep 2
K ctrl+p; sleep 1
T 'src/price_calculator.py'; sleep 2
K Return
CP "Reopen file" 4

# --- 13. Open large file -----------------------------------------------------
K ctrl+p; sleep 1
T 'src/component_library.py'; sleep 2
K Return
CP "Open large file" 22

# --- 14. Go to line ----------------------------------------------------------
K ctrl+g; sleep 1
T '120000'; sleep 1
K Return
CP "Go to line" 9

# --- 15. Page down -----------------------------------------------------------
for _ in $(seq 1 10); do K Next; sleep 0.5; done
CP "Page down" 7

# --- 16. Go to start ---------------------------------------------------------
K ctrl+Home
CP "Go to start" 7

# --- 17. Type block ----------------------------------------------------------
# One keystroke at a time, as the script says, rather than pasting - the point
# of the block is to measure what an editor costs while a person types into a
# 10 MB buffer.
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.3
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# LEGACY_SKU exists nowhere in the workspace except the three files under
# src/legacy/, so an unscoped project search has exactly the scope the script
# asks for - 12 results in 3 files - without a "files to include" glob that no
# two of these twelve editors spell the same way.
#
# The click is the confirmation dialog's Replace button.  Return does not work:
# the modal never takes the input focus, so the keystroke goes to the editor
# behind it.  See MEASUREMENTS.md for what makes 395,87 reproducible and what
# would break it.
K ctrl+shift+h; sleep 3
T 'LEGACY_SKU'; sleep 4
K Tab; sleep 1
T 'ARCHIVE_SKU'; sleep 3
K ctrl+alt+Return; sleep 3
X mousemove 395 87 click 1
CP "Global replace" 6

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
