#!/usr/bin/env bash
# Drive one video player through applications/videoplayers/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
#   common/drive-scenario.sh <app>
#
# ONE DRIVER FOR ALL SEVEN, but not for the terminal group's reason. There, every
# entrant took literally the same keystrokes. Here the twenty-two blocks are the
# same USER ACTIONS in the same order while the way to perform them differs in
# every entrant - a menu in one, a keybinding in another, a widget in a third.
# So the block sequence lives here once, and each app's driver.conf supplies the
# handful of shell functions that differ. An entrant cannot quietly do the blocks
# in another order, and a block cannot quietly go missing from one recording.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see each usage_scenario.yml).
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
APP="${1:?usage: drive-scenario.sh <app>}"
GROUP="${REPO}/applications/videoplayers"
CONF="${GROUP}/${APP}/driver.conf"
[[ -f "$CONF" ]] || { echo "no driver.conf for ${APP} at ${CONF}" >&2; exit 1; }

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }
K() { X key --clearmodifiers "$@"; }
CLICK() { X mousemove "$1" "$2"; sleep "${3:-0.6}"; X click 1; sleep "${4:-1.2}"; }

# shellcheck source=/dev/null
source "$CONF"
: "${CLASS:?driver.conf must set CLASS}"
: "${WANT_W:?driver.conf must set WANT_W}"
: "${WANT_H:?driver.conf must set WANT_H}"
: "${BAR_X0:?driver.conf must set BAR_X0}"
: "${BAR_X1:?driver.conf must set BAR_X1}"
: "${BAR_Y:?driver.conf must set BAR_Y}"
LOAD_WAIT="${LOAD_WAIT:-12}"

# How long the five clip-change blocks play for. Ten seconds in every entrant,
# which is what makes blocks 15 to 19 the same work in all of them.
#
# Kaffeine used to override this to 4, on a measurement that said it played the
# 60 fps clip at 1.5x or so. Re-measured from a clean launch it plays at 0.96x -
# real time, like everything else - and the override is gone. The hook is kept
# because an entrant that genuinely does not run at real time would have to
# declare it here rather than hide it in a sleep, but nothing uses it today.
PLAY_NEXT="${PLAY_NEXT:-10}"

# Block 1 has to put the position back to the start of clip 01, because the
# recorder's own startup is playback time. Most entrants do it with a click at
# the left end of the position bar, which is what this default does. An entrant
# whose chrome makes that unreliable overrides it in driver.conf - Totem does,
# because its control bar auto-hides and the first click after a menu is eaten by
# the popover's grab, so a bar click there failed in four consecutive recordings
# while a single keystroke never does.
declare -F do_seek_start >/dev/null || do_seek_start() { bar 0.0; }

# Pause and resume FOR THE FULLSCREEN BLOCK ONLY, because full screen is where an
# entrant driven by a mouse click stops having anything to click. Kaffeine pauses
# from a transport button on its control bar, and in full screen that bar is not
# drawn until the pointer is moved to the bottom of the screen - measured: the
# pixels under 60,880 are video there, so block 13 clicked the picture, the clip
# never paused, and the twelve rewind presses and the checkpoint all landed on a
# player that was still running. Its playlist had run out by block 19, where the
# reference reads "Stopped".
#
# Both default to the ordinary pair, so an entrant that pauses from the keyboard
# needs nothing here.
declare -F do_pause_fs  >/dev/null || do_pause_fs()  { do_pause; }
declare -F do_resume_fs >/dev/null || do_resume_fs() { do_resume; }

# A hook around the ONE playlist change the driver does not make itself: block 21
# lets a clip run off its end so the player advances on its own. Everything else
# advances through do_next/do_prev, which an entrant can wrap in its own
# driver.conf - but this one happens inside a sleep, so the hook has to be here.
#
# Totem is why it exists. Advancing its playlist while the subtitle track is
# DISABLED kills its video output permanently, and block 21's advance is no
# different. Both default to nothing, so an entrant without the defect pays
# nothing for it.
declare -F autoadvance_guard_on  >/dev/null || autoadvance_guard_on()  { :; }
declare -F autoadvance_guard_off >/dev/null || autoadvance_guard_off() { :; }

# How many backward seek presses it takes to CLAMP at the start of a clip from
# anywhere in it, and how long to leave between them. The step is the entrant's
# own and is 5 s at the smallest, so twelve presses covers the 50 s of clip 01
# with margin. An entrant with a larger step overrides the count downwards -
# Totem does - because these are decoder flushes, not free keystrokes.
REWIND_PRESSES="${REWIND_PRESSES:-12}"
REWIND_DELAY="${REWIND_DELAY:-0.5}"

# An absolute seek that uses no coordinates at all: hold the entrant's own
# backward seek key until the position clamps at the start of the clip, then step
# forward $1 times. Where `bar` needs the position bar to be where it was
# measured, this needs only the two keys every entrant already binds - which is
# why block 13 uses it. Block 13 runs FULL SCREEN, and full screen is exactly
# where BAR_X0/BAR_X1/BAR_Y stop being true: every entrant with window chrome
# draws a different control bar over the whole width of the screen there, so a
# click at the windowed coordinates lands on the video instead.
#
# The clamp is what makes it absolute. Totem's do_seek_start has used the same
# trick since the first recording - see its driver.conf - and it is the only
# mechanism in the group that turns "wherever playback left us" into a fixed
# frame without knowing where that was.
seek_abs_keys() {
    local n="$1" i
    for ((i = 0; i < REWIND_PRESSES; i++)); do do_seek_back; sleep "$REWIND_DELAY"; done
    sleep 1.5
    for ((i = 0; i < n; i++)); do do_seek_fwd; sleep 1.0; done
    sleep 1.5
}

# Click the position bar at a fraction of its length. Measured per entrant by
# clicking at known x and reading the clip's own burnt-in timecode back off the
# frame - never by eyeballing the widget, because a seek bar's ends are inset
# from the widget's ends by an amount no screenshot shows.
bar() {
    local frac="$1"
    local x
    x=$(python3 -c "print(int(${BAR_X0} + (${BAR_X1} - ${BAR_X0}) * ${frac}))")
    bar_click "$x" "$BAR_Y"
}

# Park the pointer somewhere inert before every capture, and NOT over the
# window's chrome. Every entrant here hides its controls after a second or two of
# pointer stillness and shows them again the moment the pointer moves, so a
# capture taken with the pointer anywhere near the bottom of the window records
# whatever the fade happened to be doing. Parking high and waiting puts every
# entrant in the same state: controls faded, pointer off the video's subject.
park() { X mousemove "${PARK_X:-1430}" "${PARK_Y:-8}"; sleep 2; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion is not decoration. Several entrants map more than one window with
# their own WM_CLASS - VLC maps seven besides its main window, SMPlayer seven -
# and record-macro.py captures `xdotool search --onlyvisible --class <class> |
# head -n1` while check-image.sh takes the LARGEST match. If those two ever pick
# different windows the reference is a picture of the wrong thing, and the only
# warning you get is the geometry printed here.
# THE PROBE IS A WARNING AND MUST NEVER BE FATAL. It used to be a bare
# assignment, and under `set -euo pipefail` that is a trapdoor: when the probe's
# own grep matches nothing - because `xdotool search --onlyvisible` came back
# empty for a moment - the pipeline fails, the assignment fails, and the whole
# driver exits. Silently, because `set -e` prints nothing. Measured on Totem: the
# run died in block 1 leaving a .parrot with 20 events and zero checkpoints, and
# the only trace in 55 lines of log was that "=== driving totem ===" had no
# "=== totem driven ===" after it. A diagnostic that can abort the thing it is
# diagnosing is worse than no diagnostic.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')" || geo=""
    case "$geo" in
        "") echo "  WARNING: '$1' - no visible ${CLASS} window to measure" ;;
        *"WIDTH=${WANT_W}"*"HEIGHT=${WANT_H}"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo} (want ${WANT_W}x${WANT_H})" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving ${APP} ==="

# 1 --------------------------------------------------------------- Load app
# The launcher has already been started by record-macro.py; this block only
# waits for the first frame and settles the player. dismiss_startup is a no-op
# in every entrant that has no first-run dialog, which after seeding is all of
# them - it is kept as a hook so that an entrant which grows one later has an
# obvious place to handle it rather than a new block.
# The player has been running since record-macro.py launched it - the recorder
# needs time to arm xmacrorec2 before the first event, and that is time the clip
# spends playing. Measured on the first mpv recording: block 1 paused 22.9 s into
# a 30-second clip. So this block pauses and then puts the position back to the
# start with the entrant's own seek bar, which is what makes every recording in
# the group begin on the same frame instead of on however long the entrant took
# to start.
sleep "$LOAD_WAIT"
dismiss_startup
do_pause
do_seek_start
CP "01 Load app" 3

# 2 ------------------------------------------------------------- Play H.264
# The trailing seek is what makes this block reproducible, and it is not
# decoration. "Resume, play ten seconds, pause" ends on whatever frame the wall
# clock and the decoder's speed on the day leave it on, and that is not the same
# frame twice: four entrants failed their first replay on exactly this shape, at
# RMSE 0.25 to 0.31 against a 0.2 ceiling. Every block below that plays now ends
# on a mark instead, and each one ends on a DIFFERENT mark so that a block which
# silently did nothing cannot pass on its neighbour's frame.
do_resume
sleep 10
do_pause
bar 0.40
CP "02 Play H.264" 3

# 3 ------------------------------------------- Seek with the keyboard
# Alternating back/forward. The step is the entrant's own and is between 5 s and
# 15 s across the group, so jumps in one direction would run off an end of the
# clip and trip the playlist over into clip 02 - which would then desynchronise
# every block after this one. Alternating keeps the position within one step of
# block 2's mark whatever the step turns out to be.
for i in 1 2 3 4 5; do
    do_seek_back; sleep 1
    do_seek_fwd;  sleep 1
done
# The eleventh jump. Five matched pairs come back to where they started, and
# block 2 now ENDS on a seek - so without this the block would capture block 2's
# frame again and a replay in which all ten jumps went nowhere would pass.
do_seek_back; sleep 1
CP "03 Seek with the keyboard" 3

# 4 ------------------------------------------------------- Seek on the bar
# Descending, so the block LEAVES the position at a quarter of the clip. This is
# the block the rest were modelled on: three absolute clicks, and it is the only
# block that passed its replay in all seven entrants first time.
bar 0.75
bar 0.50
bar 0.25
CP "04 Seek on the bar" 3

# 5 ----------------------------------------------------------------- Resume
do_resume
sleep 6
do_pause
bar 0.70
CP "05 Resume" 3

# 6 --------------------------------------------------- Volume down and up
do_volume_down
sleep 1
do_volume_up
CP "06 Volume down and up" 3

# 7 ------------------------------------------------------------------- Mute
do_mute
sleep 2
do_unmute
CP "07 Mute" 3

# 8 --------------------------------------------------------- Subtitles on
# No subtitle track in the corpus is flagged default, so every entrant reaches
# this block with subtitles off and this is the block that turns them on. See
# make-corpus.sh.
do_subs_german
do_resume
sleep 6
do_pause
# 0.35 and not a round number: the corpus writes a subtitle cue every five
# seconds running from t+0.5 to t+4.5, so one second in five has no subtitle on
# screen at all. 0.35 of the 50 s clip is 17.5 s, the middle of the cue that runs
# 15.5 to 19.5 - two seconds clear of either edge, which is enough slack for the
# keyframe the seek actually lands on. If it were not, this block and block 9
# would capture the same frame and neither would prove anything.
bar 0.35
CP "08 Subtitles on" 3

# 9 -------------------------------------------------------- Subtitles off
do_subs_off
# A mark of its own, where block 8 has 0.35. Both blocks would otherwise capture
# the same frame differing only in whether a subtitle line is drawn over it - and
# in Parole not even that, because a seek taken while PAUSED does not redraw the
# subtitle overlay there, so its block 8 ends on an unsubtitled frame and the
# only difference left between the two references would be the word in its
# track bar. Two marks make the pair distinct in every entrant.
bar 0.15
CP "09 Subtitles off" 3

# 10 ------------------------------------------------- Second audio track
do_audio_german
do_resume
sleep 6
do_pause
bar 0.55
CP "10 Second audio track" 3

# 11 -------------------------------------------------- Aspect ratio 4:3
do_aspect_43
CP "11 Aspect ratio 4:3" 3

# 12 ------------------------------------------------- Aspect ratio back
do_aspect_source
CP "12 Aspect ratio back" 3

# 13 ------------------------------------------------------- Fullscreen
# The one block that cannot end on a bar click, because it ends full screen and
# the bar is not where it was measured there. seek_abs_keys clamps at the start
# with the entrant's own seek key and steps forward twice, so the frame is a
# property of the keys rather than of any coordinate.
do_fullscreen_on
do_resume_fs
sleep 10
do_pause_fs
seek_abs_keys 2
CP "13 Fullscreen" 3

# 14 -------------------------------------------------- Leave fullscreen
do_fullscreen_off
CP "14 Leave fullscreen" 4

# 15-19 -------------------------------------------- the five other clips
# do_next has to leave the new clip PLAYING or PAUSED consistently across
# entrants: some start the next item playing, some inherit the paused state. Each
# driver.conf's do_next ends with the clip playing, so the sleep below is the
# only thing that decides how much of it is decoded.
#
# A different mark for each of the five, chosen off the corpus rather than picked
# round. Two things decide them.
#
# NOT ON THE FADE. The film cuts to black about 3.5 to 5.5 s into these fifteen
# seconds, and the first version of this ended block 15 at 0.30 - 4.5 s - which
# captured a black screen with two lines of white text on it. Every player looks
# the same in the dark, so that check could only have failed on the text.
#
# ALTERNATING BETWEEN THE TWO SCENES. There are only two: the bunny and the tree
# trunk before the fade, the grass field after it. Consecutive marks are put in
# different ones so that consecutive references do not look alike - see the
# separation report in common/verify-app.sh.
#
# What the marks CANNOT do is catch a playlist that failed to advance. Every clip
# is the same seconds of film, and the closing seek puts the position on the mark
# whichever clip is playing - so the capture would differ from the reference only
# in the burnt-in clip name. That was equally true before these seeks existed
# (each block started its clip from zero and played the same ten seconds), and it
# is why the clip names in the references are read block by block after every
# recording. The image checks are not what proves the playlist moved.
play_next() {          # $1 = label, $2 = the mark to end on
    do_next
    sleep "$PLAY_NEXT"
    do_pause
    bar "$2"
    CP "$1" 3
}
play_next "15 Play 60 fps"       0.20
play_next "16 Play VP9"          0.60
play_next "17 Play HEVC"         0.15
play_next "18 Play AV1"          0.75
play_next "19 Play upscaled SD"  0.60

# 20 ------------------------------------------------------ Previous clip
do_prev
sleep 3
do_pause
# 0.20, where block 18 left the same clip at 0.75. Two blocks land on clip 05,
# and this is what keeps their two references apart.
bar 0.20
CP "20 Previous clip" 3

# 21 ------------------------------------------ Play to the end of a clip
# 0.90 of a 15-second clip is 13.5 s, so resuming there runs out the last second
# and a half and the playlist advances on its own. The ground truth for this
# block is the burnt-in clip name in the captured frame: it has to read
# 06-h264-640x400p30.
# Twelve seconds and not six. At six the block ended on clip 06's FIRST frame -
# measured, and reproducible: the last 1.5 s of clip 05 plays, then the entrant
# spends several seconds tearing down an AV1 decoder and bringing up an H.264 one
# at a different video size, and the six seconds are gone before clip 06 has
# shown anything. Twelve leaves the playlist unambiguously on the next clip
# before the closing seek is taken.
bar 0.90
autoadvance_guard_on
do_resume
sleep 12
do_pause
autoadvance_guard_off
# On clip 06 now, where block 19 left it at 0.60. This is also the one block
# whose checkpoint still proves that PLAYBACK happened rather than that a seek
# did: the only way to be on clip 06 here is to have played off the end of 05.
bar 0.85
CP "21 Play to the end of a clip" 3

# 22 -------------------------------------------------------- Idle paused
# Deliberately does nothing for thirty seconds. This is the floor measurement -
# what the entrant costs while displaying one still frame - and it is the block
# most likely to separate the front ends, so it must contain no input at all.
sleep 30
CP "22 Idle paused" 2

echo "=== ${APP} driven ==="
