#!/usr/bin/env bash
# Drive JupyterLab through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# JupyterLab is the only editor in this group without a window of its own: it is
# a server plus a web application, and what is driven is Firefox showing
# http://127.0.0.1:8888/lab.  Two consequences run through everything below.
#
#   Finding does not move the caret.  CodeMirror's search panel highlights and
#   scrolls, but the cursor stays where it was - so the "search, then Escape,
#   then Home/Shift+End" pattern every other editor here uses does not work.
#   Lines are reached by scrolling a known number of wheel clicks and clicking
#   the line, which is deterministic because pin-windows.sh fixes the geometry.
#
#   There is no "go to line" at all.  See block 14.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=firefox
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Blank space in the file browser, below the last entry.  Not the editor, where
# the pointer sitting still raises CodeMirror tooltips, and not the tab bar.
park() { X mousemove 200 600; sleep 1; }

# Sixteen wheel clicks from the top of price_calculator.py puts line 90 at the
# top of the editor.  Firefox scrolls 5.6 lines a click here, so this is the
# scroll that makes the line-clicks below land where they are meant to.
scroll_to_function() {
    X mousemove 800 500
    for _ in $(seq 1 16); do X click 5; sleep 0.05; done
    sleep 1
}

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "best=''; besta=-1
              for w in \$(xdotool search --onlyvisible --class ${CLASS} 2>/dev/null); do
                eval \$(xdotool getwindowgeometry --shell \$w 2>/dev/null | grep -E '^(WIDTH|HEIGHT)=')
                a=\$((WIDTH*HEIGHT))
                if [ \$a -gt \$besta ]; then besta=\$a; best=\$w; fi
              done
              xdotool getwindowgeometry --shell \$best | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving JupyterLab ==="

# --- 1. Load app -------------------------------------------------------------
# Two things to dismiss, and only one of them belongs to JupyterLab:
#
#   "Welcome to Firefox"   the browser's own first-run modal.  Every web
#                          application in a fresh profile gets this, and it is
#                          part of what opening JupyterLab costs.
#   "Would you like to get notified about official Jupyter news?"  -> No
#
# The server is already listening: jupyter-server-start ran as a setup-command
# and waited for the port, so this block never measures the server booting.
sleep 30
X mousemove 720 325 click 1     # Welcome to Firefox -> Continue
sleep 6
X mousemove 1397 844 click 1    # Jupyter news -> No
CP "Load app" 8

# --- 2. Open file ------------------------------------------------------------
# File > Open from Path..., not the file browser tree.  Both work; this one is
# typed rather than aimed, so it does not depend on where a row happens to be.
X mousemove 52 99 click 1       # File
sleep 2
X mousemove 119 184 click 1     # Open from Path...
sleep 3
T 'src/price_calculator.py'
sleep 2
K Return
CP "Open file" 8

# --- 3. Scroll to function ---------------------------------------------------
# The wheel, which does not move the caret - the same reason VS Code, Sublime
# and Eclipse use it.  Unlike Eclipse, CodeMirror scrolls freely past the last
# line, so 30 clicks would leave line 129 alone at the top of an empty screen;
# 16 is measured, not rounded.
scroll_to_function
CP "Scroll to function" 4

# --- 4. Find identifier ------------------------------------------------------
# Ctrl+F reaches JupyterLab rather than Firefox's own find bar - CodeMirror
# takes the key first.  The panel reads 1/4 and highlights all four matches.
#
# The caret does NOT move to the match.  That is why block 5 clicks.
K ctrl+f
sleep 2
K ctrl+a
sleep 1
T 'tax_rate'
CP "Find identifier" 4

# --- 5. Select line ----------------------------------------------------------
# Line 117 is the 28th row of a view whose top line is 90, which puts it at
# y=642.  Home is smart-home here - it stops at column 5, the first
# non-whitespace - so Shift+End selects `tax = subtotal * tax_rate` without its
# indent: the status bar reads Ln 117, Col 30.
X mousemove 600 642 click 1
sleep 2
K Home
sleep 1
K shift+End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
# Return auto-indents from the line above, so the pasted copy lands at column 5
# without the indent being part of what was copied.
K ctrl+c; sleep 1
K End; sleep 1
K Return; sleep 1
K ctrl+v
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice: one Ctrl+Z removes the pasted text and leaves the opened line behind.
K ctrl+z; sleep 1
K ctrl+z
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# The chevron at 1006,167 expands the replace row.  Its state is per-document,
# so it has to be expanded again for each of the three files in block 18 - it
# does not stay open the way Eclipse's does.
#
# Ctrl+A before each field: the find field keeps the term from block 4 within
# the same document.
K ctrl+f; sleep 2
X mousemove 1140 167 click 1; sleep 1     # find field
K ctrl+a; sleep 1
T 'tax_rate'; sleep 2
X mousemove 1006 167 click 1; sleep 2     # expand the replace row
X mousemove 1110 196 click 1; sleep 1     # replace field
K ctrl+a; sleep 1
T 'vat_rate'; sleep 2
X mousemove 1332 196 click 1              # Replace All
CP "Replace all" 4

# --- 9. Undo replace ---------------------------------------------------------
# Escape closes the panel and hands focus back to the editor, which is what
# makes the Ctrl+Z reach the document rather than the replace field.  Once:
# CodeMirror groups a Replace All into a single undo.
K Escape; sleep 2
K ctrl+z
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# Back to the top and down again by the same measured scroll, because after the
# undos neither the caret nor the viewport is anywhere predictable - and with no
# go-to-line there is nothing to aim with except the wheel.
#
# Line 118 is `return subtotal + tax`, one row below the line block 5 clicked.
# Home stops at column 5, so typing the comment there and pressing Return splits
# the line and auto-indents the tail back to column 5.
K ctrl+Home; sleep 2
scroll_to_function
X mousemove 600 660 click 1; sleep 2
K Home; sleep 1
T '# benchmark complete'; sleep 1
K Return
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
K ctrl+s
CP "Save file" 4

# --- 12. Reopen file ---------------------------------------------------------
# The tab's close button.  Alt+W is what the File menu offers for Close Tab, but
# Alt is Firefox's menu-bar accelerator and the browser gets it first.
X mousemove 704 131 click 1; sleep 3
X mousemove 52 99 click 1; sleep 2
X mousemove 119 184 click 1; sleep 3
T 'src/price_calculator.py'; sleep 2
K Return
CP "Reopen file" 8

# --- 13. Open large file -----------------------------------------------------
X mousemove 52 99 click 1; sleep 2
X mousemove 119 184 click 1; sleep 3
T 'src/component_library.py'; sleep 2
K Return
CP "Open large file" 45

# --- 14. Go to line ----------------------------------------------------------
# JUPYTERLAB HAS NO GO TO LINE.  Not a keybinding, not a menu item, not a
# command-palette entry: the bundle ships CodeMirror's gotoLine code but
# registers no command for it, and Alt+G - CodeMirror's own default - does
# nothing.  Searching the palette for "go to" returns no results.
#
# So this block reaches line 120000 the only way JupyterLab offers: a click on
# the scrollbar track, which GTK warps the thumb to, followed by a click on the
# line itself.  1398,413 is 35.5% down a 700 px track and puts line 119981 at
# the top of the view; the second click lands on the 20th row, which is line
# 120000 exactly.  The caret therefore ends up where every other editor's does,
# and blocks 15 and 16 are directly comparable.
#
# What is NOT comparable is this block's own number: it measures two mouse
# clicks, not a typed line number.  See MEASUREMENTS.md.
X mousemove 1398 500; sleep 1             # wake the overlay scrollbar
X mousemove 1398 413; sleep 1
X click 1; sleep 3
X mousemove 600 514 click 1
CP "Go to line" 10

# --- 15. Page down -----------------------------------------------------------
# 40 lines a screen: L120000 -> L120400.
for _ in $(seq 1 10); do K Next; sleep 0.4; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
K ctrl+Home
CP "Go to start" 8

# --- 17. Type block ----------------------------------------------------------
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.25
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# File by file, because JupyterLab has no project-wide replace of any kind - the
# search panel is per-document and there is no "search in files" view.  This is
# the alternative path the script explicitly allows, the same one nano, Emacs
# and Sublime take.
#
# Each file needs its own chevron click: the replace row's expanded state does
# not carry from one document to the next.
for f in orders pricing shipping; do
    X mousemove 52 99 click 1; sleep 2
    X mousemove 119 184 click 1; sleep 3
    T "src/legacy/${f}.py"; sleep 2
    K Return; sleep 6
    K ctrl+f; sleep 2
    X mousemove 1140 167 click 1; sleep 1
    K ctrl+a; sleep 1
    T 'LEGACY_SKU'; sleep 2
    X mousemove 1006 167 click 1; sleep 2
    X mousemove 1110 196 click 1; sleep 1
    K ctrl+a; sleep 1
    T 'ARCHIVE_SKU'; sleep 2
    X mousemove 1332 196 click 1; sleep 2
    K Escape; sleep 2
    K ctrl+s; sleep 3
done
CP "Global replace" 8

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
