#!/usr/bin/env bash
# Drive Calligra Words through applications/wordprocessors/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# FOUR SHORTCUTS THIS APPLICATION DOES NOT HAVE, each of which looks like it
# does and each of which was found by pressing it and reading the result:
#
#   Ctrl+R   is ALIGN RIGHT, not Replace. It silently right-aligns the
#            paragraph the cursor is in - on the title page that is almost
#            invisible. Replace is Ctrl+H.
#   Ctrl+Y   is nothing at all. Redo is Ctrl+Shift+Z, and Ctrl+Y leaves the
#            page count where the undo left it with no error anywhere.
#   Tab      inside a table inserts a TAB CHARACTER. It does not move to the
#            next cell. Use the Right arrow.
#   Escape   does not leave the shape tool after an image is inserted. A
#            double-click on body text does.
set -euo pipefail

# WM_CLASS is "calligrawords", "calligrawords" - both halves the same, so the
# obvious string works for both the fluxbox pin rule and xdotool, unlike
# Collabora. Confirmed against a live window before recording.
CLASS=calligrawords

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
CLICK2() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 2 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a docker button raises a
# tooltip - that is how every landmark below was identified, so it definitely
# happens. 1240,650 is the empty lower half of the docker: no control, no
# tooltip, and inert in every block.
park() { X mousemove 1240 650; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The COUNT assertion is the one that matters here. Calligra's menus and combo
# popups are separate X windows carrying the document's own WM_CLASS - the Edit
# menu is 293x268, the style combo 377x482 - and they sort AHEAD of the document
# in xdotool's output, which is what record-macro.py takes. Worse, the Insert
# Table dialog comes back at 1440x900 at 0,0 because the fluxbox pin rule
# matches it too, so it is indistinguishable from the document by geometry
# alone. Only the count catches that one.
CP() {
    sleep "${2:-3}"
    park
    n="$(Q "xdotool search --onlyvisible --class ${CLASS} | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Calligra Words ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched the app through the startcommand, but it
# only waits a second for the window; a Flatpak sandbox takes about 40 s to get
# one on screen.
#
# Calligra opens a TEMPLATE CHOOSER rather than a document, with `Blank
# Document` already selected. Clicking `Use This Template` turns the SAME window
# into the document view - it does not open a second one - so unlike Collabora
# this block can end on a genuine editable page, which is what script.md asks
# for.
sleep 60
CLICK 1371 883                   # Use This Template
CP "Load app" 20

# --- 2. Open document --------------------------------------------------------
# A Qt file dialog, 632x412 at 394,226. The portal is absent in this container
# and that is good news: the in-process fallback is deterministic where a
# portal's appearance depends on what is running outside the sandbox.
#
# The blank document is REUSED, so there is still exactly one window afterwards.
#
# Calligra paginates this document to 120 pages where LibreOffice and OpenOffice
# give 98, because its ODF import does not apply the document's fonts - see
# MEASUREMENTS.md. script.md counts keystrokes and never names a page, so the
# driver survives it.
K ctrl+o; sleep 8
CLICK 708 562; sleep 1
K ctrl+a
T '/tmp/parrot-report.odt'; sleep 2
K Return
CP "Open document" 90

# --- 3. Page through ---------------------------------------------------------
# Ends on "Page 5-6 of 120, Line 166". Calligra shows a page RANGE when two
# pages are partly on screen, which no other application in this group does.
for _ in $(seq 1 10); do K Next; sleep 1.2; done
CP "Page through" 10

# --- 4. Jump to end ----------------------------------------------------------
# "Page 120 of 120". Takes about 45 s.
K ctrl+End
CP "Jump to end" 60

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 40

# --- 6. Zoom -----------------------------------------------------------------
# THIS BLOCK IS A DELIBERATE DEVIATION FROM script.md, and the reasoning is in
# MEASUREMENTS.md. There is no 150 % in Calligra: its steps are a root-two
# progression - 25, 33.3, 50, 66.7, 100, 141.4, 176.6, 200 - and the status-bar
# zoom box is inert, accepting a typed value and leaving the canvas untouched.
#
# Ctrl++ / Ctrl+- are the only route that actually redraws. From the `Fit Page
# Width` the document opens at, one Ctrl++ lands on 141 % - the nearest step
# there is to 150 % - and one Ctrl+- lands on exactly 100 %, which is what the
# second half of the block asks for. So only the first half deviates.
K ctrl+plus;  sleep 10
K ctrl+minus
CP "Zoom" 10

# --- 7. Find word ------------------------------------------------------------
# Ctrl+F opens a find BAR along the bottom, below the status bar - which it
# pushes up, so the status bar is at y~829 while the bar is open and back at
# y~860 once it closes.
#
# It reports "120 matches found", which is exactly what the document contains
# and is free ground truth.
#
# TWO Next clicks, not three. THE BAR IS INCREMENTAL: typing `Cormorant`
# already selects match 1, so typing + 3 clicks lands on match FOUR, one past
# what script.md asks for. Every other application in the group needs three
# clicks because its find dialog does not move until told to.
#
# This is invisible to every automated check - 18 PASS, no warnings, ground
# truth PASS - because nothing asserts WHICH match the cursor is on. It was
# caught only by opening this checkpoint beside libreoffice-check-007.png and
# noticing a different sentence, then confirming against the document:
#
#   provisional conduit downstream of Cormorant   match 3   LO/AOO/AbiWord/Collabora
#   evaporator feeding Cormorant                  match 4   Calligra with 3 clicks
#
# Close it with its own X, not Escape - the group rule after Collabora.
K ctrl+f; sleep 8
CLICK 234 857; sleep 1
T 'Cormorant'; sleep 3           # incremental: this alone selects match 1
CLICK 445 857; sleep 6           # Next -> match 2
CLICK 445 857; sleep 6           # Next -> match 3
CLICK 20 857                     # close the bar
CP "Find word" 8

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+H, NOT Ctrl+R - see the header. It opens the same bar with a second row,
# which moves the close button and the Find field up to y=829.
#
# Ctrl+Home first, as everywhere else in this group. Calligra's Replace All does
# wrap - checked by running it with the cursor mid-document and watching the
# match count go to "No matches found" - but the group convention is to start
# from the top so the number is the whole document's.
#
# Both fields are set explicitly rather than relying on block 7 leaving
# `Cormorant` in the Find box, which it does.
K ctrl+Home; sleep 30
K ctrl+h; sleep 6
CLICK 250 829; sleep 1; K ctrl+a; T 'Cormorant';  sleep 2
CLICK 253 857; sleep 1; K ctrl+a; T 'Shearwater'; sleep 2
CLICK 539 857; sleep 60          # Replace All -> "No matches found"
CLICK 21 829                     # close the bar
CP "Replace all" 8

# --- 9. Type paragraph -------------------------------------------------------
# Calligra's status bar has no word count, so the confirmation here is the line
# number and, at the end of the run, check-result.sh.
K ctrl+End; sleep 60
K Return; sleep 3
T 'The kestrel circled above the reservoir before dawn.'; sleep 2; K Return; sleep 3
T 'Three technicians logged the reading and filed the sheet.'; sleep 2; K Return; sleep 3
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 10

# --- 10. Bold a line ---------------------------------------------------------
# The docker's B button lights up, which is the only confirmation Calligra
# offers - there is no selection word count.
K shift+Home; sleep 3
K ctrl+b
CP "Bold a line" 8

# --- 11. Resize the text -----------------------------------------------------
# The docker's font-size combo, cleared with Ctrl+A after a single click - the
# rule TextMaker taught this group. The selection stays live afterwards.
CLICK 1387 151; sleep 2
K ctrl+a; sleep 1
T '18'; sleep 1
K Return
CP "Resize the text" 8

# --- 12. Apply heading -------------------------------------------------------
# The docker's paragraph-style combo. Its popup is a separate 377x482 X window
# at 1054,249 carrying the document's class, and unlike AbiWord's it does NOT
# place the selected entry under the pointer - it renders the list from the top
# with the current style visible at the bottom. `Heading 1` is at a fixed y as
# long as the current style is `Text body`, which it always is at this point.
#
# Heading 1's own 22 pt replaces the 18 from block 11, as in every other
# application in the group. The document's Heading 1 is numbered, so the line
# renders as "1. Nothing in the record...".
CLICK 1237 233; sleep 4
CLICK 1143 416
CP "Apply heading" 10

# --- 13. Insert image --------------------------------------------------------
# ANOTHER DELIBERATE DEVIATION, forced by the application. Calligra Words has no
# Insert menu and no inline-picture command - the docker's Insert group is page
# breaks and sections. The only route is Add Shape > Image, which arms a tool;
# a single click on the canvas then places a FLOATING shape and opens the file
# dialog. So the picture floats over the text instead of sitting inline, and the
# page count does not change where every other application gains a page.
#
# check-result.sh counts Pictures/ entries, so it passes either way, but the
# layout is genuinely different and the README says so.
#
# Escape does NOT return to the text tool afterwards, and neither does clicking
# the text-tool icon in the rail. A double-click on body text does. 300,400 is
# body text well clear of where the image lands.
K ctrl+End; sleep 30
K Return; sleep 5
CLICK 1297 37;  sleep 5          # Add Shape
CLICK 1168 142; sleep 6          # Image
CLICK 400 570;  sleep 8          # place it -> [Image Options] file dialog
CLICK 815 562;  sleep 1
K ctrl+a
T '/tmp/parrot.png'; sleep 2
CLICK 947 644;  sleep 25         # OK
CLICK2 300 400                   # back to the text tool
CP "Insert image" 10

# --- 14. Insert table --------------------------------------------------------
# `Insert a table` opens a grid picker whose first entry is `Insert Custom...`,
# and that gives a dialog with numeric fields - far better than a grid
# coordinate. The dialog is pinned to 1440x900 by the window manager, so its
# fields are top-left and its buttons bottom-right.
#
# THE RIGHT ARROW MOVES BETWEEN CELLS. Tab does not - it inserts a tab
# character, leaving `Alpha<tab>Beta<tab>Gamma` in cell 1 and two empty cells
# beside it. That looked plausible on screen AND passed the old ground-truth
# check, which is why check-result.sh now asserts three separate cells.
K ctrl+End; sleep 30
K Return; sleep 5
CLICK 1066 394; sleep 6          # Insert a table
CLICK 1125 417; sleep 6          # Insert Custom...
CLICK 170 51; sleep 1; K ctrl+a; T '3'; sleep 1     # columns
CLICK 170 80; sleep 1; K ctrl+a; T '4'; sleep 1     # rows
CLICK 1301 877; sleep 12         # OK
T 'Alpha'; sleep 2; K Right; sleep 2
T 'Beta';  sleep 2; K Right; sleep 2
T 'Gamma'
CP "Insert table" 8

# --- 15. Insert page break ---------------------------------------------------
# ONE Ctrl+End, like AbiWord and TextMaker and unlike LibreOffice and
# OpenOffice: the first press leaves the table and reaches the end of the
# document. "Page 120-121 of 121" -> "Page 121-122 of 122".
K ctrl+End; sleep 35
K ctrl+Return
CP "Insert page break" 30

# --- 16. Undo and redo -------------------------------------------------------
# Ctrl+Shift+Z, NOT Ctrl+Y - see the header. 122 -> 121 -> 122.
K ctrl+z; sleep 30
K ctrl+shift+z
CP "Undo and redo" 30

# --- 17. Save ----------------------------------------------------------------
# No dialog: Calligra writes ODT natively and does not ask about keeping it.
# The status bar going from `Modified` to `Saved` is the confirmation.
K ctrl+s
CP "Save" 45

# --- 18. Export PDF ----------------------------------------------------------
# File > Export as PDF raises a [Page Layout] dialog FIRST - ISO A4, portrait,
# already correct - and the file dialog only after it is accepted.
CLICK 20 8;    sleep 4           # File menu
CLICK 80 231;  sleep 8           # Export as PDF...
CLICK 979 554; sleep 8           # OK on [Page Layout]
CLICK 708 562; sleep 1
K ctrl+a
T '/tmp/parrot-report.pdf'; sleep 2
K Return
CP "Export PDF" 90

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
