#!/usr/bin/env bash
# Drive SoftMaker FreeOffice TextMaker through
# applications/wordprocessors/script.md while record-macro.py records the input.
# One block per script line, each ending in a checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# Two rules this application imposes, both learned the expensive way:
#   * a spin/combo field is cleared with Ctrl+A, NOT a triple-click. A
#     triple-click leaves the old value in place and the typed digits are
#     APPENDED - 12 and 18 become 1218 and the only sign is an error box.
#   * Escape does not deselect an inserted picture. A click in the body text
#     does.
set -euo pipefail

# Matched on TITLE, not class. Every TextMaker dialog reports WM_CLASS "tm",
# "tm" as well, and the checkpoint capture takes head -n1 of the class search.
# The regex covers all three titles the document window carries - `Untitled 1 -
# TextMaker` before the open, then with and without the modified `*`, which
# appears at the first Search in block 7 rather than at the first edit.
TITLE_RE='^.+ - TextMaker$'

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
CLICK2() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 2 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a ribbon button both raises
# a tooltip and writes that button's description into the leftmost status-bar
# cell - measured: after the zoom dialog the status bar read "Zoom level" until
# the pointer moved. Either would be baked into the reference screenshot and
# then fail to reappear on replay.
#
# 700,450 is the middle of the text area at 100% zoom, and body text raises no
# tooltip.
park() { X mousemove 700 450; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion is on the TITLE match, because that is what the capture uses for
# this app. It checks both that exactly one window matched - TextMaker opens one
# top-level window per document, so a second one would be a second match - and
# that it is the 1440x900 document.
CP() {
    sleep "${2:-3}"
    park
    n="$(Q "xdotool search --onlyvisible --name '${TITLE_RE}' | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --name '${TITLE_RE}' | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving SoftMaker FreeOffice TextMaker ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `textmaker24free` through the
# startcommand and waited for the window. Nothing has to be dismissed: the two
# first-run dialogs ([User interface] and [User info]) and the welcome document
# are all seeded away in install.sh, verified from a clean container.
sleep 30
CP "Load app" 5

# --- 2. Open document --------------------------------------------------------
# A classic tree+list dialog. Its File name field takes an absolute path and
# Return activates the default button - both checked rather than assumed. The
# default file type already includes ODT, so the type combo is never touched.
#
# The empty Untitled 1 is REUSED, so this does not open a second window.
#
# TextMaker paginates this document to 97 pages where LibreOffice and OpenOffice
# both give 98 - which is why script.md counts keystrokes and never names a page.
K ctrl+o; sleep 6
CLICK 553 617; sleep 1
T '/tmp/parrot-report.odt'; sleep 2
K Return
CP "Open document" 60

# --- 3. Page through ---------------------------------------------------------
# Ends on "Page 5 of 97", at 100% zoom.
for _ in $(seq 1 10); do K Next; sleep 0.8; done
CP "Page through" 6

# --- 4. Jump to end ----------------------------------------------------------
# "L 37 Col 52 | Page 97 of 97".
K ctrl+End
CP "Jump to end" 25

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 20

# --- 6. Zoom -----------------------------------------------------------------
# Double-click the zoom percentage in the status bar, NOT View > Set zoom: the
# ribbon route would leave the ribbon on the View tab and blocks 10-12 need Home.
#
# The [Zoom] list does NOT reposition itself - reopened with 150% selected, the
# dialog came back in the same place with 100% still at y=541. That is the
# opposite of AbiWord's zoom box and was measured, not assumed.
CLICK2 1385 885; sleep 4
CLICK 560 579; sleep 2           # 150%
CLICK 884 366; sleep 8           # OK
CLICK2 1385 885; sleep 4
CLICK 560 541; sleep 2           # 100%
CLICK 884 366; sleep 8           # OK
CP "Zoom" 6

# --- 7. Find word ------------------------------------------------------------
# Ctrl+F opens [Search and replace] on its Search tab, 619x382 at 411,534.
# The Search button relabels itself "Search again" after the first click but
# does not move. After the third: "L 24 Col 24 | Page 3 of 97 | 1 word".
K ctrl+f; sleep 5
CLICK 615 605; sleep 1
T 'Cormorant'; sleep 2
CLICK 908 590; sleep 6
CLICK 908 590; sleep 5
CLICK 908 590; sleep 5
CLICK 908 628; sleep 4           # Close
CP "Find word" 5

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+Home FIRST. Replace All runs from the cursor and "Search from top" is
# unticked by default, so started from block 7's match on page 3 it would
# replace a subset and report that number as though it were the answer. From the
# top it reports 120, which is what the document contains.
#
# Ctrl+H opens the SAME window on its Replace tab, at a different size and
# position (619x458 at 411,458, because the taller tab re-centres it). Every
# coordinate below differs from block 7's.
K ctrl+Home; sleep 20
K ctrl+h; sleep 5
CLICK 615 529; sleep 1; K ctrl+a; T 'Cormorant'; sleep 1
CLICK 615 629; sleep 1; T 'Shearwater'; sleep 2
CLICK 908 590; sleep 40          # Replace all -> "120 occurrences have been replaced."
CLICK 721 500; sleep 3           # OK on the count box
CLICK 908 628; sleep 4           # Close
CP "Replace all" 5

# --- 9. Type paragraph -------------------------------------------------------
# Return first, so the block is its own paragraph rather than being glued to the
# end of the last one. One keystroke at a time rather than a paste.
# 54607 -> 54633 words.
K ctrl+End; sleep 25
K Return; sleep 2
T 'The kestrel circled above the reservoir before dawn.'; sleep 2; K Return; sleep 2
T 'Three technicians logged the reading and filed the sheet.'; sleep 2; K Return; sleep 2
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 5

# --- 10. Bold a line ---------------------------------------------------------
# The status bar switches to the SELECTED word count - "9 words" - which is the
# cheapest confirmation that the selection is live.
K shift+Home; sleep 2
K ctrl+b
CP "Bold a line" 4

# --- 11. Resize the text -----------------------------------------------------
# Click ONCE then Ctrl+A. A triple-click does not select the box's contents: the
# typed 18 is appended to the 12 and the only sign is
#   Error: The font size must be between 1 pt and 999 pt.
# with the box reading 1218.
CLICK 462 52; sleep 1
K ctrl+a; sleep 1
T '18'; sleep 1
K Return
CP "Resize the text" 5

# --- 12. Apply heading -------------------------------------------------------
# The style gallery is anchored under the box and lists every style without
# scrolling, with the current one merely highlighted, so Heading 1 is at a fixed
# y whatever the paragraph's style is. It is also an override-redirect popup
# that xdotool search cannot see, so it raises no window-matching problem.
#
# Heading 1's own 22 pt replaces the 18 from block 11, which is what the other
# apps in the group do too.
CLICK 976 67;  sleep 4           # the style box dropdown
CLICK 873 256; sleep 6           # Heading 1
CP "Apply heading" 5

# --- 13. Insert image --------------------------------------------------------
# Insert > Picture. "Save within document" is ticked by default, so the image is
# embedded and lands in the ODT's Pictures/.
#
# Escape does NOT deselect the inserted picture - measured; the handles and the
# contextual Picture ribbon tab both survive it. A click in the body text does.
# 700,800 is below the image's bottom edge (y~723 at this zoom), so it lands in
# text rather than re-selecting the picture.
K ctrl+End; sleep 15
K Return; sleep 3
CLICK 136 15;  sleep 3           # Insert ribbon tab
CLICK 161 60;  sleep 5           # Picture
CLICK 553 584; sleep 1
T '/tmp/parrot.png'; sleep 2
CLICK 811 584; sleep 15          # OK
CLICK 700 800; sleep 5           # deselect
CP "Insert image" 5

# --- 14. Insert table --------------------------------------------------------
# [New table] defaults to 3 rows by 3 columns, so only the row count changes -
# but both fields are set explicitly so the block does not depend on that
# default. Same Ctrl+A rule as the font-size box.
K ctrl+End; sleep 15
K Return; sleep 3
CLICK 136 15;  sleep 3           # Insert ribbon tab
CLICK 93 60;   sleep 5           # Table
CLICK 590 407; sleep 1; K ctrl+a; T '4'; sleep 1     # Rows
CLICK 770 407; sleep 1; K ctrl+a; T '3'; sleep 1     # Columns
CLICK 918 410; sleep 8                               # OK
T 'Alpha'; sleep 1; K Tab; sleep 1
T 'Beta';  sleep 1; K Tab; sleep 1
T 'Gamma'
CP "Insert table" 5

# --- 15. Insert page break ---------------------------------------------------
# ONE Ctrl+End, unlike LibreOffice and OpenOffice. In both of those the first one
# only reaches the end of the table and Ctrl+Return there is a silent no-op; in
# TextMaker one press leaves the table and reaches the end of the document -
# confirmed by the contextual Table ribbon tab disappearing and the cursor
# reading L 23 Col 1. "Page 98 of 98" -> "Page 99 of 99".
K ctrl+End; sleep 15
K ctrl+Return
CP "Insert page break" 15

# --- 16. Undo and redo -------------------------------------------------------
# 99/99 -> 98/98 -> 99/99.
K ctrl+z; sleep 15
K ctrl+y
CP "Undo and redo" 15

# --- 17. Save ----------------------------------------------------------------
# No dialog: TextMaker writes ODT natively and does not ask about keeping it.
# The `*` leaving the title is the confirmation.
K ctrl+s
CP "Save" 20

# --- 18. Export PDF ----------------------------------------------------------
# File is a ribbon TAB, not a menu popup. PDF export raises an options dialog
# first (Export range = All is already selected) and a file dialog second.
CLICK 23 15;   sleep 4           # File ribbon tab
CLICK 489 60;  sleep 6           # PDF export
CLICK 907 727; sleep 6           # OK on the options
CLICK 720 617; sleep 1           # File name
K ctrl+a; sleep 1
T '/tmp/parrot-report.pdf'; sleep 2
CLICK 1148 617                   # OK
CP "Export PDF" 60

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
