#!/usr/bin/env bash
# Drive FluffyChat through applications/chatclients/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowraise`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THE RULES THIS FILE IS BUILT AROUND, all measured, and most of them specific
# to Flutter:
#
#   1. MESSAGE ACTIONS NEED A LONG PRESS. Right-click opens Flutter's own
#      text-selection menu ("Select all") and left-click does nothing at all.
#      Both look like the affordance and neither is. See PRESS() below.
#
#   2. THE SEARCH RESULT ROW IS NOT AT A FIXED POSITION. `Parrot Echo` also
#      matches the `echo` bot user, which inserts a Users section and pushes the
#      Chats row down 96 px. Clicking the wrong y opens nothing, leaves the
#      previous room on screen, and the next message goes THERE. That happened
#      while measuring; `ping` landed in Windvane Deployment. Every room's row
#      is pinned individually below.
#
#   3. `Prior` does not scroll - the same trap as Fractal. Scrolling is the
#      wheel, measured at 53 px per notch, so 14 notches is one screen.
#
#   4. PARK ON THE NAV RAIL. Hovering a message draws a row highlight into the
#      reference image. (40, 450) is empty rail, outside the timeline.
#
#   5. Chat details NARROWS the timeline while open - the composer moves 190 px
#      left - so block 7 closes it before anything else happens.
#
#   6. The `+` button creates a SPACE by default, not a room.
set -euo pipefail

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }

# Long press - the ONLY way to reach a message's actions. Rule 1.
PRESS() { X mousemove "$1" "$2"; sleep 1; X mousedown 1; sleep 1.2; X mouseup 1; sleep 3; }

# Wheel notches. 53 px each, so 14 notches is one ~760 px viewport. This is
# FluffyChat's stand-in for the `Prior` loop the other clients use.
WHEEL()   { X mousemove "$1" "$2"; sleep 0.4; for _ in $(seq 1 "$3"); do X click 4; done; }
SCREENS() { for _ in $(seq 1 "$1"); do WHEEL 950 400 14; sleep "$2"; done; }

# Open a room through the search field. The row's y is passed in per room -
# see rule 2, this is not a constant.
ROOM() { CLICK 270 36; sleep 2; K ctrl+a; sleep 1; T "$1"; sleep 5; CLICK 270 "$2"; sleep "${3:-16}"; }

# Park the pointer somewhere inert before every capture. Rule 4.
park() { X mousemove 40 450; sleep 1; }

# The size of a full-screen PNG, in bytes. `import` is a passive X client - it
# reads the root window and sends no input event - so calling it mid-recording
# does not put anything into the macro.
SHOT() { Q 'export DISPLAY=:99; import -window root /tmp/parrot-probe.png 2>/dev/null; stat -c %s /tmp/parrot-probe.png'; }

# Just above a blank or spinner screen and well below any real one. Measured on
# this client: the welcome screen is 88 kB and every real screen after it is
# larger, so there is plenty of headroom at 15000. Kept the same as Fractal's
# rather than the other three's 30000, for the same reason - see that driver.
PAINTED=15000

wait_paint() {
    local limit="${1:-420}" waited=0 sz
    while (( waited < limit )); do
        sz="$(SHOT)"
        if [[ "${sz:-0}" -gt "$PAINTED" ]]; then
            echo "  [paint] first painted frame after ${waited}s"
            return 0
        fi
        sleep 5; waited=$(( waited + 5 ))
    done
    echo "  FATAL: nothing painted after ${limit}s - the app never came up" >&2
    exit 1
}

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# FLUTTER PAINTS EVERYTHING ITSELF, onto ONE surface: menus, dialogs, the image
# viewer, the emoji picker and the Chat details panel are all inside the single
# 1440x900 window. So the window-count check cannot see any of them, and unlike
# in Fractal it is nearly a formality. The one thing it does catch is the XDG
# portal file chooser, which is a separate process with its own class - and that
# is exactly the failure block 17 used to have, so the check stays.
CP() {
    sleep "${2:-4}"
    park
    n="$(Q "xdotool search --onlyvisible --class fluffychat | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class fluffychat | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1"
    p="$(Q "xdotool search --onlyvisible --class xdg-desktop-portal-gtk | wc -l")"
    [[ "${p:-0}" == "0" ]] || echo "  WARNING: '$1' has the PORTAL FILE CHOOSER open - it does not match --class fluffychat"
    sz="$(SHOT)"
    [[ "${sz:-0}" -gt "$PAINTED" ]] || echo "  WARNING: '$1' would capture a blank or loading screen (${sz}B)"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving FluffyChat ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `flatpak-session flatpak run
# im.fluffychat.Fluffychat`. Nothing to dismiss on the welcome screen.
#
# The head time is deliberately the SAME as the other four - 20 s in
# record-session.sh, 25 s here, 5 s in CP - because it is measured time, and a
# client given a longer head burns more energy for no reason of its own.
wait_paint
sleep 25
CP "Load app" 5

# --- 2. Sign in --------------------------------------------------------------
# NOT "Login with Matrix-ID": that is the full-MXID route, which autodiscovers
# over HTTPS at the MXID's domain - something this group deliberately does not
# have. "Sign in" asks for the server first, which is the route that works.
#
# THE TYPED ADDRESS IS A RESULT ROW, NOT THE ANSWER. Typing it grows the list
# until Continue is pushed off the card; the row has to be SELECTED before
# Continue comes back. Clicking where Continue was lands in the list and does
# nothing at all.
CLICK 720 645; sleep 6                       # Sign in
CLICK 720 258; sleep 2                       # "Search or enter homeserver address"
T 'http://matrix.parrot.test:8008'; sleep 4
CLICK 686 334; sleep 3                       # select the row - REQUIRED
CLICK 720 705; sleep 12                      # Continue, which is back now
T 'parrot'; sleep 1                          # Matrix ID, focused; a bare localpart is accepted
CLICK 720 410; sleep 1                       # Password
T 'parrot'; sleep 1
CLICK 720 476
CP "Sign in" 25

# --- 3. Initial sync ---------------------------------------------------------
# The measurement this block exists for: 8000 messages, 66 rooms and a
# 509-member room arriving at once.
#
# "SKIP" DOES NOT SKIP. It skips the passphrase only - FluffyChat still
# generates a crypto identity and then SHOWS THE RECOVERY KEY, twelve random
# groups that differ on every run, in a large high-contrast block. A checkpoint
# there could never match a replay. The checkpoint goes after Continue.
#
# So this block is not quite the same block here as it is in nheko, Element and
# SchildiChat: FluffyChat, like Fractal, does cross-signing work that cannot be
# opted out of. That belongs in the results.
CLICK 720 485; sleep 10                      # Skip - the passphrase, not the setup
CLICK 886 142                                # Continue - NEVER checkpoint this screen
CP "Initial sync" 40

# --- 4. Open busy room -------------------------------------------------------
ROOM 'Aurora Release' 252 22
CP "Open busy room" 8

# --- 5. Scroll back ----------------------------------------------------------
# Ten screens, fourteen notches each, with a settle between - script.md asks for
# each batch of older messages to finish loading before scrolling again.
SCREENS 10 2
CP "Scroll back" 8

# --- 6. Jump to live ---------------------------------------------------------
# Measured to return the timeline byte-identical to the pre-scroll live view.
CLICK 1404 792
CP "Jump to live" 10

# --- 7. Open member list -----------------------------------------------------
# An in-window panel, like Element and SchildiChat. It NARROWS the timeline
# while open, so it is closed explicitly - which also makes the block boundary
# mean the same thing it means in the other clients.
CLICK 587 29; sleep 12                       # room header -> Chat details, 509 participants
CLICK 1088 36                                # close
CP "Open member list" 5

# --- 8. Open photo room ------------------------------------------------------
# 400 images, decoded with no configuration at all: FluffyChat does not
# implement MSC4278, so unlike Fractal there is nothing to seed here and this
# block is directly comparable with the three non-Flatpak clients.
ROOM 'Field Photos' 252 22
CP "Open photo room" 8

# --- 9. View image full size -------------------------------------------------
# In-window viewer. The target is reservoir-at-first-light.jpg, confirmed on the
# server rather than from the viewer, which shows no filename.
CLICK 762 707; sleep 12
CLICK 28 36                                  # close
CP "View image full size" 5

# --- 10. Scroll thumbnails ---------------------------------------------------
SCREENS 5 3
CP "Scroll thumbnails" 8

# --- 11. Filter room list ----------------------------------------------------
CLICK 270 36; sleep 2
K ctrl+a; sleep 1
T 'windvane'
CP "Filter room list" 5

# --- 12. Open filtered room --------------------------------------------------
CLICK 270 252; sleep 20
CLICK 121 36                                 # clear the filter, as script.md asks
CP "Open filtered room" 6

# --- 13. Send message --------------------------------------------------------
CLICK 950 856; sleep 2
T 'Thank you so much'; sleep 1
K Return
CP "Send message" 8

# --- 14. Reply to message ----------------------------------------------------
# LONG PRESS. Right-click gives Flutter's "Select all" and nothing else.
PRESS 804 644
CLICK 1288 856; sleep 4                      # Reply
T 'Agreed, going out today'; sleep 1
K Return
CP "Reply to message" 8

# --- 15. React to message ----------------------------------------------------
# TARGET THE ORIGINAL, NOT THE QUOTE. The reply just sent renders a quoted copy
# of Nadia's text at y~735; the original is at y~547. Reacting to the quote
# attaches the reaction to the reply event instead, and only ground truth can
# tell the difference - which is why this was checked by resolving the target
# event's SENDER, not by looking at the screen.
#
# THE QUICK ROW, NOT THE PICKER, and that is a deviation from the other four.
# The custom-reaction picker opens fine but 👍 is below its fold and the grid
# does not scroll with the wheel - 12 notches moved it 0 px, measured. So no
# full emoji picker is rendered here while the others do render one. It is in
# MEASUREMENTS.md and belongs in the results.
PRESS 804 547
CLICK 650 549                                # 👍 in the quick-reaction row
CP "React to message" 8

# --- 16. Edit message --------------------------------------------------------
# Own messages are right-aligned, as in SchildiChat. Selecting an OWN message
# adds edit and delete to the top bar, and because that row is right-aligned
# every icon shifts: (1244, 36) is the pencil on an own message and empty bar on
# a received one. Edit is NOT in the `⋮` menu, which holds only Message info and
# Report message.
PRESS 1229 670
CLICK 1244 36; sleep 4                       # the pencil
K ctrl+a; sleep 1
T 'Thank you so much indeed'; sleep 1
K Return
CP "Edit message" 8

# --- 17. Upload image --------------------------------------------------------
# PASTED, NOT CHOSEN, for exactly the reason Fractal's block 17 is: FluffyChat
# is a Flatpak, its chooser is the XDG portal, and the portal hands files over
# through the FUSE-backed document portal, whose mount needs CAP_SYS_ADMIN -
# dropped on purpose in cbe1099. Driven through the chooser this block attaches
# NOTHING and says so nowhere.
#
# What is still measured: the same 762 kB image encoded, uploaded and rendered.
# What is not: the file chooser. The event also arrives with an EMPTY body here,
# where Fractal's arrives as `image.png`.
#
# The paste raises a dialog headed "Send file" with a document icon rather than
# an image preview - it still sends a real m.image with mimetype image/png.
# SEND IS THE STEP THAT UPLOADS; the dialog closing means nothing.
CLICK 950 856; sleep 2                       # composer, so the paste lands in it
K ctrl+v; sleep 10
CLICK 816 546                                # Send - the step that matters
CP "Upload image" 16

# --- 18. Echo round trip -----------------------------------------------------
# ROW AT 348, NOT 252. `Parrot Echo` also matches the `echo` bot user, so a
# Users section is inserted above Chats. Clicking 252 here opens nothing, leaves
# the previous room on screen, and sends `ping` to THAT room instead. Measured.
ROOM 'Parrot Echo' 348 16
CLICK 950 856; sleep 2
T 'ping'; sleep 1
K Return
CP "Echo round trip" 14

# --- 19. Join room -----------------------------------------------------------
# The address goes in the same search field and comes back as a TILE under
# Public Rooms, not a list row.
CLICK 270 36; sleep 2
K ctrl+a; sleep 1
T '#parrot-lobby:parrot.test'; sleep 8
CLICK 123 145; sleep 12                      # the Public Rooms tile -> room card
CLICK 720 519                                # Join room
CP "Join room" 20

# --- 20. Create room ---------------------------------------------------------
# THE + BUTTON CREATES A SPACE BY DEFAULT. Left alone this produces an m.space,
# which is not a room, is not what script.md asks for and is not what the other
# clients produce. Group has to be chosen first.
#
# Encryption is OFF by default here, unlike Element and SchildiChat. Turning on
# "Group is public" reveals a third row and pushes the create button down 56 px.
# There is no room-address field.
CLICK 40 100; sleep 5                        # + -> New space
CLICK 902 156; sleep 4                       # Group - REQUIRED, or this makes a space
CLICK 950 360; sleep 1
T 'Parrot benchmark'; sleep 2
CLICK 1174 428; sleep 3                      # Group is public
CLICK 950 610; sleep 18                      # Create a group and invite users

# Straight into Invite contact. The row's Invite link flips to "Participant"
# once sent - verified with matrix-truth rather than by that label.
CLICK 950 168; sleep 2
T '@alice:parrot.test'; sleep 8
CLICK 1180 244                               # Invite
CP "Create room" 12

# --- 21. Leave room ----------------------------------------------------------
ROOM 'Parrot Lobby' 252 16
CLICK 1404 36; sleep 4                       # room menu
CLICK 1324 288; sleep 5                      # Leave
CLICK 815 516                                # confirm Leave
CP "Leave room" 14

# --- 22. Idle quiet ----------------------------------------------------------
ROOM 'Parrot Firehose' 252 20
sleep 60
CP "Idle quiet" 4

# --- 23. Idle receiving ------------------------------------------------------
# `drip` is the trigger: the bot posts drip 01..24, one every 5 s, scheduled
# against a fixed start so the burst does not drift.
CLICK 950 856; sleep 2
T 'drip'; sleep 1
K Return
sleep 130
CP "Idle receiving" 6

echo "=== driven ==="
