#!/usr/bin/env bash
# Everything the seven emulators need in common. Each app's install.sh sources
# this and then adds only its own configuration, because the shared half is not
# a detail: if the entrants do not get the same font, the same locale and the
# same corpus, the benchmark measures those instead of the emulator.
#
#   source install-common.sh          install the shared half
#   COMMON_PROFILE_ONLY=1 source ...  re-stage the corpus and prompt only
set -euo pipefail

clog() { printf '[install-common] %s\n' "$*"; }

if [[ "${COMMON_PROFILE_ONLY:-0}" -eq 0 ]]; then
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq

# fonts-dejavu-core is not cosmetic. Every entrant is configured to render
# DejaVu Sans Mono at one size, because otherwise the comparison measures the
# font's hinting and coverage as much as the emulator's drawing.
#
# locales is load-bearing rather than nice-to-have: GNOME Terminal REFUSES TO
# START without a UTF-8 locale - `Non UTF-8 locale (ANSI_X3.4-1968) is not
# supported!` and no window ever appears - and the container image ships none.
# The Unicode block is a third of the point of this group, and a C locale
# mangles it in the six that do start.
#
# xclip is the ground truth for block 16. The mouse drag leaves its text in the
# X PRIMARY selection and nothing else records that it happened.
#
# xfonts-base is here for one entrant only (zutty needs its bitmap fonts) and
# costs nothing; it is kept so that adding zutty back is a one-file change.
#
# fonts-wqy-microhei is here because without a CJK font the Unicode block does
# not test what it claims to. DejaVu Sans Mono has no CJK coverage at all, and
# the first xterm recording rendered `日本語のテキスト` and the kana row as rows
# of empty boxes - tofu. The double-width CELL handling was still being
# exercised, since the boxes were correctly two cells wide, but no CJK glyph was
# ever drawn, and the block's whole reason for existing is that cell-width rules
# are where emulators disagree *even when every glyph is present*.
#
# wqy-microhei rather than fonts-noto-cjk: about 5 MB against 50 MB, and full
# coverage of the Han, kana and Hangul this corpus uses. Every entrant gets the
# same font, so any remaining difference is the emulator's font FALLBACK - which
# is a genuine property of the emulator and one of the more interesting things
# this block can show.
clog "installing the shared dependencies"
apt-get install -y -qq --no-install-recommends \
    fonts-dejavu-core fontconfig \
    fonts-wqy-microhei \
    locales \
    xclip \
    less coreutils \
    x11-xserver-utils \
    >/dev/null

locale-gen en_US.UTF-8 >/dev/null 2>&1
update-locale LANG=en_US.UTF-8 >/dev/null 2>&1
fc-cache -f >/dev/null 2>&1 || true
fi   # end of the install half

# --- the launch environment ----------------------------------------------
#
# Sourced by every parrot-<app> launcher before it execs the emulator, and it is
# the single most load-bearing file in the group.
#
# An emulator decides whether it is a UTF-8 terminal from ITS OWN environment at
# startup - before the shell inside it exists, so the LANG in /root/.bashrc below
# comes far too late to help. Without this, xterm draws `â` where `│` belongs and
# turns the box-drawing and CJK blocks into Latin-1 mojibake; gnome-terminal is
# blunter and refuses to start at all. Both were observed, not guessed.
#
# The scenarios also set LANG in their `environment:` block, so under GMT the
# variable arrives twice. That is deliberate: the two paths fail independently,
# and a recording of mojibake replayed against a correct benchmark fails every
# checkpoint from block 8 onward with nothing in the macro to point at.
clog "writing /etc/parrot-env"
cat > /etc/parrot-env <<'ENV'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
ENV

# write_launcher <app> <pre-exec lines...> - the last argument is the exec line.
# Every entrant gets one even when it needs nothing but the locale, so that the
# drivers all launch `parrot-<app>` and differ nowhere else, and so that adding a
# pre-exec step later does not change how the app is started.
write_launcher() {
    local name="${1:?write_launcher <app> <line>...}"; shift
    { echo '#!/bin/bash'
      echo '# Generated by install-common.sh:write_launcher - do not edit.'
      echo '. /etc/parrot-env'
      printf '%s\n' "$@"
    } > "/usr/local/bin/parrot-${name}"
    chmod +x "/usr/local/bin/parrot-${name}"
    clog "wrote /usr/local/bin/parrot-${name}"
}

# --- the corpus ----------------------------------------------------------
#
# Staged out of the read-only repo mount into a writable path, because the
# session log lives beside nothing and the scripts have to be executable. The
# path is identical in every app so the reference screenshots show the same
# command lines.
clog "staging the corpus at /opt/parrot"
rm -rf /opt/parrot/corpus
mkdir -p /opt/parrot
cp -r /tmp/repo/applications/terminals/corpus /opt/parrot/corpus
chmod -R a+rX /opt/parrot/corpus
find /opt/parrot/corpus -name '*.sh' -exec chmod a+x {} +
rm -f /tmp/parrot-term.log

# --- the shell -----------------------------------------------------------
#
# The prompt is in every single reference screenshot, so every part of it that
# could vary between the recording and the replay has to go: the hostname is the
# container id and changes every run, the working directory would move, and a
# clock would change every second. `parrot$ ` and nothing else.
#
# HISTFILE=/dev/null so that a replay cannot be influenced by what a previous
# run typed, and so that Up-arrow is never ambiguous.
#
# TERM is deliberately NOT set here. Each emulator sets its own - xterm-256color,
# rxvt-unicode-256color, alacritty, xterm-kitty, st-256color - and programs
# inside behave slightly differently as a result. That is a genuine property of
# the emulator being measured and normalising it away would hide a real
# difference. It is recorded per app in MEASUREMENTS.md instead.
clog "seeding the shell profile"
cat > /root/.bashrc <<'BRC'
export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
export PS1='parrot$ '
export HISTFILE=/dev/null
export LESSHISTFILE=/dev/null
# A fixed LS_COLORS, so block 13 renders the same colours in every entrant
# rather than whatever each app's environment happens to inherit.
export LS_COLORS='di=01;34:ln=01;36:ex=01;32:*.txt=00;37:*.sh=01;32:*.tar.gz=01;31:*.png=01;35:*.log=00;33:*.py=01;33:*.zip=01;31:*.md=00;36'
cd /opt/parrot
BRC
cp /root/.bashrc /root/.bash_profile

clog "common setup done"
