#!/usr/bin/env bash
# Drive Collabora Office through applications/wordprocessors/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THIS APPLICATION IS A WEB VIEW. Collabora's desktop suite is Collabora Online's
# UI running offline on QtWebEngine, and three rules follow from that:
#
#   * Keyboard first, wherever there is a choice. Ctrl+End, Ctrl+Home, Ctrl+B,
#     Ctrl+1, Ctrl+Return, Ctrl+Z, Ctrl+Y and Ctrl+S all behave like
#     LibreOffice's. The ribbon is only needed for the image, the table and the
#     PDF export.
#   * NEVER click the Styles gallery at the top of the Home ribbon, and never
#     type into it. When it has not finished painting, a click on it clears the
#     direct formatting of the live selection and does NOT take focus - so the
#     next thing typed replaces the selection instead. Both failures leave a
#     completely plausible screen. Block 12 uses Ctrl+1 for that reason.
#   * Never press Escape to close a panel. It closes the panel AND leaves the
#     following keystrokes going to the document. Block 7 uses the Navigation
#     panel's own close button. (Escape on a selected picture is fine and is
#     what block 13 uses - that one was measured.)
#
# It also lays out asynchronously, so every settle here is longer than the
# native applications in this group needed.
set -euo pipefail

# WM_CLASS is "coda-qt", "Collabora Office" - NOT soffice.
#
# The two halves of WM_CLASS are res_name and res_class, and THIS APPLICATION IS
# THE ONE IN THE GROUP WHERE THEY DIFFER. fluxbox's `[app] (name=...)` rule
# matches res_name, so usage_scenario.yml pins on `coda-qt`; xdotool's --class
# matches res_CLASS, so everything here has to match on `collabora` instead.
# Using coda-qt for both looks obviously right and finds nothing:
#
#   xdotool search --onlyvisible --class coda-qt      -> no output, rc=1
#   xdotool search --onlyvisible --class collabora    -> the window
#   xdotool search --onlyvisible --classname coda-qt  -> the window
#
# The match is a case-insensitive regex, so `collabora` is enough and avoids
# putting a space in the pattern.
#
# Matching on the class is safe here because exactly one such window exists at
# every checkpoint: the start screen closes itself the moment the document
# window appears, and the two file dialogs are shut before their block ends.
# CP() asserts both facts.
CLASS=collabora

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK() { X mousemove "$1" "$2"; sleep 0.4; X click 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a ribbon button raises a
# tooltip that would be baked into the reference screenshot and then fail to
# reappear on replay.
#
# 700,450 is inside the page at every zoom this run uses, and body text raises
# no tooltip. On the start screen it is empty background.
park() { X mousemove 700 450; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# record-macro.py captures `xdotool search --onlyvisible --class <class> |
# head -n1` - the FIRST match, not the largest - so the count assertion is not
# decoration. A second coda-qt window would mean either a leftover start screen
# or an open file dialog, and either would be photographed instead of the
# document.
CP() {
    sleep "${2:-3}"
    park
    n="$(Q "xdotool search --onlyvisible --class ${CLASS} | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Collabora Office ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched the app through the startcommand, but it
# only waits a second for the window; this one takes about 55 s to appear cold,
# because a Flatpak sandbox and a Chromium have to start first.
#
# Collabora opens a START SCREEN - a template gallery with Home / New / Open
# down the left - not a document, and that is where this block ends. Clicking
# `Blank Document` to reach an editable page is NOT an option: the new document
# arrives in a SECOND 1440x900 window with the same class, and from then on
# neither the recorder nor replay.py can tell the two apart. See MEASUREMENTS.md.
sleep 75
CP "Load app" 5

# --- 2. Open document --------------------------------------------------------
# `Open` in the left rail raises a Qt file dialog - the portal is absent in this
# container, which is good news: the in-process fallback is deterministic where
# a portal's appearance would depend on what is running outside the sandbox.
#
# The start screen closes itself once the document window is up, so there is
# exactly one window again by the time this block ends.
#
# The mode switch is part of THIS block, not block 3. The document arrives in
# `Viewing` mode with no ribbon at all - File / Edit / View / Help only - and
# nothing in blocks 3-18 can be driven from there. Block 2's job is to leave the
# document open and usable, so the switch belongs here rather than as a tax on
# block 3.
CLICK 79 300; sleep 8            # Open
CLICK 708 562; sleep 1           # File name
K ctrl+a
T '/tmp/parrot-report.odt'; sleep 2
K Return; sleep 75
CLICK 1421 17; sleep 3           # the mode selector arrow
CLICK 1381 73                    # Editing Mode
CP "Open document" 30

# --- 3. Page through ---------------------------------------------------------
# Ends on "Page 4 of 98" - at the 170% Collabora opens the document with, ten
# presses move three pages.
for _ in $(seq 1 10); do K Next; sleep 1.2; done
CP "Page through" 8

# --- 4. Jump to end ----------------------------------------------------------
# "Page 98 of 98" - the same pagination LibreOffice and OpenOffice give, and the
# right fonts with it. Takes about 35 s.
K ctrl+End
CP "Jump to end" 45

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 30

# --- 6. Zoom -----------------------------------------------------------------
# The zoom list has both 150 and 100, so this is one of only three applications
# in the group that can do block 6 exactly.
#
# The list does NOT reposition itself: reopened at 150%, it came back with 100
# still at y=770. Measured twice, in two different sessions, by re-reading the
# list rather than by assuming.
CLICK 1334 884; sleep 4          # the percentage, opens the list
CLICK 1327 830; sleep 20         # 150
CLICK 1334 884; sleep 4
CLICK 1327 770                   # 100
CP "Zoom" 20

# --- 7. Find word ------------------------------------------------------------
# Ctrl+F opens a Navigation SIDEBAR, not a find bar. It reports "120 results",
# which is exactly what the document contains and is free ground truth.
#
# Return alone does not set the result index; three clicks on the down button
# reach "Result 3 of 120". The status bar reads "Selected: 120 words, 1,080
# characters" throughout, because Collabora highlights every match at once.
#
# Close it with its own X. Escape would close it too, and would also send the
# next keystrokes into the document - that is how a stray `Cormorant` ended up
# on the title page while this was being measured.
K ctrl+f; sleep 8
CLICK 109 201; sleep 1           # search box
T 'Cormorant'; sleep 2
K Return; sleep 25
CLICK 233 276; sleep 6           # next result
CLICK 233 276; sleep 6
CLICK 233 276; sleep 6
CLICK 220 148                    # close the panel
CP "Find word" 8

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+Home FIRST, as everywhere else in this group: Replace All runs from the
# cursor, and block 7 left it on page 3.
#
# The Find and Replace box is drawn INSIDE the web view, so it is not a separate
# X window and nothing in WINS or CP() ever sees it. "Search key replaced 120
# times." and 361,913 -> 362,033 characters are the confirmations.
#
# The ribbon's Search menu stays open behind the dialog and has to be toggled
# shut afterwards, or the checkpoint photographs a menu.
K ctrl+Home; sleep 25
CLICK 1083 70; sleep 4           # Search
CLICK 1123 172; sleep 6          # Replace
CLICK 763 400; sleep 1; T 'Cormorant';  sleep 2
CLICK 777 489; sleep 1; T 'Shearwater'; sleep 2
CLICK 874 541; sleep 60          # Replace All
CLICK 917 313; sleep 6           # close the dialog
CLICK 1083 70                    # close the Search menu
CP "Replace all" 8

# --- 9. Type paragraph -------------------------------------------------------
# 54,607 -> 54,633 words. Ctrl+End still reaches the document even though the
# last thing clicked was a ribbon button - checked rather than assumed.
K ctrl+End; sleep 45
K Return; sleep 3
T 'The kestrel circled above the reservoir before dawn.'; sleep 2; K Return; sleep 3
T 'Three technicians logged the reading and filed the sheet.'; sleep 2; K Return; sleep 3
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 10

# --- 10. Bold a line ---------------------------------------------------------
# The status bar switches to "Selected: 9 words, 53 characters", which is the
# cheapest confirmation that the selection is live.
K shift+Home; sleep 3
K ctrl+b
CP "Bold a line" 8

# --- 11. Resize the text -----------------------------------------------------
# At 1440x900 the ribbon is in its compact form and the whole Font group is a
# single button; its arrow expands a panel with the family and size boxes.
#
# Click the size box ONCE then Ctrl+A - the same rule TextMaker needs. Collapsing
# the panel afterwards is safe: the bold and the 18 pt both survive it, verified
# by reading the rendered line, not the box.
CLICK 263 70;  sleep 4           # expand the Font group
CLICK 510 139; sleep 2           # size box
K ctrl+a; sleep 1
T '18'; sleep 1
K Return; sleep 8
CLICK 237 70                     # collapse it again
CP "Resize the text" 8

# --- 12. Apply heading -------------------------------------------------------
# Ctrl+1. Keyboard-only, so it has no coordinates and does not depend on the
# Styles gallery painting - which is exactly the point. See the header.
K ctrl+1
CP "Apply heading" 12

# --- 13. Insert image --------------------------------------------------------
# The Insert ribbon paints correctly; it is only the Home tab's Styles gallery
# that is unreliable. The image lands inline and the page count goes 98 -> 99.
#
# Escape DOES deselect the picture here, unlike TextMaker - confirmed by the
# contextual Picture tab disappearing from the tab strip.
K ctrl+End; sleep 25
K Return; sleep 5
CLICK 236 17;  sleep 5           # Insert tab
CLICK 352 53;  sleep 8           # Image
CLICK 708 562; sleep 1           # File name
K ctrl+a
T '/tmp/parrot.png'; sleep 2
K Return; sleep 25
K Escape                         # deselect
CP "Insert image" 10

# --- 14. Insert table --------------------------------------------------------
# Table opens a 10x10 grid picker rather than a dialog. The picker labels its own
# selection - hovering 289,182 shows the tooltip "3 x 4" - so the coordinate was
# confirmed in text before it was clicked, not counted off a screenshot.
K ctrl+End; sleep 25
K Return; sleep 5
CLICK 236 17;  sleep 5           # Insert tab
CLICK 250 60;  sleep 5           # Table
CLICK 289 182; sleep 12          # the 3 x 4 cell
T 'Alpha'; sleep 2; K Tab; sleep 2
T 'Beta';  sleep 2; K Tab; sleep 2
T 'Gamma'
CP "Insert table" 8

# --- 15. Insert page break ---------------------------------------------------
# TWO Ctrl+End presses, the LibreOffice and OpenOffice trap, and it is silent:
#
#   Ctrl+End      -> the cursor lands in the LAST CELL of the table, which only
#                    the contextual Table ribbon tab gives away
#   Ctrl+Return   -> nothing at all. Page 99 of 99 before and after.
#   Ctrl+End      -> leaves the table; the tab strip returns to Home
#   Ctrl+Return   -> Page 100 of 100
K ctrl+End; sleep 25
K ctrl+End; sleep 25
K ctrl+Return
CP "Insert page break" 30

# --- 16. Undo and redo -------------------------------------------------------
# 100 -> 99 -> 100.
K ctrl+z; sleep 30
K ctrl+y
CP "Undo and redo" 30

# --- 17. Save ----------------------------------------------------------------
# No dialog at all - Collabora writes ODT natively and does not ask about
# keeping the format. `Save` in the File backstage goes grey afterwards.
#
# Worth knowing: this application AUTOSAVES, so the file on disk has already
# been rewritten before this block runs. Ctrl+S is still what the script asks
# for and still produces a fresh mtime, but the saved document is not proof on
# its own that this block ran.
K ctrl+s
CP "Save" 40

# --- 18. Export PDF ----------------------------------------------------------
# File is a ribbon TAB that opens a full-screen backstage. Take the plain `PDF`
# tile at the top right, not the `PDF ... with options` one below it, which
# raises a further dialog.
#
# 100 pages, which is 98 + the image page + the page break - the same as
# LibreOffice and OpenOffice, so Collabora needs no expected-pdf-pages file.
CLICK 98 17;   sleep 6           # File tab
CLICK 75 371;  sleep 6           # Export
CLICK 1321 207; sleep 10         # PDF Document (.pdf)
CLICK 708 562; sleep 1           # File name
K ctrl+a
T '/tmp/parrot-report.pdf'; sleep 2
K Return
CP "Export PDF" 90

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
