#!/usr/bin/env bash
# Drive the Eclipse IDE through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# Eclipse is the most mouse-driven driver in this group, and not by choice: it
# has no default binding for "open a file", its Find/Replace overlay puts the
# replace row behind a chevron, and its project-wide replace lives in a wizard.
# Every click below is at a coordinate that is fixed by pin-windows.sh, and the
# ones that are not obvious are explained where they appear.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=eclipse
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Empty space in the Package Explorer, below the single project row.  Not the
# Problems view, which block 18 replaces with the Search results tree, and not
# the editor, where the pointer sitting still long enough draws a hover.
park() { X mousemove 180 560; sleep 1; }

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving the Eclipse IDE ==="

# --- 1. Load app -------------------------------------------------------------
# Four things stand between a cold Eclipse and an editing surface, and all four
# are defaults:
#
#   the launcher      "Select a directory as workspace", prefilled with
#                     /root/eclipse-workspace.  Click Launch.
#   the Welcome page  a full-window intro tab.  Close it.
#   an empty workspace
#   the import        Eclipse has no "open this folder" argument.  The other
#                     IDEs in this group are handed /root/project on the command
#                     line; Eclipse's equivalent is File > Open Projects from
#                     File System, so that is where the same cost lands.
#
# Without the import there is no project, and with no project Eclipse's
# workspace-wide File Search - block 18 - has nothing to search.  Doing it here
# is what makes Eclipse's block 18 comparable to VS Code's rather than a
# file-by-file fallback.
#
# The sleeps are measured on a cold container, not guessed: the launcher window
# maps 4s after exec, the workbench 4s after Launch, and the Welcome page is
# pixel-stable from 10s.  The import is the slow part - the screen stops
# changing at ~45s - and it is slow because Eclipse refreshes the whole project
# into its workspace, including the 10 MB module.
sleep 15
X mousemove 998 571 click 1            # Launch
sleep 25
X mousemove 129 79 click 1             # close the Welcome tab
sleep 6
X mousemove 19 12 click 1              # File
sleep 3
X mousemove 160 87 click 1             # Open Projects from File System...
sleep 5
T '/root/project'
sleep 6
X mousemove 1101 651 click 1           # Finish
CP "Load app" 60

# --- 2. Open file ------------------------------------------------------------
# The Package Explorer click is required, not decorative.  When the import
# wizard closes, no workbench PART holds the focus - and Eclipse resolves key
# bindings against the focused part, so Ctrl+Shift+R is silently ignored until
# something inside the workbench has been clicked.  The first recording lost
# block 2 entirely to this and carried on into an editor that was never opened.
X mousemove 60 138 click 1
sleep 3
K ctrl+shift+r
sleep 4
T 'price_calculator.py'
sleep 3
K Return
CP "Open file" 8

# --- 3. Scroll to function ---------------------------------------------------
# The wheel, not Page Down, and for the reason VS Code and Sublime use it too:
# scrolling must not move the caret, or the search in block 4 starts below the
# first `tax_rate` and finds the wrong one.
#
# 30 clicks x 3 lines would put line 91 at the top; Eclipse will not scroll past
# the last line, so it clamps at 96 and shows 96..129.  Clamped is better than
# counted - the exact number of clicks stops mattering.
X mousemove 760 400
for _ in $(seq 1 30); do X click 5; sleep 0.05; done
CP "Scroll to function" 4

# --- 4. Find identifier ------------------------------------------------------
# Ctrl+F, Escape, Ctrl+F - and the second Ctrl+F is not superstition.
#
# The first Ctrl+F of a fresh workspace opens the inline overlay AND a one-time
# notification, "New Find/Replace Overlay", which takes the keyboard focus and
# never times out.  Anything typed while it is up goes nowhere: the first
# attempt at this block typed `tax_rate` into a void and checkpointed a
# screenshot that looked entirely correct.
#
# Escape dismisses it.  Escape also closes the overlay and returns focus to the
# editor - hence the second Ctrl+F, which reopens the overlay with its find
# field focused.  Clicking the notification's X instead ALSO works, but the
# click reaches the editor underneath and moves the caret, which then has to be
# put back.
K ctrl+f
sleep 3
K Escape
sleep 2
K ctrl+f
sleep 2
K ctrl+a
sleep 1
T 'tax_rate'
CP "Find identifier" 4

# --- 5. Select line ----------------------------------------------------------
# Return steps to the next match: 110 -> 117, the `tax = subtotal * tax_rate`
# the script names.  Escape then closes the overlay leaving the caret on it.
#
# Home is Eclipse's smart home - first non-whitespace, not column 0 - so
# Shift+End selects the statement without its indent.  The status bar reads
# 117 : 30 [25].
K Return
sleep 2
K Escape
sleep 2
K Home
sleep 1
K shift+End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
# Return here auto-indents from the line above, so the paste lands at column 5
# without the four spaces being copied - which is why block 5 selects the
# statement rather than the whole line.
K ctrl+c
sleep 1
K End
sleep 1
K Return
sleep 1
K ctrl+v
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice: one for the paste, one for the line the Return opened.  Same as VS
# Code, IntelliJ, Sublime and nano; only Vim, Neovim and Emacs manage it in one.
K ctrl+z
sleep 1
K ctrl+z
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+Home first: the overlay searches forward from the caret, and the caret is
# in the middle of the file after the undo.
#
# The chevron at 652,117 expands the replace row, and focus lands in the REPLACE
# field when it does - not the find field.  Tab does not move between the two:
# it leaves the overlay altogether, and the Ctrl+A that follows then selects the
# whole document instead of a field's contents.  So each field is clicked.
#
# Ctrl+A before every field, for the reason IntelliJ taught this group: the
# overlay retains the previous term and pre-selects it in the find field but not
# in the replace field, so typing appends there instead of replacing.
K ctrl+Home
sleep 1
K ctrl+f
sleep 2
K ctrl+a
sleep 1
T 'tax_rate'
sleep 2
X mousemove 652 117 click 1            # expand the replace row
sleep 2
K ctrl+a
sleep 1
T 'vat_rate'
sleep 2
X mousemove 1124 162 click 1           # Replace All
CP "Replace all" 4

# --- 9. Undo replace ---------------------------------------------------------
# Escape first, or the Ctrl+Z undoes the text in the replace FIELD.  Once:
# Eclipse groups a Replace All into a single undo, like everything here except
# nano.
K Escape
sleep 2
K ctrl+z
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# Home puts the caret before `return`, past the indent; typing the comment and
# then Return splits the line and auto-indents the tail back to column 5.  The
# comment therefore ends up at column 5 as well, which is what the ground-truth
# check reports.
K ctrl+f
sleep 2
K ctrl+a
sleep 1
T 'return subtotal + tax'
sleep 3
K Escape
sleep 2
K Home
sleep 1
T '# benchmark complete'
sleep 1
K Return
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
K ctrl+s
CP "Save file" 4

# --- 12. Reopen file ---------------------------------------------------------
# Ctrl+W closes the editor; the Package Explorer click is the same focus problem
# as block 2, because closing the last editor leaves no part focused.
K ctrl+w
sleep 3
X mousemove 60 138 click 1
sleep 3
K ctrl+shift+r
sleep 4
T 'price_calculator.py'
sleep 3
K Return
CP "Reopen file" 8

# --- 13. Open large file -----------------------------------------------------
# The Java package has no Python tooling, but the platform ships tm4e TextMate
# grammars, so the 10 MB module comes up fully coloured and folded.  Measured
# cold: the screen is pixel-identical at 20s and at 140s, so 35s is settle plus
# margin rather than a guess at how long Eclipse needs.
K ctrl+shift+r
sleep 4
T 'component_library.py'
sleep 3
K Return
CP "Open large file" 35

# --- 14. Go to line ----------------------------------------------------------
# Ctrl+L is Go to Line in an Eclipse text editor.  The dialog reads
# "Enter line number (1..337,538)".
K ctrl+l
sleep 3
T '120000'
sleep 2
K Return
CP "Go to line" 12

# --- 15. Page down -----------------------------------------------------------
# 33 lines a screen - the smallest viewport in this comparison, because the
# default Java perspective spends the window on a Package Explorer, a Task List,
# an Outline and a Problems view.  L120000 -> L120330.
for _ in $(seq 1 10); do K Next; sleep 0.4; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
# Generous settle: a jump of 337,000 lines repaints the ruler, the folding
# column and the overview bar, and the status line is the last thing to catch
# up.  A 3-second checkpoint here caught the status bar still reading 120330.
K ctrl+Home
CP "Go to start" 10

# --- 17. Type block ----------------------------------------------------------
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.25
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# One operation, the way the script allows for editors that have a project-wide
# replace.  Ctrl+H opens the Search dialog on its File Search tab with the
# scope already set to Workspace and the file pattern already `*`, so the search
# is unscoped exactly as VS Code's is - LEGACY_SKU appears nowhere but the three
# files under src/legacy/, so unscoped and scoped are the same twelve matches.
#
# "Replace..." leads to a second dialog that states the scope it is about to
# act on - "Replacing 12 matches in 3 files:" - and OK applies it.  Eclipse
# writes the three files to disk itself; there are no dirty editors left behind,
# which is the trap that cost Sublime its project-wide path.
K ctrl+h
sleep 6
T 'LEGACY_SKU'
sleep 3
X mousemove 725 599 click 1            # Replace...
sleep 10
T 'ARCHIVE_SKU'
sleep 2
X mousemove 934 529 click 1            # OK
CP "Global replace" 12

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
