#!/usr/bin/env bash
# Drive Neovim through applications/codeeditors/script.md while record-macro.py
# records the input.  One block per script line, each ending in a checkpoint.
#
# Neovim lives in a terminal, so "the application" here is a full-screen xterm with
# a bash prompt in /root/project, and block 1 is typing `vim` at that prompt.
# Everything after it is sent to the terminal.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=xterm
# 1440x900, even though a hand-launched xterm settles at 1435x897.
#
# xterm rounds its own window down to whole character cells, so fluxbox's
# [Dimensions] {1440 900} becomes 1435x897 - 159 columns by 47 rows at DejaVu
# Sans Mono 11.  But record-macro.py and position-window.sh both call
# `xdotool windowsize`, which goes round the size hints, and xterm accepts the
# extra few pixels as margin.  So the window is 1435x897 while measuring by hand
# and 1440x900 in every recording and every replay - the two paths that matter,
# and they agree with each other.
WIN_W=1440
WIN_H=900
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 40 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Anywhere in the terminal is inert - xterm has no tooltips, no hover states and
# a non-blinking cursor - but the pointer still has to be somewhere fixed, or it
# sits wherever the last click left it and covers a character cell.
park() { X mousemove 1200 850; sleep 1; }

# The settle time before each capture is generous on the large-file blocks, and
# that is not padding.  xterm repaints a 159x47 grid lazily, and on a loaded
# host the repaint after `:120000` arrived more than six seconds late - so the
# capture showed the top of the file with the command still on the command
# line, while vim had in fact already jumped.  The check passed anyway at RMSE
# 0.126, because one screenful of fixed-width catalogue lines looks very much
# like another; only the ruler in the corner said otherwise.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=${WIN_W}"*"HEIGHT=${WIN_H}"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Neovim ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has launched the xterm.  The click is for focus - fluxbox
# gives the window focus, but a real click is the only way to be certain, and
# `xdotool windowfocus` would not be recorded.
sleep 8
X mousemove 700 400 click 1
sleep 2
T 'nvim'
K Return
CP "Load app" 6

# --- 2. Open file ------------------------------------------------------------
# The shell started in /root/project, so the path in the script is the path
# typed here.
T ':e src/price_calculator.py'; K Return
CP "Open file" 4

# --- 3. Scroll to function ---------------------------------------------------
# Ctrl+F is a whole screen forward.  Two of them put the top of the window at
# ~line 92 with `def calculate_total` in view.  Neovim will not scroll the cursor
# off screen, so unlike the GUI editors the cursor moves too - which is fine
# here, because it lands ABOVE line 110 and the search in the next block still
# finds the first `tax_rate` in the file.
K ctrl+f; sleep 1
K ctrl+f
CP "Scroll to function" 3

# --- 4. Find identifier ------------------------------------------------------
T '/tax_rate'; K Return
CP "Find identifier" 3

# --- 5. Select line ----------------------------------------------------------
# n advances to the next match - the `tax_rate` in `tax = subtotal * tax_rate` -
# and V selects that whole line linewise.
K n; sleep 1
K V
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
# y yanks the linewise selection and drops back to normal mode; p puts it after
# the current line.  Two keystrokes where the GUI editors need four, because a
# linewise register knows it is a line.
K y; sleep 1
K p
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Once.  The put is a single change, so unlike VS Code and IntelliJ - where the
# Return and the paste are separate undo stops - one `u` is the whole of it.
K u
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
T ':%s/tax_rate/vat_rate/g'; K Return
CP "Replace all" 3

# --- 9. Undo replace ---------------------------------------------------------
K u
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# O opens a line above and enters insert mode with the indent of the line below,
# so the comment lands at four columns - the same as VS Code, and unlike
# IntelliJ, which pulls a Python line comment out to column 0.
T '/return subtotal + tax'; K Return; sleep 2
K O; sleep 1
T '# benchmark complete'; sleep 1
K Escape
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
T ':w'; K Return
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
# :bd unloads the buffer, :e loads it again.  Vim's viminfo puts the cursor back
# on line 118 - the inserted comment - so the line is on screen without any
# navigation, the same as VS Code.
T ':bd'; K Return; sleep 2
T ':e src/price_calculator.py'; K Return
CP "Reopen file" 4

# --- 13. Open large file -----------------------------------------------------
T ':e src/component_library.py'; K Return
CP "Open large file" 22

# --- 14. Go to line ----------------------------------------------------------
T ':120000'; K Return
CP "Go to line" 10

# --- 15. Page down -----------------------------------------------------------
# 42 lines a screen here, against 39 in VS Code - the terminal has no tab bar,
# no breadcrumb and no status bar of its own to pay for.
for _ in $(seq 1 10); do K ctrl+f; sleep 0.4; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
T 'gg'
CP "Go to start" 8

# --- 17. Type block ----------------------------------------------------------
K i; sleep 1
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.25
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
K Escape
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# :argdo is Neovim's project-wide replace, so this is one operation rather than
# three file-by-file edits.
#
# :set hidden is redundant in Neovim - 'hidden' has been on by default since
# 0.6 - and is sent anyway, so this block is the same sequence of keystrokes in
# both terminal editors.  In Vim it is load-bearing: without it :args refuses to
# abandon the unwritten component_library.py buffer with E37.  `| update` writes
# each file only if the substitution changed it.
#
# The trailing Return answers Neovim's "Press ENTER or type command to continue" -
# :argdo prints a line per file, which overflows the single-line message area.
T ':set hidden'; K Return; sleep 1
T ':args src/legacy/*.py'; K Return; sleep 3
T ':argdo %s/LEGACY_SKU/ARCHIVE_SKU/g | update'; K Return; sleep 5
K Return
CP "Global replace" 5

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
