#!/usr/bin/env bash
# Drive Android Studio through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# Android Studio is IntelliJ IDEA with Google's plugins on top, so the key
# bindings, the in-editor find bar and the Replace in Files dialog are the same
# ones ../intellij/drive-scenario.sh drives, and the same find/replace history
# trap applies.  What differs is block 1: two dialogs instead of four, and a
# third click to put the What's New panel away.
#
# THE WHAT'S NEW PANEL IS CLOSED IN BLOCK 1
#
# Studio opens with it filling the right third of the window, which left the
# editor about 400 px wide - and at that width the in-editor find and replace
# bars have nowhere to draw their text FIELDS.  They rendered at zero width, so
# no reference screenshot could show what had been typed into them, in an IDE
# that shares one find/replace history across the in-editor bar and the Replace
# in Files dialog.  That is exactly the combination that produced IntelliJ's
# `vat_rateARCHIVE_SKU` corruption with all eighteen checks passing.
#
# Closing it is a click, in the recording, costing real time - not a setting
# written behind the benchmark's back.  With the panel gone the fields are
# visible and every screenshot from block 4 on proves its own input.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
# Matched on TITLE, not class.  Android Studio maps a shaped "Content window"
# carrying the same WM_CLASS as the frame and LARGER than it (1442x927 against
# 1440x900), and both replay.py and check-image.sh take the largest match - so a
# class match screenshots the helper instead of the editor.  The frame is titled
# "project - <file>", the helper "Content window".
TITLE=project
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Blank space in the project tree, below the last entry.  Not the editor, where
# hovering code raises documentation and gutter popups.
park() { X mousemove 250 600; sleep 1; }

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --name '${TITLE}' | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Android Studio ==="

# --- 1. Load app -------------------------------------------------------------
# Two dialogs, not IDEA's four: Google asks about usage statistics where
# JetBrains asks about the user agreement, the data sharing AND the agreement's
# Continue button.  There is no SDK setup wizard, because the project directory
# is passed on the command line and Studio opens it directly.
#
# Measured cold: the consent dialog is up within 10s of exec, the trust dialog
# within 10s of the consent click, and the IDE is pixel-stable 20s after Trust
# Project.  The sleeps below are those numbers with margin.
#
# Both dialogs report the frame's WM_CLASS, so pin-windows.sh puts them at 0,0
# undecorated - which is what makes these coordinates stable rather than subject
# to fluxbox's cascade placement.
sleep 20
X mousemove 288 287 click 1     # "Help improve Android Studio" -> Don't send
sleep 15
X mousemove 1076 865 click 1    # "Trust and Open Project 'project'?" -> Trust Project
sleep 30
# The What's New tool window's Hide button.  It is only painted while the
# pointer is over the tool window header, so the move and the click are separate
# with a pause between them - a single mousemove-and-click lands before the
# button has drawn itself and hits the header instead.
X mousemove 1377 61; sleep 2
X click 1
CP "Load app" 8

# --- 2. Open file ------------------------------------------------------------
# Go to File ranks the exact filename above tests/test_price_calculator.py, so
# the plain name is unambiguous - unlike VS Code's quick open, which needs the
# directory prefix.
K ctrl+shift+n; sleep 2
T 'price_calculator.py'; sleep 3
K Return
CP "Open file" 6

# --- 3. Scroll to function ---------------------------------------------------
# Wheel at 950,450, the same place IntelliJ uses - with the What's New panel
# gone the editor is full width and the two IDEs agree again.
#
# The wheel rather than PageDown because it moves the viewport without moving
# the caret, leaving the caret on line 1 so the find in the next block lands on
# the first `tax_rate` in the file.  3 lines per click, 30 clicks -> top line 99.
X mousemove 950 450
for _ in $(seq 1 30); do X click 5; sleep 0.05; done
CP "Scroll to function" 4

# --- 4. Find identifier ------------------------------------------------------
# With the What's New panel closed the find bar has room for its text field, so
# `tax_rate` and the 1/4 counter are both in the reference image.  They were not
# before: at 400 px the fields rendered at zero width and the screenshots could
# not show what had been typed.
K ctrl+f; sleep 2
T 'tax_rate'
CP "Find identifier" 4

# --- 5. Select line ----------------------------------------------------------
# Return advances to match 2 of 4 - the `tax_rate` in `tax = subtotal *
# tax_rate`.  Escape closes the find bar with the match still selected; Home is
# smart-home, so it stops at the first non-whitespace character.
K Return; sleep 1
K Escape; sleep 1
K Home; sleep 1
K shift+End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
K ctrl+c; sleep 1
K End; sleep 1
K Return; sleep 1
K ctrl+v
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice: the Return and the paste are separate undo stops, and one Ctrl+Z leaves
# an empty indented line behind.
K ctrl+z; sleep 1
K ctrl+z
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# The in-editor replace bar's "Replace All" button, at 993,143 - within a couple
# of pixels of IntelliJ's, now that both editors are full width.
#
# Ctrl+A before typing into any field, here and in block 18.  Android Studio
# inherits IDEA's shared find/replace history: it pre-fills both the in-editor
# bar and the Replace in Files dialog from it, but only selects the text in the
# SEARCH field.  Block 18's dialog came up pre-filled with `return subtotal +
# tax` and `vat_rate` from blocks 10 and 8 - so without the explicit select-all,
# `ARCHIVE_SKU` would be appended to `vat_rate` and the project-wide replace
# would write `vat_rateARCHIVE_SKU` into all three files.  That is exactly the
# corruption IntelliJ shipped once, and every screenshot check passed while it
# did.
K ctrl+r; sleep 2
K ctrl+a; T 'tax_rate'; sleep 2
K Tab; sleep 1
K ctrl+a; T 'vat_rate'; sleep 2
X mousemove 993 143 click 1
CP "Replace all" 4

# --- 9. Undo replace ---------------------------------------------------------
# Escape first, or the Ctrl+Z undoes the text in the replace field.  Once:
# Studio groups a Replace All into a single undo.
K Escape; sleep 1
K ctrl+z
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# Ctrl+Alt+Return is "Start New Line Before Current".  Studio then pulls the `#`
# out to column 0 as it types - IDEA's convention for a line comment, and a real
# difference from VS Code, which indents to match.  The ground-truth check
# records the column rather than insisting on one.
K ctrl+f; sleep 1
T 'return subtotal + tax'; sleep 3
K Escape; sleep 1
K ctrl+alt+Return; sleep 2
T '# benchmark complete'
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
K ctrl+s
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
# The tab's close button, at 820,60.  NOT Ctrl+F4, which is IDEA's documented
# "close tab" and which fluxbox swallows - on IntelliJ it closed the whole frame
# and left the IDE running with no window at all.
X mousemove 820 60 click 1; sleep 3
K ctrl+shift+n; sleep 2
T 'price_calculator.py'; sleep 3
K Return
CP "Reopen file" 6

# --- 13. Open large file -----------------------------------------------------
# Studio draws a banner across the top of the editor - "The file size (10.01 MB)
# exceeds the configured limit" - and turns code insight off for the file.  The
# banner is one row tall and shifts every line below it down, which is fine
# because it is there in the reference image too.
#
# Measured cold: pixel-stable from 40s.
K ctrl+shift+n; sleep 2
T 'component_library.py'; sleep 3
K Return
CP "Open large file" 45

# --- 14. Go to line ----------------------------------------------------------
# Ctrl+G opens "Go to Line:Column" as a SEPARATE TOP-LEVEL WINDOW - 345x131,
# its own FocusProxy, its own WM_CLASS entry.  That matters twice over.
#
# It is why the first recording of this editor is worthless from here on.  The
# popup opened and never took the digits, so blocks 14 to 18 all ran against a
# frozen IDE with the caret still at 1:1 - and because the popup overlaps the
# frame, every screenshot from 14 to 18 came out byte-for-byte identical, with a
# black rectangle where the popup sits.  Five checkpoints, one image, eighteen
# passes.  IntelliJ and PyCharm did the same thing.
#
# The cause is the checkpoint immediately before it, and it is the same one that
# breaks block 17.  timed_xmacro.py raises and `xdotool windowfocus`es the frame
# to take each screenshot; on a Java application that clears Swing's focus
# owner.  Ctrl+G still reaches the IDE - it is a bound action, and the action
# system dispatches it - so the popup OPENS.  But with no focus owner to hand
# focus on from, X input focus stays on the frame:
#
#   $ xdotool getwindowfocus getwindowname
#   project - component_library.py          <- not "Go to Line:Column"
#
# So the digits go nowhere, Return falls through to the editor, and the popup
# sits there over the file for the rest of the run.  Click into the editor first
# and focus transfers properly; measured both ways, ten times.
#
# NO Ctrl+A HERE.  Selecting-all first looks like the safe way to clear a
# pre-filled field, and it is the single most dangerous thing this file could
# do: if focus is ever not in the popup, Ctrl+A selects all 337,537 lines of the
# open file and the Return that follows replaces every one of them with a
# newline.  That is not hypothetical - it is what the second recording of this
# editor did, and check-result.sh caught it reading "on disk: 1 bytes, 1 lines".
# The popup pre-selects its own contents anyway.
X mousemove 900 400 click 1; sleep 2
K ctrl+g; sleep 5
T '120000'; sleep 2
K Return
CP "Go to line" 10

# --- 15. Page down -----------------------------------------------------------
# 35 lines a screen: L120000 -> L120350.
for _ in $(seq 1 10); do K Next; sleep 0.5; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
K ctrl+Home
CP "Go to start" 8

# --- 17. Type block ----------------------------------------------------------
# THE CLICK IS LOAD-BEARING, AND IT IS THE SUBTLEST THING IN THIS DIRECTORY.
#
# Every checkpoint screenshots the frame, and timed_xmacro.py raises and
# `xdotool windowfocus`es it first.  On a Java application that resets Swing's
# focus owner: no text component holds focus afterwards.  IntelliJ still
# dispatches keystroke-BOUND ACTIONS from there - Return, Page Down, Ctrl+Home,
# Ctrl+G all reach the selected editor through the action system - but a plain
# printable character goes through TypedAction, which needs a focused editor
# component, and is dropped in silence.
#
# This is the only block in the scenario that types directly into the editor
# after a checkpoint.  Every other typing block opens something first
# (Ctrl+Shift+N, Ctrl+F, Ctrl+R, Ctrl+Shift+R) and the popup takes focus
# properly, which is why they were all fine and only this one was not.
#
# Without the click the block types ten lines and lands ten EMPTY ones: the
# Returns arrive, the characters do not.  The file grows by exactly ten bytes,
# the line count reads 337547 against a seeded 337537 - which looks like success
# from a distance and is why it survived - and the screenshot shows ten blank
# rows.  check-result.sh now asserts the sentinel lines instead of printing a
# count, so this cannot pass quietly again.
#
# Ctrl+Home after the click because the click puts the caret where it landed.
X mousemove 900 400 click 1; sleep 2
K ctrl+Home; sleep 1
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.3
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# Entirely keyboard-driven.  Alt+A is "Replace All" on the Replace in Files
# dialog - needed because the dialog is taller than the 900 px screen, so its
# buttons are below the bottom edge and cannot be clicked.  Return then answers
# the "Replace 12 occurrences across 3 files?" confirmation, which IS the
# default button here.
#
# The dialog's "File mask:" box shows a greyed `*.java`, but its checkbox is
# unticked so no mask is applied and the search is project-wide - which is the
# scope the script asks for, since LEGACY_SKU appears nowhere but the three
# files under src/legacy/.
K ctrl+shift+r; sleep 5
K ctrl+a; T 'LEGACY_SKU'; sleep 5
K Tab; sleep 1
K ctrl+a; T 'ARCHIVE_SKU'; sleep 4
K alt+a; sleep 5
K Return
CP "Global replace" 10

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
