#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
printf "\n  Text attributes\n\n"
for _ in $(seq 1 30000); do
  printf "  \033[1m%-22s\033[0m  1\n" "bold"
  printf "  \033[2m%-22s\033[0m  2\n" "dim"
  printf "  \033[3m%-22s\033[0m  3\n" "italic"
  printf "  \033[4m%-22s\033[0m  4\n" "underline"
  printf "  \033[7m%-22s\033[0m  7\n" "reverse"
  printf "  \033[9m%-22s\033[0m  9\n" "strikethrough"
  printf "  \033[21m%-22s\033[0m  21\n" "double underline"
  printf "  \033[53m%-22s\033[0m  53\n" "overline"
  printf "  \033[1;4m%-22s\033[0m  1;4\n" "bold underline"
  printf "  \033[1;7m%-22s\033[0m  1;7\n" "bold reverse"
  printf "  \033[4;3m%-22s\033[0m  4;3\n" "italic underline"
  printf "  \033[2;3m%-22s\033[0m  2;3\n" "dim italic"
done
printf "BLOCK %s %s\n" 03 attributes >> /tmp/parrot-term.log
