#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
printf "\n  True colour\n\n"
for _ in $(seq 1 9); do
  for band in $(seq 0 47); do
    for x in $(seq 0 239); do
      r=$(( (x * 255) / 239 ))
      g=$(( (band * 255) / 47 ))
      b=$(( 255 - r ))
      printf "\033[48;2;%d;%d;%dm \033[0m" "$r" "$g" "$b"
    done
    printf "\n"
  done
done
printf "BLOCK %s %s\n" 05 colours-true >> /tmp/parrot-term.log
