#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
printf "\n  256 colours\n\n"
for _ in $(seq 1 100); do
  for row in $(seq 0 15); do
    for col in $(seq 0 15); do
      n=$((row * 16 + col))
      printf "\033[48;5;%dm  \033[0m" "$n"
    done
    printf "\n"
  done
  printf "\n"
done
printf "BLOCK %s %s\n" 04 colours-256 >> /tmp/parrot-term.log
