#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
for _ in $(seq 1 325); do
  ls --color=always -R $(dirname "$0")/tree
done
printf "BLOCK %s %s\n" 11 ls-tree >> /tmp/parrot-term.log
