#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
printf "\033[2J"
for i in $(seq 1 65); do
  for row in $(seq 1 20); do
    bar=$(printf "%0.s#" $(seq 1 $(( (i % 40) + 1 ))))
    printf "\033[%d;1H\033[K  row %02d   iteration %03d   %s" "$row" "$row" "$i" "$bar"
  done
done
printf "\033[22;1H\n"
printf "BLOCK %s %s\n" 08 redraw >> /tmp/parrot-term.log
