#!/bin/bash
# Generated by generate_corpus.py - do not edit.
set -u
LOG=/tmp/parrot-term.log
fail=0
if [ ! -f "$LOG" ]; then echo "  FAIL no session log at $LOG"; echo "RESULT FAIL"; exit 1; fi
if grep -qx "BLOCK 02 plain" "$LOG"; then echo "  ok   block 02 plain ran"; else echo "  FAIL block 02 plain left no log line"; fail=1; fi
if grep -qx "BLOCK 03 attributes" "$LOG"; then echo "  ok   block 03 attributes ran"; else echo "  FAIL block 03 attributes left no log line"; fail=1; fi
if grep -qx "BLOCK 04 colours-256" "$LOG"; then echo "  ok   block 04 colours-256 ran"; else echo "  FAIL block 04 colours-256 left no log line"; fail=1; fi
if grep -qx "BLOCK 05 colours-true" "$LOG"; then echo "  ok   block 05 colours-true ran"; else echo "  FAIL block 05 colours-true left no log line"; fail=1; fi
if grep -qx "BLOCK 06 unicode" "$LOG"; then echo "  ok   block 06 unicode ran"; else echo "  FAIL block 06 unicode left no log line"; fail=1; fi
if grep -qx "BLOCK 07 boxes" "$LOG"; then echo "  ok   block 07 boxes ran"; else echo "  FAIL block 07 boxes left no log line"; fail=1; fi
if grep -qx "BLOCK 08 redraw" "$LOG"; then echo "  ok   block 08 redraw ran"; else echo "  FAIL block 08 redraw left no log line"; fail=1; fi
if grep -qx "BLOCK 09 longlines" "$LOG"; then echo "  ok   block 09 longlines ran"; else echo "  FAIL block 09 longlines left no log line"; fail=1; fi
if grep -qx "BLOCK 10 seq" "$LOG"; then echo "  ok   block 10 seq ran"; else echo "  FAIL block 10 seq left no log line"; fail=1; fi
if grep -qx "BLOCK 11 ls-tree" "$LOG"; then echo "  ok   block 11 ls-tree ran"; else echo "  FAIL block 11 ls-tree left no log line"; fail=1; fi
sel="$(xclip -o -selection primary 2>/dev/null | tr -d "\n" | head -c 200)"
if [ -n "$sel" ]; then echo "  ok   block 14 left a PRIMARY selection (${#sel} chars)"; else echo "  FAIL block 14 left no PRIMARY selection"; fail=1; fi
n=$(grep -c "^BLOCK " "$LOG")
if [ "$n" -eq 10 ]; then echo "  ok   10 command blocks logged"; else echo "  FAIL $n command blocks logged (want 10)"; fail=1; fi
if [ "$fail" -eq 0 ]; then echo "RESULT PASS"; else echo "RESULT FAIL"; fi
