#!/usr/bin/env bash
# Drive Element Desktop through applications/chatclients/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowraise`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THE RULES THIS FILE IS BUILT AROUND, all measured:
#
#   1. Never click a room in the room list. Element sorts by recent activity, so
#      the order moves as the scenario touches rooms. Ctrl+K takes a name.
#
#   2. A dialog closing means NOTHING. Element's upload and its invite both have
#      a second confirmation step, and skipping either leaves the server with no
#      event while the UI looks like it worked. Same for nheko's upload. Every
#      mutating block here was verified with matrix-truth.py, not by eye.
#
#   3. The context menu opens with React already focused, so Reply is ONE Down.
#      Two Downs is "Reply in thread", which opens a side panel and silently
#      changes the timeline width for every coordinate after it.
#
#   4. A window is not a painted window. The first recording of Element was
#      thrown away because of this: `element-desktop` mapped its window within
#      seconds and then sat on its loading spinner for FIVE MINUTES on a
#      freshly built container, so blocks 1-6 were recorded against a white
#      screen and the sign-in keystrokes went nowhere. Every guard in the file
#      passed - there was one window, and it was 1440x900. Hence wait_paint()
#      below, and the size check in CP(): a real Element screen is >1 MB of
#      PNG, the loading spinner is 2.4 kB.
set -euo pipefail

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
RCLICK() { X mousemove "$1" "$2"; sleep 0.4; X click 3; }
WHEEL()  { X mousemove "$1" "$2"; sleep 0.4; for _ in $(seq 1 "$3"); do X click 5; sleep 0.3; done; }

# Open a room by name through the spotlight. Immune to the room list reordering,
# and the only sane way to reach Parrot Echo and Parrot Firehose, which sit far
# down a 66-room list.
ROOM() { K ctrl+k; sleep 2; T "$1"; sleep 3; K Return; sleep "${2:-14}"; }

# Park the pointer somewhere inert before every capture. Element shows a hover
# action bar on whichever message is under the pointer, which would be baked
# into the reference image and would then have to reappear in exactly the same
# place on replay.
#
# 900,300 is over timeline text in every room the run visits. It DOES raise the
# hover bar, so the parked position must be identical at record and replay time
# - which it is, because this function is the only thing that moves the pointer
# before a capture.
park() { X mousemove 900 300; sleep 1; }

# The size of a full-screen PNG, in bytes. `import` is a passive X client - it
# reads the root window and sends no input event - so calling it mid-recording
# does not put anything into the macro.
SHOT() { Q 'export DISPLAY=:99; import -window root /tmp/parrot-probe.png 2>/dev/null; stat -c %s /tmp/parrot-probe.png'; }

# Anything above this is a screen with content on it.
#
# THE THRESHOLD HAS TO SIT JUST ABOVE THE SPINNER, not somewhere in the middle.
# 200000 was tried first and warned on all 23 checkpoints, because the only
# screen in the run with a photograph on it is the welcome screen:
#
#   loading spinner                       ~2.4 kB
#   sign-in form, room list, timeline    99-170 kB
#   welcome screen (photo background)     ~1.88 MB
#
# Flat UI compresses two orders of magnitude better than the photo, so a
# threshold picked off the welcome screen condemns every real screen after it.
PAINTED=30000

# Block until the display actually has Element on it, rather than guessing with
# a sleep. Aborts the run instead of driving a screen that is not there: a
# recording made against the loading spinner looks successful in every log line
# and is worthless.
wait_paint() {
    local limit="${1:-420}" waited=0 sz
    while (( waited < limit )); do
        sz="$(SHOT)"
        if [[ "${sz:-0}" -gt "$PAINTED" ]]; then
            echo "  [paint] first painted frame after ${waited}s"
            return 0
        fi
        sleep 5; waited=$(( waited + 5 ))
    done
    echo "  FATAL: nothing painted after ${limit}s - the app never came up" >&2
    exit 1
}

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The recorder captures `xdotool search --onlyvisible --class element | head -n1`
# and raises and focuses that window first. Two things make the assertion below
# the right one for Element:
#
#   * `--class element` is an unanchored regex, so it ALSO matches the file
#     chooser's "element-desktop". The count check catches that.
#   * The file chooser is 1124x822, not 1440x900, so unlike nheko's - which is
#     1440x900 and indistinguishable - the geometry check catches it too.
#
# Element's member list and image viewer are in-window panels rather than
# separate windows, so they never trip this.
CP() {
    sleep "${2:-4}"
    park
    n="$(Q "xdotool search --onlyvisible --class element | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class element | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1 - the file chooser is probably still open"
    sz="$(SHOT)"
    [[ "${sz:-0}" -gt "$PAINTED" ]] || echo "  WARNING: '$1' would capture a blank or loading screen (${sz}B)"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Element Desktop ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `element-desktop` - the wrapper from
# install.sh, which drops to uid 1001, starts a session bus and unlocks a secret
# service. Without all three Element either crash-loops with no window or stops
# on an "unsupported keyring" modal; see MEASUREMENTS.md.
#
# The head time here is deliberately the SAME as nheko's - 20 s in
# record-session.sh, 25 s here, 5 s in CP - because it is measured time. A
# client given a longer head sits idle for longer and its run costs more energy
# for reasons that have nothing to do with the client. wait_paint() is inserted
# rather than added to: on a freshly built container Element paints in 7 s, so
# it normally returns immediately and the head stays 50 s.
wait_paint
sleep 25
CP "Load app" 5

# --- 2. Sign in --------------------------------------------------------------
# Element asks for the HOMESERVER FIRST and defaults to matrix.org, so the
# server has to be changed before any credential is typed. This is the other
# route script.md allows for - nheko only reveals a server field after
# autodiscovery fails.
CLICK 720 322; sleep 5                       # Sign in
CLICK 999 239; sleep 5                       # Edit, next to matrix.org
# The dialog opens with "Other homeserver" selected AND its field focused, so
# there is nothing to click before typing.
T 'http://matrix.parrot.test:8008'; sleep 3
CLICK 714 573; sleep 10                      # Continue
# The form is now Username/Password with Username already focused.
T 'parrot'; sleep 1
CLICK 822 406; sleep 1                       # Password
T 'parrot'; sleep 1
CLICK 822 502                                # Sign in
CP "Sign in" 15

# --- 3. Initial sync ---------------------------------------------------------
# The measurement this block exists for: 8000 messages, 66 rooms and a
# 509-member room arriving at once.
#
# THREE PROMPTS, AND THEY ARRIVE ONE AFTER ANOTHER. Each appears only once the
# previous is gone, and the second did not appear until several seconds after
# the room list had finished populating - long after the block looks done. A
# prompt still on screen at the checkpoint is baked into this reference image
# and every one after it, so each dismissal gets a generous settle.
sleep 40
CLICK 190 192; sleep 8                       # Back up your chats -> Dismiss
CLICK 248 152; sleep 8                       # Help improve Element -> No
CLICK 751 98;  sleep 8                       # Introducing Sections -> Ok
CP "Initial sync" 12

# --- 4. Open busy room -------------------------------------------------------
ROOM 'Aurora Release' 20
CP "Open busy room" 8

# --- 5. Scroll back ----------------------------------------------------------
X mousemove 900 400; sleep 1
for _ in $(seq 1 10); do K Prior; sleep 2; done
CP "Scroll back" 8

# --- 6. Jump to live ---------------------------------------------------------
# `End` does NOT do this - measured. The composer holds focus, so End is a
# text-cursor key and never reaches the timeline. nheko behaves identically.
CLICK 1392 786
CP "Jump to live" 10

# --- 7. Open member list -----------------------------------------------------
# An in-window panel, not a separate window - so this one could be checkpointed
# with the panel open, unlike nheko's. It is closed first anyway, so that the
# block boundary means the same thing in both clients: script.md ends this block
# by closing the list.
CLICK 1400 31; sleep 12                      # the member count in the header
CLICK 1410 31                                # close the panel
CP "Open member list" 5

# --- 8. Open photo room ------------------------------------------------------
# 400 images. They render only because the homeserver sets
# enable_authenticated_media false; see ../nheko/MEASUREMENTS.md.
ROOM 'Field Photos' 18
CP "Open photo room" 8

# --- 9. View image full size -------------------------------------------------
# An in-window lightbox. Closed before the checkpoint for the same
# block-boundary reason as block 7.
CLICK 683 705; sleep 10
CLICK 1408 31                                # close the lightbox
CP "View image full size" 5

# --- 10. Scroll thumbnails ---------------------------------------------------
X mousemove 900 400; sleep 1
for _ in $(seq 1 5); do K Prior; sleep 3; done
CP "Scroll thumbnails" 8

# --- 11. Filter room list ----------------------------------------------------
K ctrl+k; sleep 2
T 'windvane'
CP "Filter room list" 5

# --- 12. Open filtered room --------------------------------------------------
K Return; sleep 16
CP "Open filtered room" 6

# --- 13. Send message --------------------------------------------------------
# Element writes "Today" as the day separator rather than a date, so the RMSE
# floor from here on is the clock time only.
CLICK 900 857; sleep 2
T 'Thank you so much'; sleep 1
K Return
CP "Send message" 8

# --- 14. Reply to message ----------------------------------------------------
# ONE Down. Two is "Reply in thread" - measured, and it opens a side panel that
# changes the timeline width for everything after it.
RCLICK 660 696; sleep 3
K Down; sleep 1; K Return; sleep 4
T 'Agreed, going out today'; sleep 1
K Return
CP "Reply to message" 8

# --- 15. React to message ----------------------------------------------------
# TARGET THE ORIGINAL, NOT THE QUOTE. The reply just sent renders a quoted copy
# of the same text lower down; reacting to that attaches the reaction to the
# reply event instead, and only ground truth can tell the difference.
#
# React is the first menu item and is already focused, so Return opens the
# picker directly. Element offers a Quick Reactions row, so no search is needed.
RCLICK 660 611; sleep 3
K Return; sleep 4
CLICK 872 766                                # 👍 in Quick Reactions
CP "React to message" 8

# --- 16. Edit message --------------------------------------------------------
# The own-message menu inserts Edit as the fourth item: React, Reply, Reply in
# thread, Edit.
RCLICK 660 710; sleep 3
K Down; sleep 1; K Down; sleep 1; K Down; sleep 1
K Return; sleep 4
K ctrl+a; sleep 1
T 'Thank you so much indeed'; sleep 1
K Return
CP "Edit message" 8

# --- 17. Upload image --------------------------------------------------------
# ELEMENT DOES NOT SEND ON FILE SELECTION either. After Open, it shows a preview
# card with an Upload button, and without that second click the server receives
# nothing while the composer looks busy.
#
# THE CHOOSER OPENS ON "Recent", WHICH IS EMPTY ON A FRESH PROFILE. An earlier
# version of this block clicked the first row of the file list, which is what
# works by hand after the chooser has been used once - and on a recording, where
# the profile is always new, it selected nothing at all. Open then did nothing,
# the dialog closed, and the Upload click landed on the timeline. Ground truth
# showed three events from @parrot instead of four; the screenshots showed a
# perfectly ordinary room.
#
# So the path is typed, the same user action nheko's block 17 uses. Ctrl+L opens
# the GTK location bar.
#
# RETURN DOES NOT ACCEPT IT - measured, twice, with the path sitting correctly in
# the entry both times. The Open button does. That asymmetry is the whole reason
# this block is written with a click rather than a keystroke.
#
# The chooser is the first separate window of the run, so fluxbox's cascade puts
# it at 1,45 and it is 1124x822.
CLICK 1378 857; sleep 8                      # paperclip
K ctrl+l; sleep 2                            # location bar
T '/tmp/parrot.png'; sleep 2
CLICK 1075 821; sleep 6                      # Open - NOT Return
CLICK 876 644                                # Upload - the step that matters
CP "Upload image" 14

# --- 18. Echo round trip -----------------------------------------------------
ROOM 'Parrot Echo' 14
CLICK 900 857; sleep 2
T 'ping'; sleep 1
K Return
CP "Echo round trip" 12

# --- 19. Join room -----------------------------------------------------------
# Neater than nheko's: the spotlight offers "Join #parrot-lobby:parrot.test" as
# the preselected first result, so Return joins. No dialog.
K ctrl+k; sleep 2
T '#parrot-lobby:parrot.test'; sleep 5
K Return
CP "Join room" 16

# --- 20. Create room ---------------------------------------------------------
# ELEMENT DEFAULTS TO PRIVATE AND ENCRYPTED. Left alone this produces an
# invite-only E2EE room - not what script.md asks for, and not what nheko
# produced, which would make every later block a comparison of different work.
#
# Switching to Public removes the encryption toggle entirely and makes a Room
# address mandatory; nheko needed no alias.
CLICK 409 98;  sleep 3                       # +
CLICK 480 203; sleep 6                       # New room
T 'Parrot benchmark'; sleep 2
CLICK 719 415; sleep 3                       # visibility dropdown
CLICK 610 477; sleep 4                       # Public room
CLICK 600 513; sleep 2                       # Room address
T 'parrot-benchmark'; sleep 2
CLICK 866 648; sleep 14                      # Create room

# The invite, in THREE steps. The first Invite button does not invite - it opens
# a confirmation, and stopping there leaves the room with only @parrot in it.
CLICK 616 713; sleep 6                       # Invite to this room
T '@alice:parrot.test'; sleep 5
CLICK 480 350; sleep 3                       # the suggestion row
CLICK 1028 261; sleep 5                      # Invite -> opens the confirmation
CLICK 910 725                                # Invite -> actually sends it
CP "Create room" 12

# --- 21. Leave room ----------------------------------------------------------
# LEAVE IS BELOW THE FOLD. The room-info panel has to be scrolled before "Leave
# room" exists on screen, so this scrolls a fixed amount rather than assuming
# the item is visible.
ROOM 'Parrot Lobby' 14
CLICK 1327 31; sleep 6                       # room info
WHEEL 1280 700 5; sleep 3                    # scroll to the bottom of the panel
CLICK 1215 848; sleep 5                      # Leave room
CLICK 1000 521                               # confirm Leave
CP "Leave room" 12

# --- 22. Idle quiet ----------------------------------------------------------
ROOM 'Parrot Firehose' 18
sleep 60
CP "Idle quiet" 4

# --- 23. Idle receiving ------------------------------------------------------
# `drip` is the trigger: the bot posts drip 01..24, one every 5 s, scheduled
# against a fixed start so the burst does not drift.
CLICK 900 857; sleep 2
T 'drip'; sleep 1
K Return
sleep 130
CP "Idle receiving" 6

echo "=== driven ==="
