#!/usr/bin/env bash
# Drive PyCharm through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# PyCharm runs on its own defaults, so the first block is four clicks through the
# user agreement, the data-sharing prompt and the project-trust dialog before
# there is an editor at all.  Every landmark is in MEASUREMENTS.md.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
# Matched on TITLE, not class.  PyCharm maps a shaped "Content window" carrying the
# same WM_CLASS as the frame and *larger than the screen* (1442x927), and both
# replay.py and check-image.sh take the largest match - so a class match
# screenshots the helper instead of the editor.  The frame is titled
# "project - <file>", the helper "Content window".
TITLE=project
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }

# Blank space in the project tree, below the last entry.  Not the editor: IDEA
# runs on defaults, so hovering code raises documentation and gutter popups.
park() { X mousemove 250 600; sleep 1; }

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --name '${TITLE}' | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving PyCharm ==="

# --- 1. Load app -------------------------------------------------------------
# Four dialogs stand between a fresh install and an editor, at exactly the same
# coordinates as IntelliJ's - same platform, same dialogs.  All four are X
# windows sharing the frame's WM_CLASS, so pin-windows.sh puts them full-screen
# at 0,0, which is what makes these coordinates stable rather than subject to
# fluxbox's cascade placement.
#
# The settle afterwards is longer than IntelliJ's: PyCharm has real Python
# support, so it indexes the project and configures an interpreter, and says so
# in a second balloon - "Python 3.12 has been configured as a project
# interpreter" - below the JCEF one.
sleep 40
X mousemove 42 831 click 1      # "I confirm that I have read and accept ..."
sleep 3
X mousemove 1379 871 click 1    # Continue (disabled until the box is ticked)
sleep 8
X mousemove 1163 871 click 1    # DATA SHARING -> Don't Send
sleep 20
X mousemove 1076 865 click 1    # Trust and Open Project 'project'? -> Trust Project
sleep 75
# THE TRIAL TAB IS CLOSED HERE, AND IT IS NOT TIDINESS.
#
# PyCharm 2025.3 ships as one distribution with a licence trial, and it opens a
# "Trial" tab - an embedded JCEF browser - in the editor area some time after
# the project does.  How long is not fixed.  When it finally loads it TAKES
# FOCUS, and if that lands while a popup is open the popup is dismissed under
# it.  IntelliJ lost a whole recording to exactly that: the tab arrived during
# block 2, killed the Go to File popup mid-type, and the file was never opened.
#
# Middle click closes a tab, so this is one action.  Once the tab is gone it
# cannot steal focus again, and every tab coordinate below is measured with it
# already closed.  Android Studio has no equivalent - Google's build is free and
# never shows one.
X mousemove 700 63; sleep 2
X click 2
CP "Load app" 8

# --- 2. Open file ------------------------------------------------------------
# Go to File ranks the exact filename above tests/test_price_calculator.py, so
# the plain name is unambiguous here - unlike VS Code's quick open, which needs
# the directory prefix.
K ctrl+shift+n; sleep 2
T 'price_calculator.py'; sleep 3
K Return
CP "Open file" 5

# --- 3. Scroll to function ---------------------------------------------------
# Wheel, not PageDown: it moves the viewport without moving the cursor, which
# leaves the cursor on line 1 so the find in the next block lands on the first
# `tax_rate` in the file.  3 lines per click, 30 clicks -> top line 91.
X mousemove 950 450
for _ in $(seq 1 30); do X click 5; done
CP "Scroll to function" 3

# --- 4. Find identifier ------------------------------------------------------
K ctrl+f; sleep 2
T 'tax_rate'
CP "Find identifier" 3

# --- 5. Select line ----------------------------------------------------------
# Return advances to match 2 of 4 - the `tax_rate` in `tax = subtotal *
# tax_rate`.  Escape closes the find bar with the match still selected; Home is
# smart-home, so it stops at the first non-whitespace character.
K Return; sleep 1
K Escape; sleep 1
K Home; sleep 1
K shift+End
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
K ctrl+c; sleep 1
K End; sleep 1
K Return; sleep 1
K ctrl+v
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Twice, same as VS Code: the Return and the paste are separate undo stops, and
# one Ctrl+Z leaves an empty indented line behind.
K ctrl+z; sleep 1
K ctrl+z
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# The in-editor replace bar's "Replace All" button, at 996,135 - measured
# separately here rather than inherited from IntelliJ, because the buttons sit
# to the right of the match counter and therefore move with its width.  With the
# fields empty the counter reads "0 results" and the button is at 974; with
# `tax_rate` in the search field it reads "1/4" and the button is at 996.  It
# has to be measured in the state the driver actually clicks in.
#
# Ctrl+A before typing into any field, here and in block 18, and it is not
# defensive programming for its own sake.  IDEA shares its find/replace history
# between the in-editor bar and the Replace in Files dialog, and pre-fills both
# from it - but only selects the text in the SEARCH field.  Without the explicit
# select-all, block 18's `ARCHIVE_SKU` was appended to block 8's leftover
# `vat_rate`, so the project-wide replace ran with a replacement string of
# `vat_rateARCHIVE_SKU` and wrote that into all three files.
#
# Every screenshot check passed while it did so: the dialog looked identical,
# and the corruption was three files the reference images never show.  Only the
# ground-truth diff caught it.
K ctrl+r; sleep 2
K ctrl+a; T 'tax_rate'; sleep 1
K Tab; sleep 1
K ctrl+a; T 'vat_rate'; sleep 1
X mousemove 996 135 click 1
CP "Replace all" 4

# --- 9. Undo replace ---------------------------------------------------------
K Escape; sleep 1
K ctrl+z
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# Ctrl+Alt+Return is "Start New Line Before Current".  IDEA then pulls the `#`
# out to column 0 as it types - its own convention for a line comment, and a
# real difference from VS Code, which indents to match.  The ground-truth check
# records the column rather than insisting on one.
K ctrl+f; sleep 1
T 'return subtotal + tax'; sleep 3
K Escape; sleep 1
K ctrl+alt+Return; sleep 2
T '# benchmark complete'
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
K ctrl+s
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
# The tab's close button, at 898,63.  NOT Ctrl+F4, which is IDEA's documented
# "close tab" and which fluxbox swallows here - it closed the whole frame and
# left the IDE running with no window at all.
X mousemove 813 63 click 1; sleep 3
K ctrl+shift+n; sleep 2
T 'price_calculator.py'; sleep 3
K Return
CP "Reopen file" 5

# --- 13. Open large file -----------------------------------------------------
K ctrl+shift+n; sleep 2
T 'component_library.py'; sleep 3
K Return
CP "Open large file" 35

# --- 14. Go to line ----------------------------------------------------------
# Ctrl+G opens "Go to Line:Column" as a SEPARATE TOP-LEVEL WINDOW - 345x131,
# with its own FocusProxy - which overlaps the frame this scenario screenshots.
#
# The first recording of this editor is worthless from here on: the popup opened
# and never took the digits, so blocks 14 to 17 ran against a frozen IDE with
# the caret still at 1:1, and all four screenshots came out byte-for-byte
# identical with a black rectangle where the popup sits.  Four checkpoints, one
# image, eighteen passes.  IntelliJ and Android Studio did the same thing.
#
# The cause is the checkpoint immediately before it, and it is the same one that
# breaks block 17.  timed_xmacro.py raises and `xdotool windowfocus`es the frame
# to take each screenshot; on a Java application that clears Swing's focus
# owner.  Ctrl+G still reaches the IDE - it is a bound action, and the action
# system dispatches it - so the popup OPENS.  But with no focus owner to hand
# focus on from, X input focus stays on the frame:
#
#   $ xdotool getwindowfocus getwindowname
#   project - component_library.py          <- not "Go to Line:Column"
#
# So the digits go nowhere, Return falls through to the editor, and the popup
# sits there over the file for the rest of the run.  Click into the editor first
# and focus transfers properly.
#
# NO Ctrl+A HERE.  Selecting-all first looks like the safe way to clear a
# pre-filled field, and it is the single most dangerous thing this file could
# do: if focus is ever not in the popup, Ctrl+A selects all 337,537 lines of the
# open file and the Return that follows replaces every one of them with a
# newline.  Android Studio's second recording did exactly that - check-result.sh
# caught it reading "on disk: 1 bytes, 1 lines".  The popup pre-selects its own
# contents anyway.
X mousemove 900 400 click 1; sleep 2
K ctrl+g; sleep 5
T '120000'; sleep 2
K Return
CP "Go to line" 12

# --- 15. Page down -----------------------------------------------------------
for _ in $(seq 1 10); do K Next; sleep 0.5; done
CP "Page down" 9

# --- 16. Go to start ---------------------------------------------------------
K ctrl+Home
CP "Go to start" 9

# --- 17. Type block ----------------------------------------------------------
# THE CLICK IS LOAD-BEARING.
#
# Every checkpoint screenshots the frame, and timed_xmacro.py raises and
# `xdotool windowfocus`es it first.  On a Java application that resets Swing's
# focus owner: no text component holds focus afterwards.  PyCharm still
# dispatches keystroke-BOUND ACTIONS from there - Return, Page Down, Ctrl+Home,
# Ctrl+G all reach the selected editor through the action system - but a plain
# printable character goes through TypedAction, which needs a focused editor
# component, and is dropped in silence.
#
# This is the only block in the scenario that types directly into the editor
# after a checkpoint.  Every other typing block opens something first
# (Ctrl+Shift+N, Ctrl+F, Ctrl+R, Ctrl+Shift+R) and the popup takes focus
# properly, which is why they were all fine and only this one was not.
#
# Without the click the block types ten lines and lands ten EMPTY ones: the
# Returns arrive, the characters do not.  The file grows by exactly ten bytes,
# which looks like success from a distance.  check-result.sh now asserts the
# sentinel lines instead of printing a count.
#
# Ctrl+Home after the click because the click puts the caret where it landed.
#
# AND THE TYPING IS SLOWER HERE THAN ANYWHERE ELSE IN THE GROUP: 120 ms a
# character against everyone else's 45, with a full second between lines.  That
# is not padding, it is the smallest cadence the 2025.3 platform will accept
# without losing input on a 337,537-line file.  Measured on IntelliJ, which is
# the same platform and the same build number, both faster settings fail:
#
#   45 ms/char, 0.3 s between lines   six lines land, then it stops dead in the
#                                     middle of the seventh.  Every Return still
#                                     arrives, so the LINE COUNT comes out right
#                                     with empty lines at the bottom.
#   45 ms/char, 1.5 s between lines   every character lands and the RETURNS are
#                                     dropped instead, welding lines together.
#   120 ms/char, 1.0 s between lines  clean.
#
# So this block's number is NOT comparable with the other editors' - it contains
# a cadence chosen for the IDE rather than by it.  What IS comparable is that
# every other editor takes 45 ms/char into the same file without dropping a
# keystroke, and the 2025.3 JetBrains platform does not.  Android Studio, on the
# older 251 platform, also does not, and is still driven at 45 ms.
X mousemove 900 400 click 1; sleep 2
K ctrl+Home; sleep 1
while IFS= read -r line; do
    X type --delay 120 -- "$line"
    K Return
    sleep 1.0
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 7

# --- 18. Global replace ------------------------------------------------------
# Entirely keyboard-driven, which VS Code's equivalent is not.  Alt+A is
# "Replace All" on the Replace in Files dialog - needed because that dialog is
# 975 px tall on a 900 px screen, so its buttons are below the bottom edge and
# cannot be clicked.  Return then answers the "Replace 12 occurrences across 3
# files?" confirmation, which IS the default button here.
K ctrl+shift+r; sleep 4
K ctrl+a; T 'LEGACY_SKU'; sleep 4
K Tab; sleep 1
K ctrl+a; T 'ARCHIVE_SKU'; sleep 3
K alt+a; sleep 4
K Return
CP "Global replace" 8

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
