#!/usr/bin/env bash
# Drive GNU Emacs through applications/codeeditors/script.md while
# record-macro.py records the input.  One block per script line, each ending in
# a checkpoint.
#
# Emacs has a real X11 window, so it is driven as a windowed application rather
# than inside an xterm.  Its Meta bindings go through as Alt directly, unlike
# nano's - a GUI Emacs receives the modifier, where a terminal application only
# ever sees an ESC prefix.
#
# Do not edit this file while it is running: bash reads a script incrementally,
# and an edit that moves byte offsets corrupts the run in flight.
set -euo pipefail

REPO=/home/didi/code/parrot
CLASS=emacs
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -lc "$1" 2>/dev/null; }

T() { X type --delay 45 -- "$1"; }
K() { X key --clearmodifiers "$1"; }
# C-x prefixed commands, as two keystrokes with a gap - Emacs reads the prefix
# and then waits.
CX() { K ctrl+x; sleep 0.4; K "$1"; }

# The empty area below the mode line is the minibuffer, which changes; park over
# the far right of the toolbar strip instead, which never does.
park() { X mousemove 1300 46; sleep 1; }

CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving GNU Emacs ==="

# --- 1. Load app -------------------------------------------------------------
# The splash screen, with no dialog in front of it.  The frame title carries the
# container hostname - "GNU Emacs at 19a854b29d5e" - which changes every run,
# but pin-windows.sh strips the decorations so it never reaches a screenshot.
sleep 16
X mousemove 700 400 click 1
CP "Load app" 6

# --- 2. Open file ------------------------------------------------------------
# The wrapper starts Emacs with /root/project as its working directory, so
# `Find file:` offers ~/project/ and the path in the script is the path typed.
CX ctrl+f; sleep 2
T 'src/price_calculator.py'; K Return
CP "Open file" 4

# --- 3. Scroll to function ---------------------------------------------------
# C-v is a screenful forward.  Emacs moves point with it, but only as far as the
# top of the new screen, so point lands above line 110 and the search in the
# next block still finds the first `tax_rate` in the file.
K ctrl+v; sleep 1
K ctrl+v
CP "Scroll to function" 3

# --- 4. Find identifier ------------------------------------------------------
# Return exits isearch, leaving point on the match.
#
# Leaving isearch ACTIVE across the checkpoint does not work, and the failure is
# silent: the checkpoint sends Scroll_Lock, which ends isearch, so the next
# block's C-s starts a fresh search instead of repeating this one and point
# never advances.  The first recording duplicated line 110 rather than 117 and
# every later block was wrong from there - with all eighteen screenshots taken
# happily.
K ctrl+s; sleep 1
T 'tax_rate'; sleep 1
K Return
CP "Find identifier" 3

# --- 5. Select line ----------------------------------------------------------
# C-s C-s repeats the previous search string, so this advances to the
# `tax_rate` in `tax = subtotal * tax_rate` without retyping it; Return exits
# isearch leaving point on it.  Self-contained: it does not depend on any
# isearch state surviving the checkpoint.
#
# The region is then the WHOLE line including its newline: C-a to column 0,
# C-SPC to set the mark, C-n to the start of the next line.  That is what makes
# block 6 two keystrokes instead of four - a yank of a region that ends in a
# newline reinserts a whole line, so there is no Return to open a gap first and
# no auto-indent to fight.
K ctrl+s; sleep 1
K ctrl+s; sleep 1
K Return; sleep 1
K ctrl+a; sleep 1
K ctrl+space; sleep 1
K ctrl+n
CP "Select line" 3

# --- 6. Duplicate line -------------------------------------------------------
K alt+w; sleep 1
K ctrl+y
CP "Duplicate line" 3

# --- 7. Undo duplicate -------------------------------------------------------
# Once.  The yank is a single change - unlike VS Code, IntelliJ, Sublime and
# nano, which all need two because they open the line and fill it separately.
K ctrl+slash
CP "Undo duplicate" 3

# --- 8. Replace all ----------------------------------------------------------
# M-< first: query-replace works forward from point, and point is in the middle
# of the file after the undo.  `!` answers "replace all remaining" to the first
# prompt; the echo area then reads "Replaced 4 occurrences".
K alt+less; sleep 1
K alt+percent; sleep 2
T 'tax_rate'; K Return; sleep 1
T 'vat_rate'; K Return; sleep 2
K exclam
CP "Replace all" 3

# --- 9. Undo replace ---------------------------------------------------------
# Once - Emacs groups the whole query-replace into one undo boundary.  Verified
# by searching for `vat_rate` afterwards and getting "Failing I-search".  nano
# is the outlier here, needing one undo per occurrence.
K ctrl+slash
CP "Undo replace" 3

# --- 10. Insert comment ------------------------------------------------------
# C-o opens a line *after* point without moving point and without running
# electric-indent, so the four spaces are typed rather than inherited.  Using
# Return here instead would auto-indent in python-mode and then the typed indent
# would be added on top of it.
K ctrl+s; sleep 1
T 'return subtotal + tax'; sleep 2
K Return; sleep 1
K ctrl+a; sleep 1
K ctrl+o; sleep 1
T '    # benchmark complete'
CP "Insert comment" 3

# --- 11. Save file -----------------------------------------------------------
CX ctrl+s
CP "Save file" 3

# --- 12. Reopen file ---------------------------------------------------------
# C-x k prompts "Kill buffer (default price_calculator.py):"; Return accepts.
CX k; sleep 1
K Return; sleep 2
CX ctrl+f; sleep 2
T 'src/price_calculator.py'; K Return
CP "Reopen file" 4

# --- 13. Open large file -----------------------------------------------------
# Emacs is the only editor in this group that asks:
#
#   File component_library.py is large (9.5 MiB), really open? (yes, no,
#   literally, ?)
#
# large-file-warning-threshold defaults to 10,000,000 bytes and the generated
# module is 10,006,238 - six thousand bytes over the line.  `y` answers it:
# find-file passes offer-raw, so Emacs 29 puts this through
# read-multiple-choice rather than yes-or-no-p and a single character is enough.
#
# ABSOLUTE path, for the reason spelled out in block 18 - and this block is why
# that comment exists twice.  `find-file` offers the CURRENT BUFFER's directory
# as its default, and after block 12 that buffer is src/price_calculator.py.  A
# relative "src/component_library.py" therefore resolved to
# ~/project/src/src/component_library.py, which does not exist.  Emacs opened an
# empty buffer under that name, no large-file prompt appeared because there was
# no large file, and the `y` meant to answer it was typed INTO the buffer.
#
# Blocks 14 to 17 then ran against a one-character scratch buffer: go-to-line
# stayed on line 1, both page-downs did nothing, and the ten lines of block 17
# were typed into a file Emacs could not even auto-save - check 17 of the first
# recording is a *Warnings* window reading "Opening output file: No such file or
# directory, /root/project/src/src/#component_library.py#".  Every screenshot
# passed.
CX ctrl+f; sleep 2
T '/root/project/src/component_library.py'; K Return; sleep 3
K y
CP "Open large file" 28

# --- 14. Go to line ----------------------------------------------------------
K alt+g; sleep 0.5; K g; sleep 2
T '120000'; K Return
CP "Go to line" 10

# --- 15. Page down -----------------------------------------------------------
# 43 lines a screen: L120000 -> L120427.
for _ in $(seq 1 10); do K ctrl+v; sleep 0.4; done
CP "Page down" 8

# --- 16. Go to start ---------------------------------------------------------
K alt+less
CP "Go to start" 8

# --- 17. Type block ----------------------------------------------------------
while IFS= read -r line; do
    T "$line"
    K Return
    sleep 0.25
done < "${REPO}/applications/codeeditors/workspace/constants_block.txt"
CP "Type block" 6

# --- 18. Global replace ------------------------------------------------------
# File by file.  Emacs can do this across a directory with dired's `Q`, but that
# is a different user action - marking files in a dired buffer first - and the
# scenario's alternative path is the honest match for "open each file, replace
# within it and save".
#
# ABSOLUTE paths, and that is not tidiness.  `find-file` offers the *current
# buffer's* directory as its default, and by this point the current buffer is
# src/component_library.py - so a relative "src/legacy/orders.py" resolves to
# ~/project/src/src/legacy/orders.py, which does not exist.  Emacs then opens an
# empty buffer under that name, the query-replace finds nothing, and the save
# writes an empty file somewhere nobody looks.  The first recording did exactly
# that and left all three real files untouched, with every screenshot passing.
for f in orders pricing shipping; do
    CX ctrl+f; sleep 2
    T "/root/project/src/legacy/${f}.py"; K Return; sleep 3
    K alt+less; sleep 1
    K alt+percent; sleep 2
    T 'LEGACY_SKU'; K Return; sleep 1
    T 'ARCHIVE_SKU'; K Return; sleep 2
    K exclam; sleep 2
    CX ctrl+s; sleep 2
done
CP "Global replace" 6

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
