#!/usr/bin/env bash
# Drive Apache OpenOffice Calc through applications/spreadsheets/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md, measured by driving this sequence by hand
# and checking common/check-result.sh at the end of it (RESULT PASS, all 17
# assertions). Do not edit this file while it is running.
#
# THREE THINGS DIFFER FROM LIBREOFFICE CALC AND EACH ONE FAILS SILENTLY:
#
#   the Name Box APPENDS, so it is triple-clicked, not clicked;
#   the argument separator is `;` - a comma gives Err:508;
#   Ctrl+D is unbound, so Fill Down is Edit > Fill > Down.
#
# None of the three reports anything. Two of them leave a plausible screen.
set -euo pipefail

CLASS=openoffice
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }

# A menu item that opens a SUBMENU needs the pointer to arrive in two steps and
# then be clicked. A single mousemove onto the parent item does not highlight it
# and hovering never opens the submenu; measured on Edit > Fill and Data > Filter.
MCLICK() { X mousemove "$(( $1 + 20 ))" "$(( $2 - 9 ))"; sleep 1
           X mousemove "$1" "$2"; sleep 1; X click 1; }

# Select a range through the Name Box.
#
# TRIPLE-click, where LibreOffice Calc's driver single-clicks. AOO's Name Box
# does not select its contents on focus, so a single click and a typed address
# gives `A422A1:H20001` - not a reference, so Return does nothing at all and the
# selection silently stays where it was. Gnumeric fails the same way; the two
# StarOffice-lineage suites do NOT agree here. Measured both ways.
NAME() { X mousemove 65 88; sleep 0.4; X click --repeat 3 1; sleep 1; T "$1"; K Return; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - which would be baked into the reference screenshot.
park() { X mousemove 1100 700; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# AOO's dialogs carry the same res_class as the document window, and
# record-macro.py's capture takes `xdotool search --class ... | head -n1` - the
# FIRST match, not the largest. A checkpoint taken with one still up photographs
# the dialog. The assertion is the only thing that says so.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Apache OpenOffice Calc ==="

# --- 1. Load app -------------------------------------------------------------
# The recorder has launched `soffice -calc` and waited for the window; this waits
# for the first paint of the empty Untitled 1. Nothing to dismiss - install.sh's
# profile has already accepted the licence and turned the update check off. The
# Properties sidebar is open down the right-hand side, which is what a user gets,
# so it is left alone.
sleep 35
CP "Load app" 5

# --- 2. Open workbook --------------------------------------------------------
# AOO's own Open dialog, not GTK's. The File name field is EMPTY and has focus,
# so the path is typed straight in - no Ctrl+L, no click. Untitled 1 is REPLACED
# rather than added to, so there is still exactly one window.
#
# No recalculation prompt: the workbook is ODF 1.2 (which is why the generator
# writes 1.2 - AOO puts an "ODF Version Conflict" modal in front of 1.3) and
# install.sh seeds Calc/Formula/Load ODFRecalcMode.
K ctrl+o; sleep 6
T '/tmp/parrot-ledger.ods'; sleep 3
K Return
CP "Open workbook" 55

# --- 3. Jump to end ----------------------------------------------------------
K ctrl+End
CP "Jump to end" 10

# --- 4. Freeze the header ----------------------------------------------------
# Freezing lives under WINDOW here, not View - and it is relative to the cursor,
# so the cursor goes to A2 first.
K ctrl+Home; sleep 4
K Down; sleep 1
CLICK 284 9; sleep 2
CLICK 314 101
CP "Freeze the header" 5

# --- 5. Page through ---------------------------------------------------------
# Ends on A422 - 42 rows a press, against Calc's 41 and Gnumeric's 35.
for _ in $(seq 1 10); do K Next; sleep 0.6; done
CP "Page through" 5

# --- 6. Switch sheets --------------------------------------------------------
CLICK 150 868; sleep 5
CLICK 200 868; sleep 5
CLICK 101 868
CP "Switch sheets" 6

# --- 7. Sort -----------------------------------------------------------------
# The dialog pre-populates ONE key and pre-selects `Date` - so pressing OK sorts
# the sheet by date, perfectly and wrongly, without a word. Reading is the only
# column starting with R, so `r` on the focused list box picks it; that is one
# keystroke instead of a click on a dropdown that can reposition itself.
#
# No "does the range have headings?" prompt: AOO reads the header row from the
# selection and offers the column NAMES, which is itself the confirmation.
NAME 'A1:H20001'; sleep 8
CLICK 240 9; sleep 2
CLICK 261 77; sleep 6
K r; sleep 2
CLICK 762 655
CP "Sort" 40

# --- 8. Enter formula --------------------------------------------------------
# SEMICOLON, not comma. `=ROUND(E2*F2,2)` gives **Err:508** here - AOO 4.1 has no
# formula-separator option at all, where LibreOffice accepts either. The cell
# shows the error and the fill-down then propagates it 20,000 times; the run
# looks like it worked and the ground truth is what catches it.
NAME 'I2'; sleep 3
T '=ROUND(E2*F2;2)'; sleep 2
K Return
CP "Enter formula" 5

# --- 9. Fill down ------------------------------------------------------------
# **Ctrl+D IS UNBOUND.** It does nothing whatsoever - no beep, no message, the
# selection stays exactly as it was and only I2 holds a value. Edit > Fill has no
# accelerator of its own either, so this is the menu route, and Fill needs
# MCLICK because hovering does not open its submenu.
NAME 'I2:I20001'; sleep 8
CLICK 45 9; sleep 2
MCLICK 100 329; sleep 2
CLICK 265 327
CP "Fill down" 60

# --- 10. Total ---------------------------------------------------------------
# 74641377.67, to the cent the same as LibreOffice Calc. Gnumeric gives
# 74641377.60 from the same column; see the half-cent note in MEASUREMENTS.md.
NAME 'K1'; sleep 3
T '=SUM(I2:I20001)'; sleep 2
K Return
CP "Total" 12

# --- 11. Recalculate ---------------------------------------------------------
# Ctrl+Shift+F9, the hard recalculation. fluxbox's DEFAULT keys file grabs
# Control+F1..F12 for workspace switching and would eat this; pin-windows.sh
# writes a keys file with no keyboard bindings at all, which is why it does not.
NAME 'K1'; sleep 3
K ctrl+shift+F9
CP "Recalculate" 40

# --- 12. Filter --------------------------------------------------------------
# No keyboard shortcut, so Data > Filter > AutoFilter. The dropdown is a plain
# single-select list - (All), (Top 10), (Standard Filter...) then the six
# categories - so Turbine is one click: no checkbox tree, no search box, no
# "untick All" step. It is an override-redirect child of the document window
# rather than a top-level, so unlike Gnumeric's it cannot be photographed
# instead of the sheet.
NAME 'A1:H20001'; sleep 8
CLICK 240 9; sleep 2
MCLICK 260 97; sleep 2
CLICK 430 97; sleep 10
CLICK 436 127; sleep 4
CLICK 380 256
CP "Filter" 25

# --- 13. Clear filter --------------------------------------------------------
# (All) restores every row and LEAVES the filter buttons in place, as Gnumeric's
# does and unlike Calc's Ctrl+Shift+L. All three satisfy the script.
CLICK 436 127; sleep 4
CLICK 360 144
CP "Clear filter" 25

# --- 14. Format numbers ------------------------------------------------------
# Ctrl+1 opens Format Cells with Number already selected and **0 decimal
# places**, so the spinner is clicked twice and the Format code field reads
# `0.00` before OK. The `+` rather than typing into the field: a typed value in a
# spin box is what silently produced 1218 from 12 and 18 in the word processor
# group.
NAME 'E2:E20001'; sleep 8
K ctrl+1; sleep 10
CLICK 656 515; sleep 1.5
CLICK 656 515; sleep 2
CLICK 704 663
CP "Format numbers" 20

# --- 15. Replace all ---------------------------------------------------------
# **Ctrl+H does nothing.** AOO reaches Find *and* Replace through Ctrl+F; the
# same is true in Writer, so it is a suite-wide difference rather than a Calc
# one.
#
# No scope trap: "Current selection only" lives behind the collapsed More
# Options and is not ticked, where Calc auto-ticks it whenever a multi-cell range
# is selected. The single-cell A1 selection is kept anyway so all three drivers
# have the same shape.
#
# No results dialog either - Calc opens a "500 results found" box that has to be
# closed. The Find & Replace window itself does stay up and IS closed here, or
# the checkpoint photographs it.
NAME 'A1'; sleep 3
K ctrl+f; sleep 10
T 'Cormorant'; sleep 2
CLICK 664 440; sleep 1
T 'Shearwater'; sleep 2
CLICK 853 453; sleep 30
CLICK 853 553
CP "Replace all" 8

# --- 16. Insert chart --------------------------------------------------------
# The Chart Wizard opens on **Column** already selected, so Finish alone gives
# what the script asks for - it serialises as chart:class="chart:bar", which is
# what the ground truth reads. (Gnumeric's guru opens on XY scatter and needs
# Column chosen explicitly.) Finish leaves the chart in edit mode; the click
# outside is what leaves it.
CLICK 200 868; sleep 6
NAME 'A1:B7'; sleep 4
CLICK 116 9; sleep 2
CLICK 150 419; sleep 20
CLICK 726 724; sleep 10
CLICK 1100 700
CP "Insert chart" 10

# --- 17. Save ----------------------------------------------------------------
# No format prompt - ODS is the native format. Confirmed by File > Save going
# grey afterwards, not by the screen.
K ctrl+s
CP "Save" 30

# --- 18. Export PDF ----------------------------------------------------------
# File > Export as PDF. Two dialogs, and the second one has the trap.
#
#   PDF Options: Range defaults to **All**. Calc's equivalent defaults to
#   "Selection/Selected sheet(s)", so the one place the two suites could have
#   shared a trap is the one place they differ.
#
#   Export: the File name field arrives PRE-FILLED with `parrot-ledger` and the
#   text is NOT selected, so a typed path is appended - the first attempt here
#   wrote `/tmp/parrot-ledger.pdfparrot-ledger.pdf` and reported success. Same
#   shape as the Name Box, in a different dialog. Triple-click first.
CLICK 15 9; sleep 2
CLICK 100 315; sleep 12
CLICK 880 618; sleep 8
X mousemove 715 511; sleep 0.5; X click --repeat 3 1; sleep 1
T '/tmp/parrot-ledger.pdf'; sleep 2
K Return
CP "Export PDF" 50

# Stop the recorder. Without this record-macro.py keeps recording and
# record-session.sh's `wait` never returns.
echo "=== done - stopping the recorder ==="
K Pause
sleep 2
