#!/usr/bin/env bash
# Drive Gnumeric through applications/spreadsheets/script.md while
# record-macro.py records the input. One block per script line, each ending in a
# checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md, measured by driving this sequence by hand
# and checking common/check-result.sh at the end of it. Do not edit this file
# while it is running.
set -euo pipefail

CLASS=gnumeric
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }

# Select a range through the Name Box.
#
# TRIPLE-click, where LibreOffice Calc's driver single-clicks. Gnumeric's Name
# Box does not select its contents on focus, so a single click and a typed
# address gives `A352A1:H20001` - which is not a reference, so Return does
# nothing at all and the selection silently stays where it was. Measured both
# ways; see MEASUREMENTS.md.
NAME() { X mousemove 75 151; sleep 0.4; X click --repeat 3 1; sleep 1; T "$1"; K Return; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - which would be baked into the reference screenshot.
park() { X mousemove 1100 700; sleep 1; }

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The assertion earns its place here twice over: Gnumeric's filter dropdown is a
# separate 82x209 X window carrying the application's own WM_CLASS, and it sorts
# AHEAD of the document window in `xdotool search`. A checkpoint taken with one
# open photographs the dropdown.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Gnumeric ==="

# --- 1. Load app -------------------------------------------------------------
# The recorder has launched `gnumeric` and waited for the window; this waits for
# the first paint of the empty Book1.gnumeric. Nothing to dismiss.
sleep 35
CP "Load app" 5

# --- 2. Open workbook --------------------------------------------------------
# Typing a path that begins with `/` makes the GTK file chooser open its location
# entry by itself, so there is nothing to click and no Ctrl+L. Book1.gnumeric is
# REPLACED rather than added to, so there is still exactly one window.
K ctrl+o; sleep 6
T '/tmp/parrot-ledger.ods'; sleep 3
K Return
CP "Open workbook" 50

# --- 3. Jump to end ----------------------------------------------------------
K ctrl+End
CP "Jump to end" 10

# --- 4. Freeze the header ----------------------------------------------------
# Freezing is relative to the cursor, so the cursor goes to A2 first.
K ctrl+Home; sleep 4
K Down; sleep 1
CLICK 103 12; sleep 2
CLICK 148 62
CP "Freeze the header" 5

# --- 5. Page through ---------------------------------------------------------
# Ends on A352 - 35 rows a press, where Calc manages 41. Three toolbars.
for _ in $(seq 1 10); do K Next; sleep 0.6; done
CP "Page through" 5

# --- 6. Switch sheets --------------------------------------------------------
CLICK 143 874; sleep 5
CLICK 232 874; sleep 5
CLICK 55 874
CP "Switch sheets" 6

# --- 7. Sort -----------------------------------------------------------------
# THE SORT SPECIFICATION ARRIVES PRE-POPULATED WITH ALL EIGHT COLUMNS, in sheet
# order. Pressing OK would sort by Date, then Site, then Sensor - a perfectly
# ordered sheet that is ordered by the wrong thing, and nothing says so. Calc
# pre-populates exactly one key; this one pre-populates eight.
#
# So: Clear, then add Reading as the only key.
NAME 'A1:H20001'; sleep 6
CLICK 391 12; sleep 2
CLICK 415 37; sleep 6
CLICK 882 533; sleep 2          # Clear
CLICK 658 658; sleep 1          # the reference field
T 'E1:E20001'; sleep 1
CLICK 882 658; sleep 2          # Add
CLICK 878 699                   # OK
CP "Sort" 30

# --- 8. Enter formula --------------------------------------------------------
# The comma is the argument separator here too. Gnumeric stores the function name
# lower-cased - =round(E2*F2,2) - which is cosmetic and does show in the
# reference screenshot.
NAME 'I2'; sleep 3
T '=ROUND(E2*F2,2)'; sleep 2
K Return
CP "Enter formula" 5

# --- 9. Fill down ------------------------------------------------------------
# The status bar sum after this is SHORT BY THE SOURCE CELL - 74641367.1 against
# the 74641377.6 that block 10 computes, a difference of exactly I2. Block 10 is
# the number to believe.
NAME 'I2:I20001'; sleep 6
K ctrl+d
CP "Fill down" 35

# --- 10. Total ---------------------------------------------------------------
NAME 'K1'; sleep 3
T '=SUM(I2:I20001)'; sleep 2
K Return
CP "Total" 10

# --- 11. Recalculate ---------------------------------------------------------
# F9. Gnumeric has no separate hard recalculation.
K F9
CP "Recalculate" 20

# --- 12. Filter --------------------------------------------------------------
# No keyboard shortcut for the autofilter here, so it is the Data > Filter
# submenu. The dropdown that follows is a plain single-select list, so Turbine is
# one click - no search box, no checkboxes, no "untick All" step.
NAME 'A1:H20001'; sleep 6
CLICK 391 12; sleep 2
X mousemove 415 112; sleep 2      # hover Filter to open the submenu
CLICK 653 111; sleep 8            # Add Auto Filter
CLICK 442 202; sleep 4            # the Category dropdown
CLICK 374 398                     # Turbine
CP "Filter" 20

# --- 13. Clear filter --------------------------------------------------------
# (All) restores every row and LEAVES the filter buttons in place, where Calc's
# Ctrl+Shift+L removes them. Both satisfy the script.
CLICK 442 202; sleep 4
CLICK 370 223
CP "Clear filter" 18

# --- 14. Format numbers ------------------------------------------------------
# Gnumeric's Number category defaults to ZERO decimal places, so the spinner is
# clicked twice. The `+` button rather than typing into the field: a typed value
# in a spin box is what silently produced 1218 from 12 and 18 in the word
# processor group.
NAME 'E2:E20001'; sleep 6
K ctrl+1; sleep 8
CLICK 454 342; sleep 3          # the Number category
CLICK 727 330; sleep 1          # decimals 0 -> 1
CLICK 727 330; sleep 2          # decimals 1 -> 2
CLICK 993 699                   # OK
CP "Format numbers" 15

# --- 15. Replace all ---------------------------------------------------------
# No scope trap: Gnumeric's Scope group defaults to "Entire workbook" where Calc
# silently scopes to the selection. The single-cell selection is kept anyway so
# both drivers have the same shape. No results dialog to close afterwards.
NAME 'A1'; sleep 3
K ctrl+h; sleep 8
T 'Cormorant'; sleep 2
CLICK 785 413; sleep 1
T 'Shearwater'; sleep 2
CLICK 961 649
CP "Replace all" 25

# --- 16. Insert chart --------------------------------------------------------
# TWO differences from Calc, either of which produces a plausible wrong result:
#
#   the guru opens on XY (scatter), so Column has to be chosen explicitly - it
#   serialises as chart:class="chart:bar", which is what the ground truth reads;
#
#   Insert does not insert. It closes the guru and ARMS a placement tool, and the
#   chart exists only once the sheet has been dragged. Same shape as Calligra
#   Words' image shape tool.
CLICK 232 874; sleep 5
NAME 'A1:B7'; sleep 3
CLICK 154 12; sleep 2
CLICK 181 137; sleep 12         # Chart...
CLICK 504 301; sleep 3          # plot type: Column
CLICK 950 759; sleep 6          # Insert - arms the placement tool
X mousemove 300 230; sleep 0.5  # place it by dragging
X mousedown 1; sleep 0.5
X mousemove 820 520; sleep 0.5
X mouseup 1; sleep 6
CLICK 1100 700                  # deselect
CP "Insert chart" 8

# --- 17. Save ----------------------------------------------------------------
# No format prompt, despite .gnumeric being the native format. Measured.
K ctrl+s
CP "Save" 20

# --- 18. Export PDF ----------------------------------------------------------
# Gnumeric has no "Export as PDF"; this is the print-to-file route script.md
# allows. Three things in order, and the first two are both required:
#
#   "Print to File" is the only printer and is NOT selected on open, so the Print
#   button starts insensitive;
#
#   the Gnumeric Print Range tab defaults to "Active workbook sheet", which would
#   export the Summary sheet alone - the same class of silent default as Calc's
#   PDF export, in a completely unrelated codebase.
#
# There is no file dialog: Gnumeric derives /tmp/parrot-ledger.pdf from the
# document, which is where the ground truth looks.
K ctrl+p; sleep 12
CLICK 503 301; sleep 3          # Print to File
CLICK 697 232; sleep 3          # the Gnumeric Print Range tab
CLICK 438 268; sleep 2          # All workbook sheets
CLICK 996 701
CP "Export PDF" 35

# Stop the recorder. Without this record-macro.py keeps recording and
# record-session.sh's `wait` never returns.
echo "=== done - stopping the recorder ==="
K Pause
sleep 2
