#!/usr/bin/env bash
# Drive Fractal through applications/chatclients/script.md while record-macro.py
# records the input. One block per script line, each ending in a checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowraise`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay.
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
#
# THE RULES THIS FILE IS BUILT AROUND, all measured. The first three are
# inherited from the other clients; the rest are Fractal's own and every one of
# them cost a wrong click or a silent no-op to find:
#
#   1. Never click a room in the unfiltered room list. Fractal sorts it by
#      activity and the scenario moves rooms around as it touches them. Every
#      room is opened through the sidebar search, which filters to one row.
#
#   2. A dialog closing means NOTHING. Block 17's chooser closes cheerfully
#      having attached nothing at all. Every mutating block here was verified
#      with matrix-truth.py, and blocks 14 and 15 had their target EVENT
#      resolved, not just their count checked.
#
#   3. A mapped window is not a painted window - see wait_paint() below and the
#      Element write-up that cost a recording to produce.
#
#   4. PARK IN THE MARGIN, NOT ON THE TIMELINE. GTK tooltips are separate X
#      windows that match --class fractal, and in Field Photos the middle of the
#      timeline is an image with a filename tooltip. (400, 400) is the left
#      margin of the centred content column and raises nothing.
#
#   5. `Prior` does not scroll Fractal's timeline - the composer holds focus.
#      Scrolling is the wheel, measured at 86 px per notch, so 9 notches is one
#      screen. See the table in MEASUREMENTS.md.
#
#   6. The message context menu grows UPWARDS from the pointer - its origin is
#      (click_x - 1, click_y - height) - and the own-message menu is 369 tall
#      rather than 305 because it gains Edit and Remove. Block 16's coordinates
#      cannot be copied from block 14's.
#
#   7. The `⋮` room menu CHANGES SIZE per room. @parrot cannot invite in the
#      corpus rooms, so Invite New Members is absent there and Leave Room moves
#      up by 32 px. Block 21 uses the two-item position, block 20 the
#      three-item one.
set -euo pipefail

X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
RCLICK() { X mousemove "$1" "$2"; sleep 0.4; X click 3; }

# Wheel notches at a point. 86 px each, measured identical in an image room and
# a text room, so 9 notches is one 790 px viewport. This is Fractal's stand-in
# for the `Prior` loop the other four clients use.
WHEEL() { X mousemove "$1" "$2"; sleep 0.4; for _ in $(seq 1 "$3"); do X click 4; done; }
SCREENS() { for _ in $(seq 1 "$1"); do WHEEL 860 400 9; sleep "$2"; done; }

# Open a room through the sidebar search. The FIRST call has to open the search
# field with the toolbar button; every later one clicks into the field that is
# already there, because the × that block 12 uses to clear the filter leaves the
# field open but NOT focused - typing straight after it goes nowhere at all, and
# leaves a byte-identical screen behind to prove it.
#
# ctrl+a rather than a second × click: one action instead of two, and it works
# whether the field is empty or still holds the previous block's room name.
ROOM_FIRST() { CLICK 221 27;  sleep 2; T "$1"; sleep 4; CLICK 144 119; sleep "${2:-14}"; }
ROOM()       { CLICK 144 68;  sleep 1; K ctrl+a; sleep 1; T "$1"; sleep 4; CLICK 144 119; sleep "${2:-14}"; }

# Park the pointer somewhere inert before every capture. See rule 4: this must
# be the left margin, not the timeline. Measured across all 23 checkpoints as
# leaving exactly one window matching the class.
park() { X mousemove 400 400; sleep 1; }

# The size of a full-screen PNG, in bytes. `import` is a passive X client - it
# reads the root window and sends no input event - so calling it mid-recording
# does not put anything into the macro.
SHOT() { Q 'export DISPLAY=:99; import -window root /tmp/parrot-probe.png 2>/dev/null; stat -c %s /tmp/parrot-probe.png'; }

# Just above a blank or spinner screen, and well below any real one. Measured on
# Element: the loading spinner is ~2.4 kB, real screens are 99 kB and up. The
# threshold must sit near the spinner, not in the middle - a value picked off
# the photographic welcome screen condemns every real screen after it.
#
# LOWER HERE THAN IN THE OTHER DRIVERS, and this is calibration rather than a
# weakening. Element's sparsest real screen is ~99 kB, so 30000 has enormous
# headroom there. Fractal's is not: block 20 ends on a newly created empty room
# - a white timeline, "The conversation starts here.", "2 room changes" and a
# one-row sidebar - which is a genuine, fully painted screen at **25 kB**. At
# 30000 that block warned on every run, which is worse than useless: a guard
# that cries wolf on a known-good block is one nobody reads on the block that
# matters.
#
# 15000 still sits far above anything blank. For reference, measured in this
# client: welcome screen 40 kB, decoded Field Photos 45 kB (gradients compress
# far better than text, so a photo screen is SMALLER than a text one here),
# text rooms 79-108 kB, empty new room 25 kB.
PAINTED=15000

# Block until the display actually has the client on it, rather than guessing
# with a sleep. Aborts the run instead of driving a screen that is not there: a
# recording made against a loading screen looks successful in every log line and
# is worthless.
wait_paint() {
    local limit="${1:-420}" waited=0 sz
    while (( waited < limit )); do
        sz="$(SHOT)"
        if [[ "${sz:-0}" -gt "$PAINTED" ]]; then
            echo "  [paint] first painted frame after ${waited}s"
            return 0
        fi
        sleep 5; waited=$(( waited + 5 ))
    done
    echo "  FATAL: nothing painted after ${limit}s - the app never came up" >&2
    exit 1
}

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# THE PORTAL CHECK IS NOT COSMETIC. SchildiChat's guard catches its file chooser
# because the chooser's WM_CLASS starts with the client's name. Fractal's
# chooser is the XDG portal - WM_CLASS "xdg-desktop-portal-gtk" - which does not
# match --class fractal at all, so without this line block 17 could capture a
# screen with a file dialog across it and report one window, right geometry, no
# warning. Measured; see MEASUREMENTS.md block 17.
#
# The count check does real work in this client rather than being a formality:
# Room Details, the invite dialog, the `⋮` menu, the emoji picker and every GTK
# tooltip are all separate windows that match the class. What it cannot see are
# the IN-WINDOW modals - settings, Join a Room, New Room, the image viewer -
# which is why the blocks that open those close them explicitly.
CP() {
    sleep "${2:-4}"
    park
    n="$(Q "xdotool search --onlyvisible --class fractal | wc -l")"
    geo="$(Q "w=\$(xdotool search --onlyvisible --class fractal | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    [[ "$n" == "1" ]] || echo "  WARNING: '$1' matched ${n} windows, not 1 - a menu, tooltip or Room Details window is still open"
    p="$(Q "xdotool search --onlyvisible --class xdg-desktop-portal-gtk | wc -l")"
    [[ "${p:-0}" == "0" ]] || echo "  WARNING: '$1' has the PORTAL FILE CHOOSER open - it does not match --class fractal"
    sz="$(SHOT)"
    [[ "${sz:-0}" -gt "$PAINTED" ]] || echo "  WARNING: '$1' would capture a blank or loading screen (${sz}B)"
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Fractal ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `flatpak-session flatpak run
# org.gnome.Fractal`. The wrapper drops to uid 1001, starts a session bus and
# unlocks a secret service, and sets XDG_CURRENT_DESKTOP so xdg-desktop-portal
# picks an implementation - without which Fractal stops on a full-window "Secret
# Portal Error" and goes no further. See ../common/install-flatpak.sh.
#
# The head time is deliberately the SAME as nheko's, Element's and
# SchildiChat's - 20 s in record-session.sh, 25 s here, 5 s in CP - because it
# is measured time, and a client given a longer head burns more energy for no
# reason of its own.
wait_paint
sleep 25
CP "Load app" 5

# --- 2. Sign in --------------------------------------------------------------
# Homeserver FIRST, and auto-discovery has to be turned OFF before the address
# can be typed: discovery probes https://parrot.test/.well-known/matrix/client
# and this group has no TLS and no such host. Fractal offering a manual override
# is the whole reason it can be measured here at all - a client that only
# autodiscovers cannot be, which is what removed the sixth entrant.
CLICK 720 622; sleep 6                       # Log In
CLICK 719 708; sleep 5                       # Advanced... -> Homeserver Discovery
CLICK 912 484; sleep 2                       # Auto-Discovery off
CLICK 946 323; sleep 3                       # close the dialog
CLICK 700 536; sleep 1                       # the field, now "Homeserver URL"
T 'http://matrix.parrot.test:8008'; sleep 2
CLICK 719 646; sleep 10                      # Next
T 'parrot'; sleep 1                          # Matrix Username is already focused
CLICK 700 522; sleep 1                       # Password
T 'parrot'; sleep 1
CLICK 719 602                                # Next
CP "Sign in" 25

# --- 3. Initial sync ---------------------------------------------------------
# The measurement this block exists for: 8000 messages, 66 rooms and a
# 509-member room arriving at once.
#
# It is NOT the same block here as elsewhere, and that has to be said in the
# results. Fractal's account-recovery prompt cannot be dismissed - Back and
# Escape both undo the sign-in - so going through it is the only way in, and it
# does real cryptographic work no other client in the group does: a cross-
# signing identity and a key backup.
#
# THE MIDDLE SCREEN SHOWS A RANDOM RECOVERY KEY, different on every run, in a
# large high-contrast block. A checkpoint taken there could never match a
# replay. The checkpoint goes after Start Chatting, with all three screens
# behind it.
CLICK 719 644; sleep 20                      # Set Up, passphrase left empty
CLICK 719 580; sleep 8                       # Done - NEVER checkpoint this screen
CLICK 719 642                                # Start Chatting
CP "Initial sync" 40

# --- 4. Open busy room -------------------------------------------------------
# The only ROOM_FIRST: the search field is closed until the toolbar button opens
# it.
ROOM_FIRST 'Aurora Release' 22
CP "Open busy room" 8

# --- 5. Scroll back ----------------------------------------------------------
# Ten screens, nine notches each, with a settle between - script.md asks for
# each batch of older messages to finish loading before scrolling again, and 90
# notches in one burst outruns the loader.
SCREENS 10 2
CP "Scroll back" 8

# --- 6. Jump to live ---------------------------------------------------------
# Not `End`: the composer holds focus, so End is a text-cursor key and never
# reaches the timeline. Measured in all four clients so far.
CLICK 1390 805
CP "Jump to live" 10

# --- 7. Open member list -----------------------------------------------------
# Room Details is a REAL SECOND WINDOW here (640x780), not an in-window panel as
# in Element and SchildiChat, so the checkpoint guard would catch it - but it is
# closed explicitly anyway, so the block boundary means the same thing it means
# in the other clients.
#
# The `⋮` menu in a corpus room is the two-item one: Room Details, Leave Room.
CLICK 1297 27; sleep 3                       # room menu
CLICK 1296 79; sleep 6                       # Room Details
CLICK 319 325; sleep 14                      # Members 509
CLICK 611 27                                 # close
CP "Open member list" 5

# --- 8. Open photo room ------------------------------------------------------
# 400 images. They render only because the homeserver sets
# enable_authenticated_media false (see ../nheko/MEASUREMENTS.md) AND because
# the media-preview policy is seeded to "on" for this scenario - Fractal
# implements MSC4278 and its default hides previews in public rooms, which Field
# Photos is. See ../common/seed-media-previews.sh.
ROOM 'Field Photos' 20
CP "Open photo room" 8

# --- 9. View image full size -------------------------------------------------
# An in-window viewer, closed before the checkpoint for the same block-boundary
# reason as block 7. The header confirms the target is
# reservoir-at-first-light.jpg, which is the image script.md names.
CLICK 853 625; sleep 12
CLICK 28 27                                  # back arrow
CP "View image full size" 5

# --- 10. Scroll thumbnails ---------------------------------------------------
SCREENS 5 3
CP "Scroll thumbnails" 8

# --- 11. Filter room list ----------------------------------------------------
# The field must be CLICKED first. Block 12 cleared it with the ×, which leaves
# it open and unfocused, and typing into it then does nothing whatsoever.
CLICK 144 68; sleep 1
K ctrl+a; sleep 1
T 'windvane'
CP "Filter room list" 5

# --- 12. Open filtered room --------------------------------------------------
# Clicking the row is safe here for the same reason as in the other clients: the
# list has been filtered to exactly one result.
CLICK 144 119; sleep 18
CLICK 262 68                                 # clear the filter, as script.md asks
CP "Open filtered room" 6

# --- 13. Send message --------------------------------------------------------
CLICK 858 872; sleep 2
T 'Thank you so much'; sleep 1
K Return
CP "Send message" 8

# --- 14. Reply to message ----------------------------------------------------
# The menu hangs its BOTTOM edge off the pointer: right-clicking (686, 694) puts
# a 192x305 window at (685, 389), so Reply lands at (722, 516).
RCLICK 686 694; sleep 3
CLICK 722 516; sleep 4                       # Reply
T 'Agreed, going out today'; sleep 1
K Return
CP "Reply to message" 8

# --- 15. React to message ----------------------------------------------------
# TARGET THE ORIGINAL, NOT THE QUOTE. The reply just sent renders a quoted copy
# of Nadia's text at y~813; the original is at y~628. Reacting to the quote
# attaches the reaction to the reply event instead, and only ground truth can
# tell the difference - which is why this was checked by resolving the target
# event, not by looking at the screen.
#
# Through the PICKER, not the menu's quick-reaction row. The 👍 in the menu
# would be one click, but script.md says "through the client's emoji picker" and
# the other clients all render a full picker before clicking 👍 - taking the
# shortcut would skip work the rest of the group is being charged for.
RCLICK 686 628; sleep 3
CLICK 843 395; sleep 4                       # ••• -> emoji picker
CLICK 589 605; sleep 3                       # Body & Clothing tab
CLICK 843 458                                # 👍, last of the fourth row
CP "React to message" 8

# --- 16. Edit message --------------------------------------------------------
# Own messages are LEFT-aligned in Fractal, unlike SchildiChat's right-aligned
# bubbles, so this aims at the left of the timeline. The own-message menu is 369
# tall rather than 305 because it gains Edit and Remove, so Edit is at
# (648, 551) and not where block 14's Reply was.
RCLICK 618 761; sleep 3
CLICK 648 551; sleep 4                       # Edit
K ctrl+a; sleep 1
T 'Thank you so much indeed'; sleep 1
K Return
CP "Edit message" 8

# --- 17. Upload image --------------------------------------------------------
# PASTED, NOT CHOSEN - and this is the one block where Fractal is not doing what
# the other four do. The reason is in usage_scenario.yml: Fractal's chooser is
# the XDG portal, the portal hands files over through the FUSE-backed document
# portal, and that mount needs CAP_SYS_ADMIN, which this group dropped on
# purpose. Driven through the chooser instead, this block attaches NOTHING and
# says so nowhere - the dialog closes, the timeline is unchanged, and only the
# absence of an m.image event on the server gives it away.
#
# What is still measured: the same 762 kB image encoded, uploaded and rendered
# as a thumbnail. What is not: the file chooser itself. The event also arrives
# named `image.png`, because a clipboard image has no filename. Both go in the
# results.
#
# The clipboard is loaded by ../common/seed-clipboard.sh, the last setup-command,
# and the xclip that owns it stays alive for the whole session - X11 keeps no
# copy of its own.
#
# The paste raises a preview dialog with Cancel / Send. SEND IS THE STEP THAT
# ACTUALLY UPLOADS; the dialog closing means nothing, exactly as SchildiChat's
# second confirmation step does.
CLICK 858 872; sleep 2                       # composer, so the paste lands in it
K ctrl+v; sleep 10                           # preview dialog appears
CLICK 861 272                                # Send - the step that matters
CP "Upload image" 16

# --- 18. Echo round trip -----------------------------------------------------
ROOM 'Parrot Echo' 14
CLICK 858 872; sleep 2
T 'ping'; sleep 1
K Return
CP "Echo round trip" 12

# --- 19. Join room -----------------------------------------------------------
# The menu item rather than its Ctrl+L accelerator, so the recording does not
# depend on where focus happens to be. "Join a Room" is an in-window modal, so
# the window count stays at one throughout.
CLICK 261 27; sleep 2                        # hamburger
CLICK 209 142; sleep 4                       # Join Room...
T '#parrot-lobby:parrot.test'; sleep 2
CLICK 719 533; sleep 8                       # Look Up -> room preview
CLICK 719 620                                # Join
CP "Join room" 18

# --- 20. Create room ---------------------------------------------------------
# Fractal defaults to PRIVATE but with encryption OFF - unlike Element and
# SchildiChat, which default to private AND encrypted. Choosing Public removes
# the encryption toggle and makes a Main Address mandatory; Create Room stays
# disabled until it is filled.
CLICK 261 27; sleep 2                        # hamburger
CLICK 212 110; sleep 4                       # New Room...
T 'Parrot benchmark'; sleep 2
CLICK 581 601; sleep 3                       # Public
CLICK 670 690; sleep 1                       # Main Address
T 'parrot-benchmark'; sleep 2
CLICK 719 758; sleep 16                      # Create Room

# The invite. This is the THREE-item `⋮` menu - it is our own room, so Invite
# New Members is present and Leave Room sits below it. The invite window is a
# separate 640x780 X window titled "Room Details", and it does match the class,
# so the checkpoint guard catches it if it is ever left open.
CLICK 1297 27; sleep 3                       # room menu
CLICK 1267 112; sleep 5                      # Invite New Members...
T '@alice:parrot.test'; sleep 6
CLICK 300 140; sleep 3                       # the result row - ticks a checkbox
CLICK 583 27                                 # Invite
CP "Create room" 12

# --- 21. Leave room ----------------------------------------------------------
# THE TWO-ITEM MENU. @parrot cannot invite in the corpus rooms, so Invite New
# Members is absent and Leave Room is 32 px higher than it was in block 20.
# Clicking block 20's position here lands below the menu entirely, dismisses it
# and does nothing - silently.
ROOM 'Parrot Lobby' 14
CLICK 1297 27; sleep 3                       # room menu
CLICK 1296 124; sleep 4                      # Leave Room
CLICK 803 499                                # confirm Leave
CP "Leave room" 12

# --- 22. Idle quiet ----------------------------------------------------------
ROOM 'Parrot Firehose' 20
sleep 60
CP "Idle quiet" 4

# --- 23. Idle receiving ------------------------------------------------------
# `drip` is the trigger: the bot posts drip 01..24, one every 5 s, scheduled
# against a fixed start so the burst does not drift.
CLICK 858 872; sleep 2
T 'drip'; sleep 1
K Return
sleep 130
CP "Idle receiving" 6

echo "=== driven ==="
