#!/usr/bin/env bash
# Drive Apache OpenOffice Writer through applications/wordprocessors/script.md
# while record-macro.py records the input. One block per script line, each
# ending in a checkpoint.
#
# Runs on the host and sends events into the container with xdotool, so that
# xmacrorec2 - watching the same X display from inside - records real input
# events. There is no `xdotool windowactivate`, `windowfocus` or `windowsize`
# here: none of those is an input event, so xmacrorec2 would not record them and
# they would silently not happen on replay. The window is pinned by the window
# manager instead (see usage_scenario.yml).
#
# Every landmark is in MEASUREMENTS.md. Do not edit this file while it is
# running: bash reads a script incrementally, and an edit that moves byte
# offsets corrupts the run in flight.
set -euo pipefail

CLASS=openoffice
X() { docker exec -e DISPLAY=:99 window-container xdotool "$@" >/dev/null 2>&1; }
Q() { docker exec -e DISPLAY=:99 window-container bash -c "$1" 2>/dev/null; }

T()  { X type --delay 45 -- "$1"; }
K()  { X key --clearmodifiers "$1"; }
CLICK()  { X mousemove "$1" "$2"; sleep 0.4; X click 1; }
CLICK2() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 2 1; }
CLICK3() { X mousemove "$1" "$2"; sleep 0.4; X click --repeat 3 1; }

# Park the pointer somewhere inert before every capture. xdotool leaves it
# wherever it last clicked, and a pointer resting on a toolbar button raises a
# tooltip - which would be baked into the reference screenshot and then fail to
# reappear on replay. AOO does this too: docking a toolbar during measuring left
# an "Apply Style" tooltip on screen.
#
# 120,450 is the grey workspace to the left of the page, which spans x=177..1003
# at 100%. Not the toolbar, not the page, not the sidebar, and nothing hovers
# there. It is also clear of the floating Table toolbar at 22,66 307x77.
park() { X mousemove 120 450; sleep 1; }

# What the document window's title should contain once the document is open.
# Empty for block 1, which is still "Untitled 1 - OpenOffice Writer".
EXPECT_TITLE=""

# Checkpoint: settle, park, assert what would be captured, then press the
# recorder's hotkey.
#
# The size assertion is the one every app in this group needs. The checkpoint
# capture - timed_xmacro.py, not record-macro.py itself - runs
# `xdotool search --onlyvisible --class <class> | head -n1`, the FIRST match and
# not the largest, and every AOO dialog, message box and floating toolbar shares
# the document's WM_CLASS. (record-macro.py's own window search does take the
# largest, but that is only used to find the app at startup.)
#
# The title assertion is here because the size assertion alone cannot catch
# AOO's particular version of that. Opening the document REUSES the frame, and
# during the swap a window list briefly shows both "Untitled 1" and
# "parrot-report.odt" at 1440x900 - so a checkpoint landing there would pass a
# size check while photographing an empty document. The X window id turns out to
# be the same one, so this cannot actually happen, but a check that costs one
# xdotool call is cheaper than relying on that staying true.
CP() {
    sleep "${2:-3}"
    park
    geo="$(Q "w=\$(xdotool search --onlyvisible --class ${CLASS} | head -n1);
              xdotool getwindowgeometry --shell \$w | grep -E '^(WIDTH|HEIGHT)='" | tr '\n' ' ')"
    case "$geo" in
        *"WIDTH=1440"*"HEIGHT=900"*) ;;
        *) echo "  WARNING: '$1' would capture ${geo}" ;;
    esac
    if [[ -n "$EXPECT_TITLE" ]]; then
        title="$(Q "xdotool getwindowname \$(xdotool search --onlyvisible --class ${CLASS} | head -n1)")"
        case "$title" in
            *"$EXPECT_TITLE"*) ;;
            *) echo "  WARNING: '$1' would capture window titled '${title}'" ;;
        esac
    fi
    K Scroll_Lock
    sleep 2
    echo "  [checkpoint] $1"
}

echo "=== driving Apache OpenOffice Writer ==="

# --- 1. Load app -------------------------------------------------------------
# record-macro.py has already launched `soffice -writer` through the
# startcommand and waited for the window. What it cannot wait for is AOO
# finishing its first paint.
#
# Nothing has to be dismissed: the seeded profile turns off the first-start
# wizard, the ODF-version update dialog and the online update check. See
# install.sh for why each one is there.
sleep 45
CP "Load app" 5

# --- 2. Open document --------------------------------------------------------
# AOO uses its own file picker, not GTK's. The File name field has focus when
# the dialog opens, so nothing is clicked. The empty `Untitled 1` window is
# REUSED rather than added to - same X window id, retitled - so there is still
# exactly one window afterwards.
#
# The ODF Version Conflict modal would appear here if the profile had not turned
# it off: the document is ODF 1.3 and AOO implements 1.2.
K ctrl+o; sleep 4
T '/tmp/parrot-report.odt'; sleep 2
K Return
EXPECT_TITLE="parrot-report.odt"
CP "Open document" 45

# --- 3. Page through ---------------------------------------------------------
# Ends on "Page 7 / 98". LibreOffice reaches pages 6 and 7 with the same ten
# presses because it spans two pages at 100%; AOO shows one.
for _ in $(seq 1 10); do K Next; sleep 0.6; done
CP "Page through" 5

# --- 4. Jump to end ----------------------------------------------------------
K ctrl+End
CP "Jump to end" 20

# --- 5. Jump to start --------------------------------------------------------
K ctrl+Home
CP "Jump to start" 15

# --- 6. Zoom -----------------------------------------------------------------
# Double-clicking the zoom percentage in the status bar opens `Zoom & View
# Layout` directly, the same route LibreOffice uses. The dialog came up at the
# identical position both times it was opened while measuring.
CLICK2 1424 890; sleep 4
CLICK  513 474; sleep 1          # Variable radio
CLICK3 678 475; sleep 1          # its field, contents selected
T '150%'; sleep 1
CLICK  682 519; sleep 6          # OK
CLICK2 1424 890; sleep 4
CLICK  513 451; sleep 1          # 100 % radio
CLICK  682 519
CP "Zoom" 6

# --- 7. Find word ------------------------------------------------------------
# Ctrl+F opens the FULL Find & Replace dialog - AOO has no find toolbar. `Find`
# and `Find All` are greyed out until the field has text in it.
#
# After the third Find: "Page 3 / 98", with Cormorant selected. LibreOffice lands
# on page 3 of 98 too, which is a free cross-check that both stepped through the
# same three matches.
K ctrl+f; sleep 4
T 'Cormorant'; sleep 2
CLICK 854 349; sleep 3           # Find
CLICK 854 349; sleep 3
CLICK 854 349; sleep 3
K Escape
CP "Find word" 4

# --- 8. Replace all ----------------------------------------------------------
# Ctrl+F again, NOT Ctrl+H. Ctrl+H is not bound in AOO at all: Edit > Find &
# Replace... reads Ctrl+F, and that one dialog is both halves. Ctrl+H produces no
# dialog, no message and no error.
#
# The dialog reopens with Cormorant still in the Search field and selected, so
# typing overwrites it. It is typed in full anyway rather than depending on that.
#
# Replace All is the click at 854,453 - 28 px below Replace at 854,425.
K ctrl+f; sleep 4
T 'Cormorant'; sleep 1
CLICK 660 440; sleep 1           # Replace with field
T 'Shearwater'; sleep 1
CLICK 854 453; sleep 15          # -> "Search key replaced 120 times."
CLICK 719 471; sleep 3           # OK on the count box
CLICK 854 553; sleep 3           # Close
CP "Replace all" 4

# --- 9. Type paragraph -------------------------------------------------------
# Return first, so the block is its own paragraph rather than being glued to the
# end of the last one. One keystroke at a time rather than a paste: the point of
# the block is what typing into a 98-page document costs.
K ctrl+End; sleep 12
K Return; sleep 2
T 'The kestrel circled above the reservoir before dawn.'; sleep 2; K Return; sleep 2
T 'Three technicians logged the reading and filed the sheet.'; sleep 2; K Return; sleep 2
T 'Nothing in the record explained the drop in pressure.'
CP "Type paragraph" 4

# --- 10. Bold a line ---------------------------------------------------------
# AOO's status bar carries no selection word count, so there is no numeric
# confirmation of the selection here the way there is in LibreOffice.
K shift+Home; sleep 2
K ctrl+b
CP "Bold a line" 3

# --- 11. Resize the text -----------------------------------------------------
# Enter in the size box returns focus to the document, but the selection is
# STILL LIVE afterwards - a printable character sent next would replace the
# whole line. The next block only uses the style box, so that is safe here.
CLICK3 362 59; sleep 2
T '18'; sleep 1
K Return
CP "Resize the text" 4

# --- 12. Apply heading -------------------------------------------------------
# The style box, same behaviour. Ends with "Outline Numbering : Level 1" in the
# status bar. This overrides the 18 pt from block 11, which is what the script
# asks for and is identical in every application.
CLICK3 105 59; sleep 2
T 'Heading 1'; sleep 1
K Return
CP "Apply heading" 5

# --- 13. Insert image --------------------------------------------------------
# Insert > Picture > From File... - a submenu, unlike LibreOffice's single
# Insert > Image. The menus are drawn inside the main window rather than as their
# own X windows, so they never appear in a window list.
#
# The Escape at the end is required, not tidiness. The inserted image arrives
# selected, which raises a floating Picture toolbar as its OWN X window at
# 0,44 387x51 - and `import -window` returns everything it covers as solid
# black, so the reference screenshot would have the menu bar replaced by a black
# rectangle. Escape deselects the image and the toolbar goes.
K ctrl+End; sleep 5
K Return; sleep 3
CLICK 116 9;  sleep 3            # Insert menu
CLICK 152 477; sleep 3           # Picture -> submenu
CLICK 300 477; sleep 5           # From File...
T '/tmp/parrot.png'; sleep 2
K Return; sleep 15
K Escape                         # drop the selection and the floating toolbar
CP "Insert image" 6

# --- 14. Insert table --------------------------------------------------------
# Ctrl+F12 only works because pin-windows.sh writes a fluxbox keys file with no
# keyboard bindings. The default one binds Control+F1..F12 to workspace
# switching and grabs them at the X server.
#
# AOO defaults the dialog to 2 columns by 2 rows, so both spin fields have to be
# set. The Name field reads "Table4", which proves the document arrived with
# exactly three tables.
#
# This block's checkpoint legitimately contains a 307x77 black rectangle at
# 22,66: the cursor ends inside the table, which raises the floating Table
# toolbar, and leaving the table is block 15's job. It is deterministic. See
# MEASUREMENTS.md before treating it as a defect.
K ctrl+End; sleep 5
K Return; sleep 3
K ctrl+F12; sleep 5
CLICK3 570 377; sleep 1; T '3'; sleep 1     # Columns
CLICK3 570 402; sleep 1; T '4'; sleep 1     # Rows
CLICK  931 335; sleep 6                     # OK
T 'Alpha'; sleep 1; K Tab; sleep 1
T 'Beta';  sleep 1; K Tab; sleep 1
T 'Gamma'
CP "Insert table" 4

# --- 15. Insert page break ---------------------------------------------------
# Ctrl+End TWICE, exactly as in LibreOffice. The cursor is in the last table cell
# after block 14, and the first Ctrl+End only goes to the end of the TABLE - the
# status bar goes Table4:C1 -> Table4:C4 and the page count does not move.
# Ctrl+Return there is a silent no-op. The second one reaches the end of the
# document, and then the break takes: "Page 100 / 100".
K ctrl+End; sleep 8
K ctrl+End; sleep 8
K ctrl+Return
CP "Insert page break" 8

# --- 16. Undo and redo -------------------------------------------------------
# A page break is a single undo unit in every application in this group, which
# is why the script exercises undo on this and not on the typed paragraph.
# 100 / 100 -> 99 / 99 -> 100 / 100.
K ctrl+z; sleep 8
K ctrl+y
CP "Undo and redo" 8

# --- 17. Save ----------------------------------------------------------------
# No dialog: ODT is AOO's native format, so nothing asks about keeping it.
K ctrl+s
CP "Save" 20

# --- 18. Export PDF ----------------------------------------------------------
# File > Export as PDF... - one level, no submenu. Range defaults to All, so the
# whole document goes.
#
# The path is typed in full even though the Export dialog already offers
# /tmp/parrot-report.pdf: that is a property of this run - the document was
# opened from /tmp - rather than of the scenario.
CLICK 15 9;    sleep 3           # File menu
CLICK 78 315;  sleep 6           # Export as PDF...
CLICK 879 618; sleep 6           # PDF Options -> Export
CLICK3 715 512; sleep 1          # file name field, contents selected
T '/tmp/parrot-report.pdf'; sleep 2
K Return
CP "Export PDF" 45

echo "=== done - stopping the recorder ==="
K Pause
sleep 2
